/**
 * Process: TFO
 */

var WORKSTEP = {
	INITIATOR: 'Initiator',
	LOGISTICS: 'Logistics Team',
	DELIVERY: 'DELIVERY',
	PROCESSING_CHECKER: 'PROCESSING CHECKER',
	PROCESSING_MAKER: 'PROCESSING MAKER',
	PP_MAKER: 'PP_MAKER',
	ASSIGNMENT_QUEUE: 'Assignment Queue',
	CUSTOMER_REVIEW: 'CUSTOMER_REVIEW',
	TSD: 'TSD',
	LEGAL_TEAM: 'LEGAL_TEAM',
	RM: 'RM',
	TREASURY: 'Treasury',
	CORRESPONDENT_BANK: 'CORRESPONDENT_BANK',
	TRADE_SALES: 'TB Sales',
	COMPLIANCE: 'COMPLIANCE',
	PMPS: 'PM Processing System',
	PCPS: 'PC Processing System',
	WORK_EXIT: 'Work Exit',
	ARCHIVAL: 'Archival',
	CUSTOMER_REFERRAL_RESPONSE: 'Customer Referral Response',
	COMPLIANCE_REFERRAL_RESPONSE: 'Compliance Referral Response',
	REPAIR_QUEUE : 'Repair',
	READ_ONLY : 'ReadOnly',
	LEGAL : 'Legalization Queue',
        SCC : 'SCC',	
	TRAYDSTREAM : 'Trayd Stream'
};

var PROPERTY_NAME = {
		DISABLE: 'disable',
		MANDATORY: 'mandatory',
		READONLY: 'readonly',
		VISIBLE: 'visible',
		CHARCASE: 'charcase'
	};

var confirmDialogButtons = {
		confirm: {
			label: 'Yes',
			className: 'btn-primary'
		},
		cancel: {
			label: 'No',
			className: 'btn-default'
		}
};

var sfrmLoad = false;

//Control Names
var FORM= 'form'; // THIS IS USED AS A PLACEHOLDER FOR FORM LOAD EVENTS ONLY
var TFO_REMARKS= 'REMARKS';
var TFO_CURR_WS= 'CURR_WS';

//Initiator Details Header Frame Controls
var TFO_WI_NAME= 'WI_NAME';
var INITIATOR_BRANCH = 'INITIATOR_BRANCH';
var INITIATOR_USERID = 'INITIATOR_USERID';
var REQ_DATE_TIME = 'REQ_DATE_TIME';
var TRNS_BAL = 'TRNS_BAL';
var TRN_STATUS = 'TRN_STATUS';

//Request Details Frame Controls
var REQUEST_TYPE = 'REQUEST_TYPE';
var REQUESTED_BY = 'REQUESTED_BY';
var PROCESS_TYPE = 'PROCESS_TYPE';
var REQUEST_CATEGORY = 'REQUEST_CATEGORY';
var SOURCE_CHANNEL = 'SOURCE_CHANNEL';

//Swift Frame Controls
var SWIFT_FETCH_MODULE = 'SWIFT_FETCH_MODULE';
var SWIFT_MESSAGE_TYPE = 'SWIFT_MESSAGE_TYPE';
var SWIFT_PROCESSING_STATUS = 'SWIFT_PROCESSING_STATUS';
var SWIFT_REASON_FOR_FILING = 'SWIFT_REASON_FOR_FILING';
var SWIFT_DEC_ON_SWIFT_MESSAGE = 'SWIFT_DEC_ON_SWIFT_MESSAGE';
var SWIFT_FIELD_21 = 'SWIFT_FIELD_21';
var SWIFT_SENDER_BIC = 'SWIFT_SENDER_BIC';

//Customer Details Tab Controls
var CID_FIRST = 'CID_Txt';
var TRANSACTION_CURRENCY = 'TRANSACTION_CURRENCY';
var TRANSACTION_REFERENCE = 'TRANSACTION_REFERENCE';
var TRANSACTION_AMOUNT = 'TRANSACTION_AMOUNT';
var RELATIONSHIP_TYPE = 'RELATIONSHIP_TYPE';
var CUSTOMER_ID = 'CUSTOMER_ID';
var CUSTOMER_NAME = 'CUSTOMER_NAME';
var TFO_ASSIGNED_CENTER = 'ASSIGNED_CENTER';
var TFO_BRANCH_CITY = 'BRANCH_CITY';
var TrnsRefNo = 'TrnsRefNo';
var ROUTE_TO_PPM = 'ROUTE_TO_PPM';
var ROUTE_TO_PM = 'ROUTE_TO_PM';
var ADCB_BILL_REF_NO  ='BILL_LN_REFRNCE';
//Initiator Workstep Hidden Fields
var IS_ACC_VALID = 'IS_ACC_VALID';
var FLG_PPM_AMT = 'FLG_PPM_AMT';
var IS_ACK_GEN = 'IS_ACK_GEN';
var SWIFT_UTILITY_FLAG = 'SWIFT_UTILITY_FLAG';
var MANUALLY_TICKED_MAIL = 'MANUALLY_TICKED_MAIL';
var DEC_CODE = 'DEC_CODE';
var DECISION = 'DECISION';
var PT_CUSTOMER_IC = 'PT_CUSTOMER_IC';

var GRNT_DISABLE_PT_FIELDS = 'SOURCE_CHANNEL,TRN_THIRD_PARTY,GRNTEE_APP_CNTRCT_REF_NO,GRNTEE_BEN_CNTRCT_REF_NO,INSTRCTN_TO_BANK,PRO_TRADE_REF_NO,PRO_TRADE_SETTLEMENT_INST';
var GRNT_DISABLE_AM_PT_FIELDS = 'SOURCE_CHANNEL,GRNTEE_APP_CNTRCT_REF_NO,GRNTEE_BEN_CNTRCT_REF_NO,PRO_TRADE_REF_NO,PRO_TRADE_SETTLEMENT_INST';
var ILC_NI_DISABLE_PT_FIELDS = 'LC_UNDER,LC_LTST_SHIPMNT_DATE,LC_FROM_PLACE,LC_TO_PLACE,LC_PORT_OF_LOADING,LC_PORT_OF_DISCHRG,LC_GOODS_DESC,LC_ABOVE,SOURCE_CHANNEL,LC_TOLERANCE,EXP_DATE,TRN_THIRD_PARTY,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE';  //ATP-383 REYAZ 15-04-2024;
var ELCB_BL_DISABLED_FIELDS = 'BILL_NAME_OF_VESSEL,BILL_PORT_OF_LOADING,BILL_PORT_OF_DISCHARGE,BILL_FORWARD_EXCHG_CONTRACT_NO,BILL_DEAL_NUMBER,BILL_CURRENCY,BILL_DEAL_AMOUNT,SOURCE_CHANNEL';
//Checkboxes
var CHKBX_SEND_MAIL = 'CHKBX_SEND_MAIL';
var FLG_ACK_GEN = 'FLG_ACK_GEN';

//listview
var LVW_Decision_Sumary = 'LVW_Decision_Sumary';

//Buttons
var BUTTON_CUSTOMER_ACK = 'btnPrint';
var BUTTON_FETCH = 'btnCidFetch';
var BUTTON_SUBMIT = 'btnSubmit';
var BUTTON_DISCARD = 'btnDiscard';
var BUTTON_NEXT = 'btnNext';
var BUTTON_PREVIOUS = 'btnPrevious';
var BUTTON_SAVE = 'btnSave';

//Initiator Workstep Sections Control Names
var FRM_SWIFT = 'FRM_SWIFT';
var SEC_INIT_DETAILS = 'SEC_INIT_DETAILS';
var SEC_REQ_DETAILS = 'SEC_REQ_DETAILS';
var SEC_CUST_DETAILS = 'SEC_CUST_DETAILS';
var SUBSEC_CUST_DETAILS = 'SUBSEC_CUST_DETAILS';
var FRAME_Decision_Hist = 'FRAME_Decision_Hist';

//Workstep-RM: customer details tab controls
var ADDRESS_LINE_1 ='ADDRESS_LINE_1';
var ADDRESS_LINE_2 ='ADDRESS_LINE_2';
var CUSTOMER_CATEGORY ='CUSTOMER_CATEGORY';
var EMIRATES = 'EMIRATES';
var FCR_CUST_EMAIL_ID ='FCR_CUST_EMAIL_ID';
var IS_CUSTOMER_VIP = 'IS_CUSTOMER_VIP';
var MOBILE_NUMBER ='MOBILE_NUMBER';
var PO_BOX = 'PO_BOX';
var PROFIT_CENTER_CODE = 'PROFIT_CENTER_CODE';
var RM_CODE = 'RM_CODE';
var RM_EMAIL ='RM_EMAIL';
var RM_MOBILE_NUMBER = 'RM_MOBILE_NUMBER';
var RM_NAME ='RM_NAME';
var TRADE_CUST_EMAIL_ID ='TRADE_CUST_EMAIL_ID';

//List of Controls
var EMPTY_FIELD = [CUSTOMER_NAME,ADDRESS_LINE_1,ADDRESS_LINE_2,CUSTOMER_CATEGORY,EMIRATES,FCR_CUST_EMAIL_ID,IS_CUSTOMER_VIP,
                   MOBILE_NUMBER,PO_BOX,PROFIT_CENTER_CODE,RM_EMAIL,RM_MOBILE_NUMBER,RM_NAME,TRADE_CUST_EMAIL_ID,
                   CUSTOMER_ID,TRANSACTION_REFERENCE,TRN_STATUS,TRNS_BAL,RM_CODE];
var EMPTY_FIELD_INITIATOR = [CUSTOMER_NAME,CUSTOMER_ID,TRANSACTION_REFERENCE,TRN_STATUS,TRNS_BAL];
var EMPTY_AMOUNT = [TRANSACTION_AMOUNT];

//PP Maker frames
var GTEE_FRAME  = 'GTEE_FRAME';
var IF_FRAME = 'IF_FRAME';
var IFS_BUYER = 'IFS_BUYER';
var LC_FRAME = 'LC_FRAME';
var GRNT_FRM_NEW = 'GRNT_FRM_NEW';
var FRM_GRTEE_LC_COMMON = 'FRM_GRTEE_LC_COMMON';
var IF_FRAME = 'IF_FRAME';
var IF_FRAME1 = 'IF_FRAME1';
var BILL_FRAME = 'BILL_FRAME';
var Charges_Frame= 'Charges_Frame'; 
var DEAL_DETAILS_FRAME = 'DEAL_DETAILS_FRAME';
var IELC_MKR_INPUT_FRM = 'IELC_MKR_INPUT_FRM';

var GRNT_FRAMES_HIDE = 'IF_FRAME,IFS_BUYER,LC_FRAME,DEAL_DETAILS_FRAME,Charges_Frame,IF_FRAME1,BILL_FRAME';
var GRNT_FRAMES_GRNT_SD_GAA = 'IF_FRAME,IFS_BUYER,LC_FRAME,DEAL_DETAILS_FRAME,Charges_Frame,IF_FRAME1,BILL_FRAME';
var GRNT_FRAMES_SHOW= 'GTEE_FRAME,GRNT_FRM_NEW,FRM_GRTEE_LC_COMMON';
var IFS_IFP_FRAMES_HIDE = 'GTEE_FRAME,BILL_FRAME';
var IFS_IFP_FRAMES_SHOW = 'IF_FRAME,IF_FRAME1';
var IFS_IFP_LD_FRAMES_SHOW = 'IFS_BUYER';
var ELC_ILC_FRAMES_SHOW = 'GTEE_FRAME,LC_FRAME#,RM_GRTEE_LC_COMMON,IELC_MKR_INPUT_FRM';
var ELC_ILC_FRAMES_HIDE = 'IF_FRAME,IFS_BUYER'; 
var ILCB_ELCB_IC_EC_DBA_FRAMES_SHOW = 'IF_FRAME,BILL_FRAME';
var ILCB_BL_FRAMES_SHOW = 'Charges_Frame';
var TL_FRAMES_SHOW = 'IF_FRAME,IF_FRAME1';

var PPM_GRNT_NI_PT_SHOW = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,SWIFT_PUR_OF_MSG,FCUBS_PUR_OF_MSG,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,LANG,EXPIRY_TYPE,CNTR_GTEE_EXP_DATE,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE';
var PPM_GRNT_NI_PT_DISABLE = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,LANG,EXPIRY_TYPE,CNTR_GTEE_EXP_DATE,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE';  //ATP-383 REYAZ 15-04-2024
var PPM_GRNT_NI_PT_ENABLE = 'FCUBS_PUR_OF_MSG';

var PPM_GRNT_NI_BAU_SHOW = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,SWIFT_PUR_OF_MSG,FCUBS_PUR_OF_MSG';
var PPM_GRNT_NI_BAU_ENABLE = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,FCUBS_PUR_OF_MSG';

var PPM_ELC_SLCA_PT_SHOW = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,FCUBS_PUR_OF_MSG,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,LANG,EXPIRY_TYPE';
var PPM_ELC_SLCA_PT_DISABLE = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,LANG,EXPIRY_TYPE';
var PPM_ELC_SLCA_PT_ENABLE = 'FCUBS_PUR_OF_MSG';
var PPM_ELC_SLCA_PT_HIDE = 'GRNTEE_CNTR_EXP_DATE';//mansi

var PPM_ELC_SLCA_BAU_SHOW = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,FCUBS_PUR_OF_MSG';
var PPM_ELC_SLCA_BAU_ENABLE = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,FCUBS_PUR_OF_MSG';
var PPM_ELC_SLCA_BAU_HIDE = 'GRNTEE_CNTR_EXP_DATE';//mansi

var PPM_ELC_SLCA_SWIFT_SHOW = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,FCUBS_PUR_OF_MSG,PT_GTEE_FRAME,PT_FFT_Frame,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,EXPIRY_TYPE';
var PPM_ELC_SLCA_SWIFT_DISABLE = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,EXPIRY_TYPE';
var PPM_ELC_SLCA_SWIFT_ENABLE = 'FCUBS_PUR_OF_MSG';
var PPM_ELC_SLCA_SWIFT_HIDE = 'GUARANTEE_FORMAT,EFFECTIVE_DATE,GRNTEE_CNTR_EXP_DATE';

//GRNT NI
//HIDE ADDN_AMT_INFO FOR SWIFT CHANGES 24-10-2023
var PPM_GRNT_NI_SWIFT_SHOW = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,SWIFT_PUR_OF_MSG,FCUBS_PUR_OF_MSG,PT_GTEE_FRAME,PT_FFT_Frame,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,EXPIRY_TYPE';
var PPM_GRNT_NI_SWIFT_DISABLE = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,EXPIRY_TYPE';
var PPM_GRNT_NI_SWIFT_ENABLE = 'FCUBS_PUR_OF_MSG';
var PPM_GRNT_NI_SWIFT_HIDE = 'GUARANTEE_FORMAT,EFFECTIVE_DATE';

var PPM_GRNT_AM_PT_SHOW='PT_AMENDMENT_FRAME';
var PPM_GRNT_AM_BAU_SHOW='PT_AMENDMENT_FRAME';
var PPM_GRNT_AM_SWIFT_SHOW='PT_AMENDMENT_FRAME';

var PPM_GRNT_GAA_PT_SHOW='PT_AMENDMENT_FRAME';
var PPM_GRNT_GAA_BAU_SHOW='PT_AMENDMENT_FRAME';
var PPM_GRNT_GAA_SWIFT_SHOW='PT_AMENDMENT_FRAME';

//JIRA ATP -198 ,JIRA ATP -199 , ATP - 200  ADDED BY REYAZ
var PPM_SCF_PD_BAU_HIDE = 'DELIVERY_BRANCH,INF_TENOR_DAYS,INF_TENOR_BASE,INF_BASE_DOC_DATE,INF_ACTUAL_TENOR_BASE';
var PPM_SCF_PD_BAU_SHOW ='PROCESSING_SYSTEM,UTC_REQUIRED_BRMS,UTC_CONVERTED_AMOUNT,STANDALONE_LOAN,BTN_FETCH_TSLM_CID_DETAILS,UTC_REQUIRED,UTC_JSTIFICATION_REQUIRED,TSLM_COMPANY_TYPE,PAST_DUE_LIABILITY';
var PPM_SCF_PD_BAU_FRAMES_HIDE = 'IF_FRAME1,GTEE_FRAME,IFS_BUYER,DEAL_DETAILS_FRAME,Charges_Frame,BILL_FRAME,FRM_GRTEE_LC_COMMON,LC_FRAME,FRM_COUNTER_PARTY,SEC_INVOICE_NUMBERS_FOR_STANDALONE_LOAN';
var PPM_SCF_PD_BAU_ENABLE ='BTN_FETCH_TSLM_CID_DETAILS';
var PPM_SCF_PD_BAU_DISABLE ='INF_AMEND_TYPE,STANDALONE_LOAN,PAST_DUE_LIABILITY';
var PPM_SCF_PD_TSLM_DISABLE ='SOURCE_CHANNEL,RELATIONSHIP_TYPE,BRN_CODE,PROCESSING_SYSTEM,PRODUCT_TYPE,INF_LOAN_CURR,LOAN_EFFECTIVE_DATE,INF_MATURITY_DATE,BILL_CUST_HLDING_ACC_US,INF_CHARGE_ACC_NUM,INF_SETTLEMENT_ACC_NUM,TSLM_COMPANY_TYPE,UTC_REQUIRED,BTN_INVOICE_BROWSE,QVAR_utc_details,btnINFFetchAcc'; //Added by Shivanshu ATP - 409
var PPM_SCF_PD_BAU_FRAMES_SHOW = 'SEC_TSLM_COUNTER_PARTY_DETAILS';
var PPM_SCF_PD_TSLM_FRONTEND_SHOW ='ASSET_ID,CUSTOMER_REFERENCE';
var PPM_SCF_PD_TSLM_FRONTEND_HIDE = 'DELIVERY_BRANCH,INF_TENOR_DAYS,INF_TENOR_BASE,INF_BASE_DOC_DATE,INF_ACTUAL_TENOR_BASE,FINANCE_PERCENTAGE,FOR_ACCOUNT_OF_FLAG,SUBCOMPANY_NAME,GOOD_SERVICE_UTIL_DESCRIPTION,PT_GTEE_EXPIRY_DATE,SUPPORTING_DOCS_REQ_PER_CREDIT_APPROVAL';
var PPM_SCF_PD_TSLM_FRONTEND_FRAMES_HIDE = 'PT_FFT_Frame,PT_GTEE_FRAME,FRM_GRNT_NI_TERMS_COND';

var PM_SCF_PD_BAU_FRAMES_HIDE = 'IF_FRAME1,GTEE_FRAME,IFS_BUYER,DEAL_DETAILS_FRAME,Charges_Frame,BILL_FRAME,FRM_GRTEE_LC_COMMON,LC_FRAME,FRM_COUNTER_PARTY,SEC_INVOICE_NUMBERS_FOR_STANDALONE_LOAN';

var PM_SCF_PD_BAU_HIDE = 'DELIVERY_BRANCH,INF_TENOR_DAYS,INF_TENOR_BASE,INF_BASE_DOC_DATE,INF_ACTUAL_TENOR_BASE,INF_CREDIT_ACC_NUM,INF_CREDIT_ACC_TITLE,INF_CREDIT_ACC_CURR,REMITTANCE_CURR,REMITTANCE_AMT,IFS_LOAN_GRP,CUST_REF_NO,PT_CUST_EMAIL_ID,OTHER_AMENDMENT';

var PM_SCF_PD_BAU_DISABLE ='INF_AMEND_TYPE,STANDALONE_LOAN,PAST_DUE_LIABILITY,ROUTE_TO_PM'; //Added  ROUTE_TO_PM by Shivanshu ATP - 409
var PM_SCF_PD_TSLM_DISABLE ='BRN_CODE,ROUTE_TO_PM,LOAN_AMOUNT,UTC_REQUIRED,BTN_INVOICE_BROWSE,UTC_START_CHECK,QVAR_utc_details'; //Added by Shivanshu ATP - 409
var PM_SCF_PD_BAU_SHOW ='SEC_TSLM_CUST_SPECIAL_INST';


var PC_SCF_PD_BAU_HIDE = 'ASSET_ID,CUSTOMER_REFERENCE,PAY_CURRENCY,PAY_AMOUNT,LEGALIZATION_CHARGES_DETAIL,DELIVERY_BRANCH,INF_TENOR_DAYS,INF_TENOR_BASE,INF_BASE_DOC_DATE,INF_ACTUAL_TENOR_BASE,INF_CREDIT_ACC_NUM,INF_CREDIT_ACC_TITLE,INF_CREDIT_ACC_CURR,REMITTANCE_CURR,REMITTANCE_AMT,IFS_LOAN_GRP,CUST_REF_NO,PT_CUST_EMAIL_ID,OTHER_AMENDMENT,COMP_POSITIVE_MATCH,COMP_CHK_DONE,FINANCE_PERCENTAGE,FOR_ACCOUNT_OF_FLAG,SUBCOMPANY_NAME,GOOD_SERVICE_UTIL_DESCRIPTION,PT_GTEE_EXPIRY_DATE,SUPPORTING_DOCS_REQ_PER_CREDIT_APPROVAL';
var PC_SCF_PD_BAU_FRAMES_HIDE = 'IF_FRAME1,GTEE_FRAME,IFS_BUYER,DEAL_DETAILS_FRAME,Charges_Frame,BILL_FRAME,FRM_GRTEE_LC_COMMON,LC_FRAME,FRM_COUNTER_PARTY,SEC_INVOICE_NUMBERS_FOR_STANDALONE_LOAN';
var PC_SCF_PD_BAU_DISABLE ='INF_AMEND_TYPE,STANDALONE_LOAN,PAST_DUE_LIABILITY';
var PC_SCF_PD_TSLM_FRONTEND_SHOW ='ASSET_ID,CUSTOMER_REFERENCE';
var PC_SCF_PD_TSLM_FRONTEND_HIDE = 'DELIVERY_BRANCH,INF_TENOR_DAYS,INF_TENOR_BASE,INF_BASE_DOC_DATE,INF_ACTUAL_TENOR_BASE,FINANCE_PERCENTAGE,FOR_ACCOUNT_OF_FLAG,SUBCOMPANY_NAME,GOOD_SERVICE_UTIL_DESCRIPTION,PT_GTEE_EXPIRY_DATE,SUPPORTING_DOCS_REQ_PER_CREDIT_APPROVAL';
var PC_SCF_PD_TSLM_FRONTEND_FRAMES_HIDE = 'PT_FFT_Frame,PT_GTEE_FRAME,FRM_GRNT_NI_TERMS_COND';

//ATP-361 DATE -08-01-2024  REYAZ
var PPM_STL_TSLM_FRONTEND_DISABLE ='INF_CHARGE_ACC_NUM,INF_SETTLEMENT_ACC_NUM';



var TL_FRAMES_HIDE = 'GTEE_FRAME,BILL_FRAME,IFS_BUYER,LC_FRAME,FRM_GRTEE_LC_COMMON,DEAL_DETAILS_FRAME,Charges_Frame';
var IFS_FRAMES_HIDE = 'DEAL_DETAILS_FRAME,GTEE_FRAME,LC_FRAME,FRM_GRTEE_LC_COMMON,Charges_Frame,BILL_FRAME,IFS_BUYER';
var IC_ILCB_ELCB_DBA_FRAMES_HIDE = 'GTEE_FRAME,IFS_BUYER,IF_FRAME1,LC_FRAME,Charges_Frame';
var ILCB_BL_HIDE_FRAMES = 'GTEE_FRAME,IFS_BUYER,IF_FRAME1,LC_FRAME';
var ILC_ELC_FRAMES_HIDE = 'DEAL_DETAILS_FRAME,IF_FRAME,IFS_BUYER,IF_FRAME1,Charges_Frame,BILL_FRAME';

var LOCK_PPM_FRAMES = "PT_AMENDMENT_FRAME,INPUT_DETAILS_FRAME,PT_PROTRADE,PT_Document_Detail,PT_CUSTOMER_INS,REF_FRAME,FRM_VERIFY_DETAIL,FRM_SWIFT,GTEE_FRAME,LC_FRAME,IF_FRAME,IF_FRAME1,BILL_FRAME,FRM_GRTEE_LC_COMMON,DEAL_DETAILS_FRAME,IFS_BUYER,Charges_Frame,Customer_Details,FRM_COUNTER_PARTY,FRM_VALIDATION,FRM_REFERAL_DETAILS,FRM_VALIDATION_DOC,FRM_REFERAL_DETAILS_DOC,FRM_VALIDATION_TXT,FRM_REFERAL_DETAILS_TXT,FRM_VALIDATION_LIMIT,FRM_REFERAL_DETAILS_LIMIT,FRM_DUPE,Decision_Frame,PT_COMMON,PT_GTEE_FRAME,PT_COMMON,PT_FFT_Frame,PT_ILC_FRAME";
var GRNT_CC_ER_CL_EPC_DISABLE='IS_ACC_VALID,TRN_THIRD_PARTY,ACCOUNT_NUMBER,GRNT_CHRG_ACC_TITLE,GRNT_CHRG_ACC_CRNCY'; //RR

var PPM_SBLC_NI_PT_SHOW = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,SWIFT_PUR_OF_MSG,FCUBS_PUR_OF_MSG,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,LANG,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,TRN_TENOR';//EXPIRY_TYPE,CNTR_GTEE_EXP_DATE;
var PPM_SBLC_NI_PT_DISABLE = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,LANG,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE';  //ATP-383 REYAZ 15-04-2024
var PPM_GRNT_NI_PT_ENABLE = 'FCUBS_PUR_OF_MSG';';//,EXPIRY_TYPE,CNTR_GTEE_EXP_DATE';
var PPM_SBLC_NI_PT_ENABLE = 'FCUBS_PUR_OF_MSG,TRN_TENOR';
var PPM_SBLC_NI_PT_HIDE = 'GRNTEE_CNTR_EXP_DATE,PT_GTEE_EXPIRY_DATE,EXPIRY_TYPE,CNTR_GTEE_EXP_DATE';

var PPM_SBLC_NI_BAU_SHOW = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,SWIFT_PUR_OF_MSG,FCUBS_PUR_OF_MSG';
var PPM_SBLC_NI_BAU_ENABLE = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,FCUBS_PUR_OF_MSG';
var PPM_SBLC_NI_BAU_HIDE = 'GRNTEE_CNTR_EXP_DATE,PT_GTEE_EXPIRY_DATE,EXPIRY_TYPE,CNTR_GTEE_EXP_DATE';

var PPM_SBLC_NI_SWIFT_SHOW = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,SWIFT_PUR_OF_MSG,FCUBS_PUR_OF_MSG,PT_GTEE_FRAME,PT_FFT_Frame,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,EXPIRY_TYPE';
var PPM_SBLC_NI_SWIFT_DISABLE = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,EXPIRY_TYPE';
var PPM_SBLC_NI_SWIFT_ENABLE = 'FCUBS_PUR_OF_MSG';
var PPM_SBLC_NI_SWIFT_HIDE = 'GUARANTEE_FORMAT,EFFECTIVE_DATE,GRNTEE_CNTR_EXP_DATE,PT_GTEE_EXPIRY_DATE,EXPIRY_TYPE,CNTR_GTEE_EXP_DATE';

//GA TYPE CHANGES
//HIDE  AND SHOW SUPPL_INFO_AMT,GOVT_LAW_JURSD FOR SWIFT CHANGES DATE 23-10-2023
var PPM_GRNT_GA_SWIFT_SHOW = 'EXPIRY_COND,PUR_OF_GTEE,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,FCUBS_PUR_OF_MSG,ADDN_AMT_INFO,SUPPL_INFO_AMT,GOVT_LAW_JURSD';
var PPM_GRNT_GA_SWIFT_DISABLE = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,SUPPL_INFO_AMT,GOVT_LAW_JURSD';
var PPM_GRNT_GA_SWIFT_ENABLE ='FCUBS_PUR_OF_MSG';

var PPM_GRNT_GA_BAU_SHOW = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,FCUBS_PUR_OF_MSG';
var PPM_GRNT_GA_BAU_ENABLE = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,FCUBS_PUR_OF_MSG';

//HIDE  AND SHOW SUPPL_INFO_AMT,GOVT_LAW_JURSD FOR SWIFT CHANGES DATE 23-10-2023
var PM_GRNT_GA_SWIFT_SHOW = 'EXPIRY_COND,PUR_OF_GTEE,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,FCUBS_PUR_OF_MSG,ADDN_AMT_INFO,SUPPL_INFO_AMT,GOVT_LAW_JURSD';
var PM_GRNT_GA_BAU_SHOW = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,FCUBS_PUR_OF_MSG';
var PM_GRNT_GA_BAU_ENABLE = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,FCUBS_PUR_OF_MSG';
var PM_GRNT_GA_SWIFT_DISABLE = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,SUPPL_INFO_AMT,GOVT_LAW_JURSD';

//HIDE  AND SHOW SUPPL_INFO_AMT,GOVT_LAW_JURSD FOR SWIFT CHANGES DATE 23-10-2023
var PC_GRNT_GA_BAU_ENABLE = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,FCUBS_PUR_OF_MSG';
var PC_GRNT_GA_SWIFT_DISABLE = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,ADDN_AMT_INFO,SUPPL_INFO_AMT,GOVT_LAW_JURSD';
var PC_GRNT_GA_SWIFT_SHOW = 'EXPIRY_COND,PUR_OF_GTEE,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,FCUBS_PUR_OF_MSG,SUPPL_INFO_AMT,GOVT_LAW_JURSD';
var PC_GRNT_GA_BAU_SHOW = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,FCUBS_PUR_OF_MSG';

//Workstep Logistics Controls to hide
var HIDE_AT_LOGISTICS = 'FRM_SWIFT,PROCESS_TYPE,btnDiscard,btnPrint,btnCidFetch,CHKBX_SEND_MAIL,FLG_ACK_GEN';

//PM Workstep Controls
var TRSD_OTHER_ENTITY_NAME_ID = 'TRSD_OTHER_ENTITY_NAME_ID';
var ELCB_AM_FIELDS = 'BILL_STAGE,PT_CUST_EMAIL_ID';
var EC_AM_FIELDS = 'otherInstructionLabel,OTHER_INSTRUCTION1,OTHER_INSTRUCTION2,OTHER_INSTRUCTION3';
var PM_DECISION_HISTORY ='PM_DECISION_HISTORY';
var TRN_TENOR = 'TRN_TENOR';
var EXP_DATE = 'EXP_DATE';
var AMEND_TYPE = 'AMEND_TYPE';
var Q_AMENDMENT_DATA_USER_EXPIRY_TYPE ='Q_Amendment_Data_USER_EXPIRY_TYPE';	//amendment frame
var Q_AMENDMENT_DATA_PT_EXPIRY_TYPE ='Q_Amendment_Data_PT_EXPIRY_TYPE';	//mansi
var Q_AMENDMENT_DATA_USER_EXPIRY_COND='Q_Amendment_Data_USER_EXPIRY_COND';//mansi
var Q_AMENDMENT_DATA_FIN_EXPIRY_COND='Q_Amendment_Data_FIN_EXPIRY_COND';//mansi
var Q_AMENDMENT_DATA_FIN_EXPIRY_DATE='Q_Amendment_Data_FIN_EXPIRY_DATE';//mansi
var Q_AMENDMENT_DATA_USER_EXPIRY_DATE='Q_Amendment_Data_USER_EXPIRY_DATE';//mansi
var Q_AMENDMENT_DATA_USER_CNTR_GTEE_EXP_DATE='Q_Amendment_Data_USER_CNTR_GTEE_EXP_DATE';//mansi
var COMP_CHK_OPTION_YES = 'COMP_CHK_OPTION_YES';
var ACCOUNT_NUMBER = 'ACCOUNT_NUMBER';
var CREATE_AMEND_CNTRCT_FCUBS = 'CREATE_AMEND_CNTRCT_FCUBS';
var OPERATION_CODE = 'OPERATION_CODE';
var LLI_CHK_YES = 'LLI_CHK_YES';
var LLI_CHK_OK = 'LLI_CHK_OK';
var COMP_CHK_DONE = 'COMP_CHK_DONE';
var COMP_POSITIVE_MATCH = 'COMP_POSITIVE_MATCH';
var COMP_REF = 'COMP_REF';
var COMP_EXP_REMARKS = 'COMP_EXP_REMARKS';
var DUP_CHK_CONFIRMATION = 'DUP_CHK_CONFIRMATION';
var TR_REFER_TREASURY = 'TR_REFER_TREASURY';
var COMP_IMB_CHK = 'COMP_IMB_CHK';
var TR_BUY_CUR = 'TR_BUY_CUR';
var TR_LOAN_AMT = 'TR_LOAN_AMT';
var TR_SELL_CUR = 'TR_SELL_CUR';
var TR_SELL_AMT = 'TR_SELL_AMT';
var TR_RATE_REQ = 'TR_RATE_REQ';
var TR_EXCHANGE_RATE = 'TR_EXCHANGE_RATE';
var UI_EXCHANGE_RATE = 'UI_EXCHANGE_RATE';
var NEW_TRN_AMT = 'NEW_TRN_AMT';
var EXP_DATE = 'EXP_DATE';
var NEW_EXP_DATE = 'NEW_EXP_DATE';
var FIELD_LC_UNDER ='LC_UNDER';
var FIELD_LC_ABOVE = 'LC_ABOVE';
var LC_GOODS_DESC='LC_GOODS_DESC';
var LISTVIEW_TRSD_TABLE='TRSD_TABLE';
var BTN_START_TRSD='BTN_START_TRSD';
var TRSD_WI_NAME='TRSD_WI_NAME';
var BTN_IFRAME_CLOSE='BTN_IFRAME_CLOSE';
var LISTVIEW_TRSD_TABLE_OPTIONAL='TRSD_TABLE_OPTIONAL';
var ENTITY_ID='ENTITY_ID' ;
var ENTITY_NAME_ID='ENTITY_NAME_ID' ; 
var TRSD_SCREENING_TYPE_ID='TRSD_SCREENING_TYPE_ID';  
var TRSD_SCREENING_RESULT_ID='TRSD_SCREENING_RESULT_ID' ; 
var CASE_ID='CASE_ID' ;
var CASE_NUMBER_ID='CASE_NUMBER_ID' ;
var PENDING_IN_TRSD_GROUP_ID ='PENDING_IN_TRSD_GROUP_ID';
var CASE_CLOSED_BY_ID='CASE_CLOSED_BY_ID' ;
var SCREENING_DATE_ID='SCREENING_DATE_ID' ;
var ASSESSMENT_DATE_ID='ASSESSMENT_DATE_ID' ;
var CHANNEL_REFERENCE_NO_ID='CHANNEL_REFERENCE_NO_ID';
var REMARKS_ID='REMARKS_ID';

var PM_GRNT_NI_PT_SHOW = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,SWIFT_PUR_OF_MSG,FCUBS_PUR_OF_MSG,LANG,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,EXPIRY_TYPE';
var PM_GRNT_NI_PT_DISABLE = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,LANG,EXPIRY_TYPE,SWIFT_PUR_OF_MSG';
var PM_GRNT_NI_PT_ENABLE = 'FCUBS_PUR_OF_MSG,SWIFT_PUR_OF_MSG';

var PM_GRNT_NI_BAU_SHOW = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,SWIFT_PUR_OF_MSG,FCUBS_PUR_OF_MSG';
var PM_GRNT_NI_BAU_ENABLE = 'ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,FCUBS_PUR_OF_MSG,SWIFT_PUR_OF_MSG';

// GRNT NI
//HIDE ADDN_AMT_INFO FOR SWIFT CHANGES 24-10-2023
var PM_GRNT_NI_SWIFT_SHOW = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,SWIFT_PUR_OF_MSG,FCUBS_PUR_OF_MSG,PT_GTEE_FRAME,PT_FFT_Frame,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,EXPIRY_TYPE';
var PM_GRNT_NI_SWIFT_DISABLE = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,EXPIRY_TYPE';
var PM_GRNT_NI_SWIFT_ENABLE = 'FCUBS_PUR_OF_MSG,SWIFT_PUR_OF_MSG';
var PM_GRNT_NI_SWIFT_HIDE = 'GUARANTEE_FORMAT,EFFECTIVE_DATE';

var PM_GRNT_AM_PT_SHOW='PT_AMENDMENT_FRAME';
var PM_GRNT_AM_BAU_SHOW='PT_AMENDMENT_FRAME';
var PM_GRNT_AM_SWIFT_SHOW='PT_AMENDMENT_FRAME';

var PM_GRNT_GAA_PT_SHOW='PT_AMENDMENT_FRAME';
var PM_GRNT_GAA_BAU_SHOW='PT_AMENDMENT_FRAME';
var PM_GRNT_GAA_SWIFT_SHOW='PT_AMENDMENT_FRAME';

//PC constants
var FRM_LLI_FIELDS = 'TXT_LLI_VESSELNAME,LLI_SHIPMENT_DATE,BTN_LLI_FETCH,Btn_Gen_PDF,Btn_Add_LLI,Btn_Del_LLI';
var DISABLE_LLI='FIELD_SHIPMENT_DATE,FIELD_TXT_VESSELNAME,FIELD_TXT_VESSELFLAG,FIELD_TXT_VESSELID,FIELD_TXT_VESSELIMO';
var DISABLE_PM_TXT="NEW_TRN_AMT,ROUTE_TO_PPM,EXP_DATE,NEW_EXP_DATE,TXT_SIGACC_ACC_NO,LC_UNDER,LC_ABOVE,GRNTEE_APP_CNTRCT_REF_NO,GRNTEE_BEN_CNTRCT_REF_NO,PRO_TRADE_REF_NO,INSTRCTN_TO_BANK,GRNTEE_EXP_DATE,PRO_TRADE_SETTLEMENT_INST";
var DISABLE_PC_TXT="LC_FROM_PLACE,LC_PORT_OF_DISCHRG,LC_TO_PLACE,LC_PORT_OF_LOADING,LC_GOODS_DESC,GRNTEE_CNTR_EXP_DATE,LC_LTST_SHIPMNT_DATE";
var HIDE_PC_TXT="GRNTEE_CNTR_EXP_DATE";
var DISABLE_PC_TXT_GDDESC="LC_FROM_PLACE,LC_PORT_OF_DISCHRG,LC_TO_PLACE,LC_PORT_OF_LOADING,GRNTEE_CNTR_EXP_DATE,LC_LTST_SHIPMNT_DATE";
var DISABLE_PM_LOV="PRODUCT_TYPE,ACCOUNT_NUMBER,AMEND_TYPE,IS_ACC_VALID,TRN_THIRD_PARTY,TRN_TENOR,LC_TOLERANCE";
var DISABLE_PM_IF_CHECKBOX="BILL_FORWARD_EXCHG_CONTRACT_NO";
var DISABLE_PC_PD_DETAILS="TFO_PD_CUSTOMER_ID,TFO_PARTY_TYPE,TFO_PARTY_DESC,TFO_PD_ADDRESS1,TFO_PD_ADDRESS2,TFO_PD_ADDRESS3,TFO_PD_ADDRESS,TFO_PD_COUNTRY,TFO_MEDIA_TYPE,TFO_PD_CUSTOMER_NAME,TFO_PD_PARTY_ID,TFO_PD_ADDRESS4,TFO_PARTY_TYPE_PM";
var DISABLE_PC_CONTRACT_LIMIT="CL_SERIALNUMBER,CL_CUSTOMER_NO,CL_PER_CONTRIBUTION,CL_COMBO_OPERATION,CL_COMBO_TYPE,CL_COMBO_AMOUNTTAG,CL_COMBO_PARTYTYPE,CL_LINKAGEREFNO,CONTRACT_LIMIT_ADD_BTN,CONTRACT_LIMIT_MODIFY_BTN,CONTRACT_LIMIT_DELETE_BTN";
var ELC_AOP ="ELC_REIMB_CL_PER_PAY,ELC_CON_FCC_ICIEC_COV,ELC_ENS_COR_LIM_LINES,ELC_SWFT_IB_CHRG_COFM,ELC_CHRG_COL_PER_ICG_ICIEC,ELC_UPDT_COMM_GL_TRACK,ELC_SILENT_CONF,ELC_ENS_LMT_INT_OIL_LC,ELC_SWFT_IB_CHRG_COFM";
var ELC_AOP_DISABLED = 'ELC_COL_CHRG_CUST,ELC_PREP_ASS_LETTER,ELC_SWFT_IB_AOP_DTLS'; 
var HIDE_PC_FIELDS='BRN_CODE'
var DISABLE_SWIFT_FIELDS="SWIFT_MESSAGE_TYPE,SWIFT_PROCESSING_STATUS,SWIFT_FIELD_21,SWIFT_SENDER_BIC,SWIFT_FETCH_MODULE,SWIFT_DEC_ON_SWIFT_MESSAGE,REASON_FOR_FILING"; 
var DISABLE_CPD_STLMNT="CPD_NAME,CPD_COUNTRY";
var DISABLE_PM_IF_TXT="REMITTANCE_AMT,INF_NEW_MATURITY_DATE,INF_TENOR_DAYS,INF_BASE_DOC_DATE,INF_MATURITY_DATE,INF_ACTUAL_TENOR_BASE,INF_CHARGE_ACC_TITLE,INF_SETTLEMENT_ACC_TITLE,INF_CREDIT_ACC_TITLE,INF_CHARGE_ACC_CURR,INF_SETTLEMENT_ACC_CURR,INF_CREDIT_ACC_CURR,BC_DATE_OF_CALL,BC_REMAKS_NOT_DONE,BC_CALL_INFO,BC_NAME_OF_CALLER,BC_CONTACT_PERSON,BC_INVOICE_AMT,BC_RSN_OF_CALL,BC_BUYER_NAME,BC_TIME_OF_CALL,BC_BUYER_CONTACT_NUM,BC_INVOICE_NUMBER,PRO_TRADE_REF_NO,INSTRCTN_TO_BANK,PRO_TRADE_SETTLEMENT_INST,BILL_NAME_OF_VESSEL,BILL_PORT_OF_LOADING,BILL_PORT_OF_DISCHARGE,BILL_DEAL_NUMBER,BILL_DEAL_AMOUNT";
var DISABLE_PM_IF_LOV="REMITTANCE_CURR,PRODUCT_TYPE,INF_LOAN_CURR,INF_AMEND_TYPE,INF_TENOR_BASE,INF_CHARGE_ACC_NUM,INF_SETTLEMENT_ACC_NUM,INF_CREDIT_ACC_NUM,BC_CALL_DONE,BC_INVOICE_CURR,BILL_CURRENCY";
var DISABLE_TR_TAB_COMBOS="INF_TR_BUY_CURR,INF_TR_SELL_CURR";
var DISABLE_TR_TAB_FIELDS="TR_SELL_CUR,TR_EXCEPTIONS,TR_SELL_AMT,TR_REFER_TREASURY,TR_TREASURY_DEAL_NUM,TR_REFER,UI_EXCHANGE_RATE,TR_FRAME,TR_LOAN_AMT,TR_CID,TR_CUST_NAME,TR_BUY_CUR,TR_LN_AMNT,TR_SELL_AMNT,TR_EXCHANGE_RATE,TR_EXC_RATE,TR_UI_XCHNG,BTN_TR_FETCHRATE,TR_RATE_REQ,TR_TRS_NUM,TR_REF_EXC,TR_REF_YES,TR_REF_NO";
var COMPLIANCE_FIELDS= "COMP_CHK_DONE,LLI_CHK_OK,COMP_IMB_CHK,COMP_REF,COMP_POSITIVE_MATCH,COMPLIANCE_CHK_FRM,LLI_CHK_OK,COMP_REF,COMP_EXP_REMARKS";
var DISABLE_CHARGES="TFO_Q_Charges_Frame.legalCurrency,TFO_Q_Charges_Frame.penaltyCurrency,"
	+ "TFO_Q_Charges_Frame.overdrawnCurrency,TFO_Q_Charges_Frame.otherCurrency,TFO_Q_Charges_Frame.legalChargesBorneBy,"
	+ "TFO_Q_Charges_Frame.penaltyChargesBorneBy,TFO_Q_Charges_Frame.overdrawnChargesBorneBy,"
	+ "TFO_Q_Charges_Frame.otherChargesBorneBy,TFO_Q_Charges_Frame.legalAmount,TFO_Q_Charges_Frame.penaltyAmount,"
	+ "TFO_Q_Charges_Frame.overdrawnAmount,TFO_Q_Charges_Frame.otherAmount,TFO_Q_Charges_Frame.remarks";

var HIDE_FD= "REJ_RESN_PPM,CREATE_AMEND_CNTRCT_FCUBS,FCUBSConNo,CREATE_AMEND_STATUS_FCUBS,LIMIT_PARTY_TYPE,REF_ICG_RM,OPERATION_CODE,BILL_PRODUCT_CODE";
var FCUBS_CON_NO = "FCUBSConNo";
var FRAME_HIDE_PC = "FRM_LLI";
//event types 
var EVENT_TYPE = {
		LOAD: 'load',
		CLICK: 'click',
		CHANGE: 'change',
		LOSTFOCUS: 'blur',
		GOTFOCUS:'focus'
	};
 var SUBFORM_FINAL_DECISION_ID='subForm_Final_Decision_ID';
 var BUTTON_SF_START='SF_Start_Button';
 var BUTTON_SF_CLOSE='SF_Close_Button';
 var JSP_FRAME_CONTRACT='JSP_Frame_Contract';
 var PM_TAB_IFRAME_ID = 10;
 var PM_COMPLIANCE_SHEET_ID = 4;
 var PM_TRESARY_SHEET_ID = 5;
 var PM_PARTY_SHEET_ID = 6;
 var PM_TRSD_SHEET_ID = 7;
 var PM_FINAL_DEC_SHEET_ID = 9;
 var JSP_FRAME_LOGISTICS='Jsp_Frame_Logistics';  //Traydstream |reyaz|atp-518|17-09-2024|
 
 var PC_GRNT_NI_PT_SHOW = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,SWIFT_PUR_OF_MSG,FCUBS_PUR_OF_MSG,LANG,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,EXPIRY_TYPE';
 var PC_GRNT_NI_PT_DISABLE = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,LANG,EXPIRY_TYPE';
 var PC_GRNT_NI_PT_ENABLE = 'FCUBS_PUR_OF_MSG';

 var PC_GRNT_NI_BAU_SHOW = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,SWIFT_PUR_OF_MSG,FCUBS_PUR_OF_MSG';
 var PC_GRNT_NI_BAU_DISABLE = 'EXPIRY_COND,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,FCUBS_PUR_OF_MSG';
 var PC_GRNT_NI_BAU_ENABLE = 'FCUBS_PUR_OF_MSG';
 
 // GRNT NI
//HIDE ADDN_AMT_INFO FOR SWIFT CHANGES 24-10-2023
 var PC_GRNT_NI_SWIFT_SHOW = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,SWIFT_PUR_OF_MSG,FCUBS_PUR_OF_MSG,PT_GTEE_FRAME,PT_FFT_Frame,PT_Document_Detail,FRM_GRNT_NI_TERMS_COND,EXPIRY_TYPE';
 var PC_GRNT_NI_SWIFT_DISABLE = 'EXPIRY_COND,CNTR_GTEE_EXP_DATE,ADDN_AMT_INFO,PUR_OF_GTEE,PROJECT_NAME,TRANSFER_INDICATOR,TRANSFER_CONDITIONS,DELIVERY_INSTR,SWIFT_PUR_OF_MSG,EXPIRY_TYPE';
 var PC_GRNT_NI_SWIFT_ENABLE = 'FCUBS_PUR_OF_MSG';
 var PC_GRNT_NI_SWIFT_HIDE = 'GUARANTEE_FORMAT,EFFECTIVE_DATE';
 
 //var JSP_URL_CONTRACT="http://10.101.109.182:9081/TFO/CustomFolder/FCUBS_Integration_Calls.jsp?";
// Alert/Confirm Messages
var MESSAGE = {
		SUCCESS: { // success: true
			
		},
		ERROR: { // success: false
			READONLY_FORM: 'Your role is not defined in user access module. Please contact to administrator',
			ALERT_REQ_CAT: 'Please Select Request Category',
			ALERT_REQ_TYPE: 'Please Select Request Type',
			ALERT_REQ_BY: 'Please Select Request Resubmitted By',
			ALERT_SRC_CHNL: 'Please Select Source Channel',
			ALERT_CUST_ID: 'Please Enter CID',
			ALERT_CUST_NAME: 'Please Enter Customer Name',
			ALERT_BRNCH_CITY: 'Please select Issuing Center',
			ALERT_ASGN_CNTR: 'Please select Processing Center',
			ALERT_TRNS_CURR: 'Please Select Currency',
			ALERT_TRNS_AMT: 'Please Enter Transaction Amount',
			ALERT_REL_TYPE: 'Please Select Transaction Branch Code',
			ALERT_TRNS_REF: 'Please Enter Transaction Ref. Number',
			ALERT_TRNS_REF_LENGTH: 'Please enter correct Transaction Ref. Number of length 16',
			ALERT_ACK_CHK: 'Please ensure the data is correct, as it cannot be changed once you generate the acknowledgement?',
			ALERT_VALID_AMT: 'Please enter valid amount',
			ALERT_AMT_LNGTH: 'Please enter amount less than 22 length',
			ALERT_FETCH_MODULE: 'Please select Fetch Module',
			ALERT_JUST_FOR_FILLING: 'Please Select Just For Filling In Decision On SWIFT Message',
			ALERT_FIELD_21: 'Please enter Field 21.',
			ALERT_MSG_TYPE: 'Please select Message Type.',
			ALERT_SWIFT_DEC: 'Please select Decision on SWIFT Message.',
			ALERT_BIC: 'Please enter Sender BIC.',
			ALERT_FILING_REASON: 'Please enter Reason for filing',
			ALERT_ACK: 'Please click on Customer Ack button and generate acknowledgement.',
			ALERT_ROUTE_PPM: 'Please Select Route To.',
			CONFIRM_DISCARD_MSG: 'Do you really want to Discard the workitem?',
			ALERT_DEC_CODE: 'Please select Decision',
			ALERT_REMARKS: 'Please Enter Remarks',
			ALERT_DELIVERY_BRANCH: 'Please select delivery branch',
			ALERT_CREATE_AMEND: 'Please select Create Amend Contract in FCUBS',
			ALERT_TS_REFERENCE: 'Please Enter TS Reference'
		}
};
//PPM_Fields
//var SELECT = "";
var emptyStr = "0";

var DISABLE_PPM='FIELD_SIGACC_ACC_TOTAL_BAL,FIELD_SIGACC_ACC_CURR_BAL,FIELD_SIGACC_DOMCL_BRN_CODE,FIELD_SIGACC_ACC_CURRENCY,FIELD_SIGACC_ACC_MNDT,FIELD_TXT_SIGACC_ACC_NO,FIELD_GRNTEE_EXP_DATE,FIELD_PRO_TRADE_REF_NO,FIELD_INSTRCTN_TO_BANK,FIELD_PRO_TRADE_SETTLEMENT_INST,SWIFT_FETCH_MODULE,SWIFT_MESSAGE_TYPE,SWIFT_PROCESSING_STATUS,SWIFT_FIELD_21,DEC_ON_SWIFT_MESSAGE,SWIFT_SENDER_BIC';
var DISABLE_SG_PPM_FIELDS = 'TRN_TENOR,AMEND_TYPE,TRN_THIRD_PARTY,NEW_TRN_AMT,NEW_EXP_DATE,GRNTEE_APP_CNTRCT_REF_NO,GRNTEE_BEN_CNTRCT_REF_NO,GRNT_CHRG_ACC_TITLE,GRNT_CHRG_ACC_CRNCY,PRODUCT_TYPE';// Shipping_gtee_28, 27
var PPM_TRSD_SHEET_ID = 11;
//PM Fields Constants
var ACCOUNT_DETAILS = 'btnAccDtl';
var DISC_DETAILS = 'btnDiscDetails';
var ADD_COUNTER_PARTY = 'btnCPDAdd';
var VESSEL_DETAILS='Btn_Basic_Vessel_Details';
var OWNERSHIP_DETAILS='Btn_Ownrship_Details';
var MOVEMENT_DETAILS='Btn_Movmnt_Details';
var BUTTON_MODIFY_PARTY_DETAILS = 'btnModifyPartyDetails';

var PARTY_TYPE = 'TFO_PARTY_TYPE'; 
var PARTY_DESC = 'TFO_PARTY_DESC';
var PD_PARTY_ID = 'TFO_PD_PARTY_ID';
var PD_CUSTOMER_NAME = 'TFO_PD_CUSTOMER_NAME';
var PD_ADDRESS1 = 'TFO_PD_ADDRESS1';
var PD_ADDRESS2 = 'TFO_PD_ADDRESS2';
var PD_ADDRESS3 = 'TFO_PD_ADDRESS3';
var PD_ADDRESS4 = 'TFO_PD_ADDRESS4';
var PD_COUNTRY = 'TFO_PD_COUNTRY';
var MEDIA_TYPE = 'TFO_MEDIA_TYPE';
var PD_ADDRESS = 'TFO_PD_ADDRESS';
var LISTVIEW_PARTY = 'Qvar_Party_Details';
var LISTVIEW_CONTRACT_LIMIT = 'Qvar_Contract_Limits'; 
var TXT_VESSELNAME = 'TXT_VESSELNAME';
var SHIPMENT_DATE = 'SHIPMENT_DATE';
var CL_SERIALNUMBER = 'cl_serialNumber';
var CL_COMBO_OPERATION = 'cl_combo_operation';
var CL_COMBO_PARTYTYPE  = 'cl_combo_partyType';
var CL_CUSTOMER_NO = 'cl_customer_no';
var CL_COMBO_TYPE = 'cl_combo_type';
var CL_LINKAGEREFNO = 'cl_linkageRefNo';
var CL_PER_CONTRIBUTION = 'cl_per_contribution';
var CL_COMBO_AMOUNTTAG = 'cl_combo_amountTag';
var BUTTON_MODIFY_CONTRACT_DETAILS = 'btnModifyContractLimits';
var BUTTON_SAVE = 'btnSave';
var BUTTON_ADD_LLI = 'Btn_Add_LLI';
var BUTTON_FETCH_LLI = 'BTN_LLI_FETCH';
var BUTTON_GENERATE_LLI_PDF = 'Btn_Gen_PDF';
var LISTVIEW_LLI ='Qvar_LLI_Details';
var BUTTON_PARTY_DETAIL_FETCH = 'btnPDFetch';
var LISTVIEW_FINAL_DECISION = 'Qvar_Final_Desc_PPM';
var FETCH_DETAILS = 'btnINFFetchAcc';
var FINAL_DEDUPE = 'BTN_DUPE';
var BUTTON_ADD_PARTY_DETAILS = 'btnAddPartyDetails';
var BUTTON_ADD_CONTRACT_DETAILS = 'btnAddContractLimits';
var BUTTON_MODIFY_CONTRACT_DETAILS = 'btnModifyContractLimits';
var FORM_CONTROLS_PARTY = 'TFO_PARTY_TYPE,TFO_PARTY_DESC,TFO_PD_PARTY_ID,TFO_PD_CUSTOMER_NAME,'
	+ 'TFO_PD_ADDRESS1,TFO_PD_ADDRESS2,TFO_PD_ADDRESS3,TFO_PD_ADDRESS4,TFO_PD_COUNTRY,'
	+ 'TFO_MEDIA_TYPE,TFO_PD_ADDRESS';
var FORM_CONTROLS_CONTROL_LIMITS = 'cl_serialNumber,cl_combo_operation,cl_combo_partyType,cl_customer_no,cl_combo_type,'
		+ 'cl_linkageRefNo,cl_per_contribution,cl_combo_amountTag';
var FINAL_DECISION_GRID_ADDITIONAL_MAIL ='QVAR_FINAL_DESC_PPM_NEW_MAIL';
var TR_FETCH_RATE_BUTTON ='FETCH_RATE';
var LISTVIEW_LLI='Qvar_LLI_Details';
var BUTTON_GENERATE_PDF_PM = 'Btn_Gen_PDF';
var FORM_CONTROLS_LLI = 'TXT_VESSELNAME,SHIPMENT_DATE,TXT_VESSELFLAG,TXT_VESSELID,TXT_VESSELIMO';
var LLI_ALERT = 'Are you sure to delete selected vessel as all its details will be removed from WI '+' Please confirm to Proceed';
//getValue('WI_NAME')+

//ppm input tab fields
var FIELD_SIGACC_ACC_TOTAL_BAL='SIGACC_ACC_TOTAL_BAL';
var FIELD_SIGACC_ACC_CURR_BAL='SIGACC_ACC_CURR_BAL';
var FIELD_SIGACC_DOMCL_BRN_CODE='SIGACC_DOMCL_BRN_CODE';
var FIELD_SIGACC_ACC_CURRENCY='SIGACC_ACC_CURRENCY';
var FIELD_SIGACC_ACC_MNDT='SIGACC_ACC_MNDT';
var FIELD_TXT_SIGACC_ACC_NO='TXT_SIGACC_ACC_NO';
var FIELD_GRNTEE_EXP_DATE='GRNTEE_CNTR_EXP_DATE';
var FIELD_PRO_TRADE_REF_NO='PRO_TRADE_REF_NO';
var FIELD_INSTRCTN_TO_BANK='INSTRCTN_TO_BANK';
var FIELD_PRO_TRADE_SETTLEMENT_INST='PRO_TRADE_SETTLEMENT_INST';
var FIELD_LC_TOLERANCE='LC_TOLERANCE';
var BUTTON_ADD_DOC_CHKLIST='btnModify';
var BUTTON_RETRY_ADD_DOC='btnRetry';
var LISTVIEW_DOC_CHKLIST='Qvar_Doc_Rvw';
var LISTVIEW_DRAFT_DETAILS='Qvar_Draft_Details';
var BUTTON_LIMIT_ADD_CKLIST='lmtCrdtBtnFetch';
var LISTVIEW_LIMIT_CKLIST='Qvar_Lmt_Crdt_ID';
var LISTVIEW_FFT_DETAIL='Qvar_FFT_Details';
var FIELD_ISSUING_BANK_LC_NO='ISSUING_BANK_LC_NO';
var FIELD_ADVISING_BANK_REF='ADVISING_BANK_REF';
var FIELD_GRNTEE_APP_CNTRCT_REF_NO='GRNTEE_APP_CNTRCT_REF_NO';
var FIELD_GRNTEE_BEN_CNTRCT_REF_NO='GRNTEE_BEN_CNTRCT_REF_NO';
var QVAR_CHRGS_LEGAL_AMT='Q_Charges_Frame_legalAmount';
var QVAR_CHRGS_PENALTY_AMT='Q_Charges_Frame_penaltyAmount';
var QVAR_CHRGS_OVERDRAWN_AMT='Q_Charges_Frame_overdrawnAmount';
var QVAR_CHRGS_OTHER_AMT='Q_Charges_Frame_otherAmount';
var DATE_INF_BASE_DOC='INF_BASE_DOC_DATE';
var DATE_INF_MATURITY='INF_MATURITY_DATE';
var COMBOX_LMTCRE_APP_AVL='LMTCRE_APP_AVL_PPM';
var COMBOX_DOC_REV_SUCC='DOC_REV_SUCC_PPM';
var COMBOX_LMTCRE_REF_TO='LMTCRE_REF_TO';
var COMBOX_TXT_REQ_APP='TXT_REQ_APP_PPM';
var COMBOX_DOCREV_REF_TO='DOCREV_REF_TO';
var COMBOX_REQ_SIGN_MAN='REQ_SIGN_MAN_PPM';
var COMBOX_SUFF_BAL_AVL='SUFF_BAL_AVL_PPM';
var COMBOX_TXTVETT_REF_TO='TXTVETT_REF_TO';
var COMBOX_SIGACC_REF_TO='SIGACC_REF_TO';
var FIELD_SIGACC_EXC_RMKS='SIGACC_EXC_RMKS';
var COMBOX_BILL_CUST_HLDING_ACC_US='BILL_CUST_HLDING_ACC_US';
var COMBOX_INF_CHARGE_ACC_NUM='INF_CHARGE_ACC_NUM';
var COMBOX_REJ_RESN='REJ_RESN_PPM';
var FIELD_CPD_COUNTER_PARTY_NAME_ID='CPD_COUNTER_PARTY_NAME_ID';
var COMBOX_INF_SETTLEMENT_ACC_NUM='INF_SETTLEMENT_ACC_NUM';
var FIELD_CPD_ACTIVITY_NAME_ID='CPD_ACTIVITY_NAME_ID';
var DATE_CPD_INSERTED='CPD_INSERTED_DATE_ID';
var FIELD_CPD_TRANSACTION_ID='CPD_TRANSACTION_ID';
var COMBOX_REF_ICG_RM='REF_ICG_RM';
var LISTVIEW_CPD_DETAILS='Qvar_cpd_details';
var LISTVIEW_SIGN_ACC='lvwSignAcc';
var LISTVIEW_TXT_VETTING='lvwTxtVet';
var LISTVIEW_LINKED_CUST='QVar_linked_cust';
var COMBOX_TRN_THIRD_PARTY='TRN_THIRD_PARTY';
var COMBOX_IFS_LOAN_GRP='IFS_LOAN_GRP';
var COMBOX_INF_AMEND_TYPE='INF_AMEND_TYPE';
var COMBOX_PRODUCT_TYPE='PRODUCT_TYPE';
var COMBOX_BILL_MODE_OF_PMNT='BILL_MODE_OF_PMNT';
var COMBOX_INF_CREDIT_ACC_NUM='INF_CREDIT_ACC_NUM';
var COMBOX_BILL_RVSD_DOC_AVL='BILL_RVSD_DOC_AVL';
var DATE_INF_NEW_MATURITY='INF_NEW_MATURITY_DATE';
var FIELD_INF_CHARGE_ACC_TITLE='INF_CHARGE_ACC_TITLE';
var FIELD_INF_CHARGE_ACC_CURR='INF_CHARGE_ACC_CURR';
var FIELD_INF_SETTLEMENT_ACC_TITLE='INF_SETTLEMENT_ACC_TITLE';
var FIELD_INF_SETTLEMENT_ACC_CURR='INF_SETTLEMENT_ACC_CURR';
var FIELD_INF_CREDIT_ACC_TITLE='INF_CREDIT_ACC_TITLE';
var FIELD_INF_CREDIT_ACC_CURR='INF_CREDIT_ACC_CURR';
var FIELD_GRNT_CHRG_ACC_TITLE='GRNT_CHRG_ACC_TITLE';
var FIELD_GRNT_CHRG_ACC_CRNCY='GRNT_CHRG_ACC_CRNCY';
var BUTTON_ADD_SIGN='btnAddSign';
var BUTTON_ADD_DOC='btnAddDoc';
var FIELD_DOCREV_EXC_RMKS='DOCREV_EXC_RMKS';
var BUTTON_ADD_TXT_VETT='btnAddTxtVet';
var FIELD_TXTVETT_EXC_RMKS='TXTVETT_EXC_RMKS';
var BUTTON_LIMIT_CREDIT_ADD='LIMIT_CREDIT_ADD';
var FIELD_LMTCRE_EXC_RMKS='LMTCRE_EXC_RMKS';
var BUTTON_FETCH_ACC_DETAIL='btnFetchAccDetails';
var BUTTON_FETCH_ACC_MEMO='btnFetchAccMemo';
var COMBO_BC_CALL_DONE='BC_CALL_DONE';
//santhosh changes
var EXPIRY_COND='EXPIRY_COND';
var CNTR_GTEE_EXP_DATE='CNTR_GTEE_EXP_DATE';
var ADDN_AMT_INFO='ADDN_AMT_INFO';
var PUR_OF_GTEE='PUR_OF_GTEE';
var TRANSFER_INDICATOR='TRANSFER_INDICATOR';
var TRANSFER_CONDITIONS='TRANSFER_CONDITIONS';
var PROJECT_NAME='PROJECT_NAME';
var DELIVERY_INSTR='DELIVERY_INSTR';
var LANG='LANG';
var FCUBS_PUR_OF_MSG='FCUBS_PUR_OF_MSG';
var SWIFT_PUR_OF_MSG='SWIFT_PUR_OF_MSG';
var COMBOX_TXT_FORMAT = 'TXT_FORMAT_PPM'; //added by Rakshita
//santhosh changes end
//added new field for SWIFT CHANGES DATE 23-10-2023
var SUPPL_INFO_AMT ='SUPPL_INFO_AMT';
var GOVT_LAW_JURSD ='GOVT_LAW_JURSD';


var FIELD_SWIFT_CID = 'SWIFT_CID';
var COMBO_CUST_INSTR='CUST_INSTR';
//PROTRADE CONSTANTS
var PT_UTILITY_FLAG = 'PT_UTILITY_FLAG';
var PT_GTEE_FRAME = 'PT_GTEE_FRAME';
var PT_FFT_FRAME = 'PT_FFT_Frame';
var PM_TAB_CLICK = 'onClickTabPM';
var SAVE_AND_NEXT = 'TABCLICK';
var INF_ACTUAL_TENOR_BASE = 'INF_ACTUAL_TENOR_BASE';
var PT_CUST_EMAIL_ID ='PT_CUST_EMAIL_ID';
var NARRATIVE  = 'NARRATIVE';
var ADDN_CONDITION = 'ADDN_CONDITION';
var PT_AMENDMENT_FRAME = 'PT_AMENDMENT_FRAME';
var CUST_INSTRUCTION_SECTION  = 'CUST_INSTRUCTION_SECTION';
var BILL_TYPE = 'BILL_TYPE';

var IF_SIGHT_BILL           = 'IF_SIGHT_BILL';
var DISCREPANCY_INSTRUCTION = 'DISCREPANCY_INSTRUCTION';
var SETTLEMENT_INSTRUCTION  = 'SETTLEMENT_INSTRUCTION';
var PT_HYBRID_PROFILE_TXN = 'PT_HYBRID_PROFILE_TXN';
var ROUTE_TO_PM = 'ROUTE_TO_PM';

//TSLSM CONSTANTS
var PROCESSING_SYSTEM = 'PROCESSING_SYSTEM'; 

//TSLSM PPM/PM/PC/PMS/PCS CONSTANTS
var TSLM_STANDALONE_LOAN = 'STANDALONE_LOAN';
var INF_TENOR_DAYS = 'INF_TENOR_DAYS';
var TSLM_FINANCED_AMOUNT = 'FINANCED_AMOUNT';
var TSLM_OVERALL_OUTSTANDING_AMOUNT = 'OVERALL_OUTSTANDING_AMOUNT';
var TSLM_LOAN_STAGE = 'LOAN_STAGE';
var TSLM_IF_PURCHASE_PRODUCT_CODE = 'IF_PURCHASE_PRODUCT_CODE';
var TSLM_FUNDING_REQUIRED = 'FUNDING_REQUIRED';
var TSLM_ADDITIONAL_LOAN_AMOUNT = 'ADDITIONAL_LOAN_AMOUNT';
var SEC_TSLM_LOAN_INPUT_DETAILS = 'SEC_TSLM_LOAN_INPUT_DETAILS';
var SEC_TSLM_COUNTER_PARTY_DETAILS = 'SEC_TSLM_COUNTER_PARTY_DETAILS';
var SEC_TSLM_INVOICE_NUMBERS_FOR_STANDALONE_LOAN = 'SEC_INVOICE_NUMBERS_FOR_STANDALONE_LOAN';
var SEC_TSLM_CUST_SPECIAL_INST = 'SEC_TSLM_CUST_SPECIAL_INST';
var TSLM_INST_TOGGLE = 'Toggle2';
var BTN_FETCH_TSLM_CID_DETAILS = 'BTN_FETCH_TSLM_CID_DETAILS';
var TSLM_COMPANY_TYPE = 'TSLM_COMPANY_TYPE';
var TAB_TSLM_LOAN_REF = 'TAB_TSLM_LOAN_REF';
var TSLM_DEDUPE_LABEL = 'TSLM_DEDUPE_LABEL';
var TSLM_INVOICE_CHK_CONFIRM = 'TSLM_INVOICE_CHK_CONFIRM';
var BTN_TSLM_INVOICE_CHK_CONFIRM = 'BTN_TSLM_INVOICE_CHK_CONFIRM';
var TSLM_PENAL_IR = 'TSLM_PENAL_IR';
var TSLM_ANY_PAST_DUE_CID = 'TSLM_ANY_PAST_DUE_CID';
var FCUBS_ANY_PAST_DUE_CID = 'FCUBS_ANY_PAST_DUE_CID';
var SEC_TSLM_REF_DET = 'SEC_TSLM_REF_DET';

var LISTVIEW_TSLM_CPD = 'Q_TSLm_Counter_Dets';
var LISTVIEW_TSLM_INVOICE_NO = 'Q_TSLM_Invoice_No_SA_Loan';

var IFS_IFC_IFA_LOAD_ENABLE = 'PROCESSING_SYSTEM,STANDALONE_LOAN,BTN_FETCH_TSLM_CID_DETAILS,BTN_FETCH_TSLM_CID_DETAILS,'+
	'FCUBS_ANY_PAST_DUE_CID,TSLM_ANY_PAST_DUE_CID,SEC_TSLM_COUNTER_PARTY_DETAILS,SEC_TSLM_INVOICE_NUMBERS_FOR_STANDALONE_LOAN,'+
	'SEC_TSLM_REFERRAL_DETAILS,SEC_TSLM_REF_DET';
var DISBURSEMENT_LOAD_ENABLE = 'TSLM_COMPANY_TYPE,Toggle2,TSLM_ANY_PAST_DUE_CID,TSLM_DEDUPE_LABEL,TSLM_INVOICE_CHK_CONFIRM,BTN_TSLM_INVOICE_CHK_CONFIRM';
var A_S_CP_LOAD_ENABLE = 'SEC_TSLM_LOAN_INPUT_DETAILS,FINANCED_AMOUNT,OVERALL_OUTSTANDING_AMOUNT,LOAN_STAGE,SEC_TSLM_COUNTER_PARTY_DETAILS';
var B_S_CP_LOAD_ENABLE = 'IF_PURCHASE_PRODUCT_CODE,FUNDING_REQUIRED,ADDITIONAL_LOAN_AMOUNT';

var TSLM_LOAN_AMOUNT = 'LOAN_AMOUNT';
var SEC_TSLM_LOAN_REF_DET = 'SEC_TSLM_LOAN_REF_DET';
var TSLM_INST_TOGGLE_PMS_PCS = 'Toggle1';
var SEC_PS_SL_FINAL = 'SEC_PS_SL_FINAL';
var PREV_WS = 'PREV_WS';
var TRSD_SCREENING_DATA_BTN = 'TRSD_SCREENING_DATA_BTN';
var LISTVIEW_REF_DocRvw='lvwDocRvw';

var ANY_DOC_COURRIER = 'LC_DOC_COURIER';
var PURPOSE_OF_MESSAGE = "SWIFT_PUR_OF_MSG";
var CUSTOMER_INSTRUCTION = 'CONFN_INTRN';
var REQ_CONFIRM_PARTY = 'REQ_CONF_PARTY';
var FCUBS_PUR_OF_MSG = 'FCUBS_PUR_OF_MSG';
var PT_ILC_FRAME_FIELD_HIDE = 'EXP_PLACE,TRANSFERABLE,CREDIT_MODE,LC_TOTAL_EXPOSURE,PARTIAL_SHIPMENT,PARTIAL_SHIPMENT_CONDITIONAL,TRANSSHIPMENT,TRANSSHIPMENT_CONDITIONAL,SHIPMENT_PERIOD,PERIOD_PRESENT_DAYS,PERIOD_PRESENT_MODE,PERIOD_PRESENT_MODE,PRINCIPAL_ACC_NUMBER,ADDN_AMT_COVERED,SPEC_PAYMENT_CONDN,DEFERRED_PAYMENT,Qvar_Draft_Details';
var TRN_THIRD_PARTY='TRN_THIRD_PARTY';
var OPTIONAL_ENTITY = 'table182_entity';   //Added by reyaz 26-05-2023
var PPM_ILC_NI_PT_SHOW = 'CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE';  //ATP-383 13-FEB-24 JAMSHED


//ATP-458 JAMSHED 06-JUN-2024 START
var INI_ILC_NI_SWIFT_MT798_SHOW  ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,BANK_REF_NO,BANK_BUS_REF,TEXT_PURP,MSG_CR_DTTIME,METH_ISS,DR_ACC_NUM,BANK_CHG_PBY,CHG_INFO,CHG_DR_ACC,CNF_CHG_PBY,REQ_CNF_PARTY,TRANSPORT_MODE,FWD_CONT_REF_NO,APPL_UNDERTAKING,CUST_CONTACT,SEN_REC_INFO,FILE_ID,CUST_ID,PR_BANK_ID,LEAD_BANK_ID,FRM_MT798,CUST_ID_DESC,FILE_ID_DESC';
var INI_ILC_NI_SWIFT_MT798_DISABLE ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,BANK_REF_NO,BANK_BUS_REF,TEXT_PURP,MSG_CR_DTTIME,METH_ISS,DR_ACC_NUM,BANK_CHG_PBY,CHG_INFO,CHG_DR_ACC,CNF_CHG_PBY,REQ_CNF_PARTY,TRANSPORT_MODE,FWD_CONT_REF_NO,APPL_UNDERTAKING,CUST_CONTACT,SEN_REC_INFO,FILE_ID,CUST_ID,PR_BANK_ID,LEAD_BANK_ID,PROCESS_TYPE,REQUEST_CATEGORY,REQUEST_TYPE,REQUESTED_BY,SOURCE_CHANNEL,CUST_ID_DESC,FILE_ID_DESC,EXTN_PERIOD_B,TXN_REF_NO_LC';
var PPM_ILC_NI_SWIFT_MT798_SHOW ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,BANK_REF_NO,BANK_BUS_REF,TEXT_PURP,MSG_CR_DTTIME,METH_ISS,DR_ACC_NUM,BANK_CHG_PBY,CHG_INFO,CHG_DR_ACC,CNF_CHG_PBY,REQ_CNF_PARTY,TRANSPORT_MODE,FWD_CONT_REF_NO,APPL_UNDERTAKING,CUST_CONTACT,SEN_REC_INFO,FILE_ID,CUST_ID,PR_BANK_ID,LEAD_BANK_ID,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,PT_COMMON,PT_ILC_FRAME,PT_CUST_EMAIL_ID,FRM_MT798,AVL_WITH,AVL_WITH_D,COND_FR_BANK,SUPPORTING_DOCS_REQ_PER_CREDIT_APPROVAL,CUST_ID_DESC,FILE_ID_DESC';
var PPM_ILC_NI_SWIFT_MT798_DISABLE ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,BANK_REF_NO,BANK_BUS_REF,TEXT_PURP,MSG_CR_DTTIME,METH_ISS,DR_ACC_NUM,BANK_CHG_PBY,CHG_INFO,CHG_DR_ACC,CNF_CHG_PBY,REQ_CNF_PARTY,TRANSPORT_MODE,FWD_CONT_REF_NO,APPL_UNDERTAKING,CUST_CONTACT,SEN_REC_INFO,FILE_ID,CUST_ID,PR_BANK_ID,LEAD_BANK_ID,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,LC_DOC_COURIER,AVL_WITH,AVL_WITH_D,COND_FR_BANK,CUST_ID_DESC,FILE_ID_DESC';
var PPM_ILC_NI_SWIFT_MT798_HIDE = 'PT_AMENDMENT_FRAME';
var PM_ILC_NI_SWIFT_MT798_SHOW ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,BANK_REF_NO,BANK_BUS_REF,TEXT_PURP,MSG_CR_DTTIME,METH_ISS,DR_ACC_NUM,BANK_CHG_PBY,CHG_INFO,CHG_DR_ACC,CNF_CHG_PBY,REQ_CNF_PARTY,TRANSPORT_MODE,FWD_CONT_REF_NO,APPL_UNDERTAKING,CUST_CONTACT,SEN_REC_INFO,FILE_ID,CUST_ID,PR_BANK_ID,LEAD_BANK_ID,ASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,PT_COMMON,PT_ILC_FRAME,PT_CUST_EMAIL_ID,FRM_MT798,AVL_WITH,AVL_WITH_D,COND_FR_BANK,SUPPORTING_DOCS_REQ_PER_CREDIT_APPROVAL,CUST_ID_DESC,FILE_ID_DESC';
var PM_ILC_NI_SWIFT_MT798_DISABLE ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,BANK_REF_NO,BANK_BUS_REF,TEXT_PURP,MSG_CR_DTTIME,METH_ISS,DR_ACC_NUM,BANK_CHG_PBY,CHG_INFO,CHG_DR_ACC,CNF_CHG_PBY,REQ_CNF_PARTY,TRANSPORT_MODE,FWD_CONT_REF_NO,APPL_UNDERTAKING,CUST_CONTACT,SEN_REC_INFO,FILE_ID,CUST_ID,PR_BANK_ID,LEAD_BANK_ID,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,LC_DOC_COURIER,AVL_WITH,AVL_WITH_D,COND_FR_BANK,CUST_ID_DESC,FILE_ID_DESC';
var PM_ILC_NI_SWIFT_MT798_HIDE = 'COMP_CHK_DONE,COMP_POSITIVE_MATCH';


var INI_GRNT_NI_SWIFT_MT798_SHOW  ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,BANK_REF_NO,BANK_BUS_REF,TEXT_PURP,MSG_CR_DTTIME,METH_ISS_LG,DR_ACC_NUM,TYPE_UNDR,TYPE_UNDR_DESC,CUST_ID,CUST_ID_DESC,SPL_TERMS,LANG_WORDING,APPROX_EXP_DATE,CHG_DR_ACC,REF_LG,REF_LG_DESC,REF_DATE,CONT_CCY,CONT_AMOUNT,UNDR_VAL_PCT,BENE_CONT,SPL_AGREE,CUST_CONTACT,LCL_UNDR_BENCONT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,PR_BANK_ID,LEAD_BANK_ID,FRM_MT798';
var INI_GRNT_NI_SWIFT_MT798_DISABLE ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,BANK_REF_NO,BANK_BUS_REF,TEXT_PURP,MSG_CR_DTTIME,METH_ISS_LG,DR_ACC_NUM,TYPE_UNDR,TYPE_UNDR_DESC,CUST_ID,CUST_ID_DESC,SPL_TERMS,LANG_WORDING,APPROX_EXP_DATE,CHG_DR_ACC,REF_LG,REF_LG_DESC,REF_DATE,CONT_CCY,CONT_AMOUNT,UNDR_VAL_PCT,BENE_CONT,SPL_AGREE,CUST_CONTACT,LCL_UNDR_BENCONT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,PR_BANK_ID,LEAD_BANK_ID,PROCESS_TYPE,REQUEST_CATEGORY,REQUEST_TYPE,REQUESTED_BY,SOURCE_CHANNEL';
var PPM_GRNT_NI_SWIFT_MT798_SHOW ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,BANK_REF_NO,BANK_BUS_REF,TEXT_PURP,MSG_CR_DTTIME,METH_ISS_LG,DR_ACC_NUM,TYPE_UNDR,TYPE_UNDR_DESC,CUST_ID,CUST_ID_DESC,SPL_TERMS,LANG_WORDING,APPROX_EXP_DATE,CHG_DR_ACC,REF_LG,REF_LG_DESC,REF_DATE,CONT_CCY,CONT_AMOUNT,UNDR_VAL_PCT,BENE_CONT,SPL_AGREE,CUST_CONTACT,LCL_UNDR_BENCONT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,PR_BANK_ID,LEAD_BANK_ID,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,PT_COMMON,PT_GRNT_FRAME,PT_CUST_EMAIL_ID,FRM_MT798,AVL_WITH,AVL_WITH_D,COND_FR_BANK,SUPPORTING_DOCS_REQ_PER_CREDIT_APPROVAL';
var PPM_GRNT_NI_SWIFT_MT798_DISABLE ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,BANK_REF_NO,BANK_BUS_REF,TEXT_PURP,MSG_CR_DTTIME,METH_ISS_LG,DR_ACC_NUM,TYPE_UNDR,TYPE_UNDR_DESC,CUST_ID,CUST_ID_DESC,SPL_TERMS,LANG_WORDING,APPROX_EXP_DATE,CHG_DR_ACC,REF_LG,REF_LG_DESC,REF_DATE,CONT_CCY,CONT_AMOUNT,UNDR_VAL_PCT,BENE_CONT,SPL_AGREE,CUST_CONTACT,LCL_UNDR_BENCONT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,PR_BANK_ID,LEAD_BANK_ID,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,LC_DOC_COURIER,AVL_WITH,AVL_WITH_D,COND_FR_BANK';
var PPM_GRNT_NI_SWIFT_MT798_HIDE = 'PT_AMENDMENT_FRAME';
var PM_GRNT_NI_SWIFT_MT798_SHOW ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,BANK_REF_NO,BANK_BUS_REF,TEXT_PURP,MSG_CR_DTTIME,METH_ISS_LG,DR_ACC_NUM,TYPE_UNDR,TYPE_UNDR_DESC,CUST_ID,CUST_ID_DESC,SPL_TERMS,LANG_WORDING,APPROX_EXP_DATE,CHG_DR_ACC,REF_LG,REF_LG_DESC,REF_DATE,CONT_CCY,CONT_AMOUNT,UNDR_VAL_PCT,BENE_CONT,SPL_AGREE,CUST_CONTACT,LCL_UNDR_BENCONT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,PR_BANK_ID,LEAD_BANK_ID,ASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,PT_COMMON,PT_GRNT_FRAME,PT_CUST_EMAIL_ID,FRM_MT798,AVL_WITH,AVL_WITH_D,COND_FR_BANK,SUPPORTING_DOCS_REQ_PER_CREDIT_APPROVAL';
var PM_GRNT_NI_SWIFT_MT798_DISABLE ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,BANK_REF_NO,BANK_BUS_REF,TEXT_PURP,MSG_CR_DTTIME,METH_ISS_LG,DR_ACC_NUM,TYPE_UNDR,TYPE_UNDR_DESC,CUST_ID,CUST_ID_DESC,SPL_TERMS,LANG_WORDING,APPROX_EXP_DATE,CHG_DR_ACC,REF_LG,REF_LG_DESC,REF_DATE,CONT_CCY,CONT_AMOUNT,UNDR_VAL_PCT,BENE_CONT,SPL_AGREE,CUST_CONTACT,LCL_UNDR_BENCONT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,PR_BANK_ID,LEAD_BANK_ID,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,LC_DOC_COURIER,AVL_WITH,AVL_WITH_D,COND_FR_BANK';
var PM_GRNT_NI_SWIFT_MT798_HIDE = 'COMP_CHK_DONE,COMP_POSITIVE_MATCH';

//ATP-458 JAMSHED 06-JUN-2024 END


//ATP-490 SHIVANSHU 25-JULY-2024 START
var INI_ILC_AM_SWIFT_MT798_SHOW  ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,TXN_REF_NO_LC,MSG_CR_DTTIME,METH_ISS,BANK_CHG_PBY,CHG_INFO,CUST_CONTACT,SEN_REC_INFO,FILE_ID,CUST_ID,PR_BANK_ID,LEAD_BANK_ID,FRM_MT798,CUST_ID_DESC,FILE_ID_DESC,EXTN_PERIOD_B';
var INI_ILC_AM_SWIFT_MT798_DISABLE ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,TXN_REF_NO_LC,MSG_CR_DTTIME,METH_ISS,BANK_CHG_PBY,CHG_INFO,CUST_CONTACT,SEN_REC_INFO,FILE_ID,CUST_ID,PR_BANK_ID,LEAD_BANK_ID,PROCESS_TYPE,REQUEST_CATEGORY,REQUEST_TYPE,REQUESTED_BY,SOURCE_CHANNEL,CUST_ID_DESC,FILE_ID_DESC,EXTN_PERIOD_B';
var INI_ILC_AM_SWIFT_MT798_ENABLE  ='FLG_ACK_GEN';
var PPM_ILC_AM_SWIFT_MT798_SHOW ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,TXN_REF_NO_LC,MSG_CR_DTTIME,METH_ISS,BANK_CHG_PBY,CHG_INFO,CUST_CONTACT,SEN_REC_INFO,FILE_ID,CUST_ID,PR_BANK_ID,LEAD_BANK_ID,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,PT_COMMON,PT_ILC_FRAME,PT_CUST_EMAIL_ID,FRM_MT798,AVL_WITH,AVL_WITH_D,COND_FR_BANK,SUPPORTING_DOCS_REQ_PER_CREDIT_APPROVAL,CUST_ID_DESC,FILE_ID_DESC,EXTN_PERIOD_B';
var PPM_ILC_AM_SWIFT_MT798_DISABLE ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,TXN_REF_NO_LC,MSG_CR_DTTIME,METH_ISS,BANK_CHG_PBY,CHG_INFO,CUST_CONTACT,SEN_REC_INFO,FILE_ID,CUST_ID,PR_BANK_ID,LEAD_BANK_ID,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,LC_DOC_COURIER,AVL_WITH,AVL_WITH_D,COND_FR_BANK,CUST_ID_DESC,FILE_ID_DESC,EXTN_PERIOD_B';
var PPM_ILC_AM_SWIFT_MT798_HIDE = 'PT_ILC_FRAME';

var PM_ILC_AM_SWIFT_MT798_SHOW ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,TXN_REF_NO_LC,MSG_CR_DTTIME,METH_ISS,BANK_CHG_PBY,CHG_INFO,CUST_CONTACT,SEN_REC_INFO,FILE_ID,CUST_ID,PR_BANK_ID,LEAD_BANK_ID,ASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,PT_COMMON,PT_ILC_FRAME,PT_CUST_EMAIL_ID,FRM_MT798,AVL_WITH,AVL_WITH_D,COND_FR_BANK,SUPPORTING_DOCS_REQ_PER_CREDIT_APPROVAL,CUST_ID_DESC,FILE_ID_DESC,EXTN_PERIOD_B';
var PM_ILC_AM_SWIFT_MT798_DISABLE ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,TXN_REF_NO_LC,MSG_CR_DTTIME,METH_ISS,BANK_CHG_PBY,CHG_INFO,CUST_CONTACT,SEN_REC_INFO,FILE_ID,CUST_ID,PR_BANK_ID,LEAD_BANK_ID,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,LC_DOC_COURIER,AVL_WITH,AVL_WITH_D,COND_FR_BANK,CUST_ID_DESC,FILE_ID_DESC,EXTN_PERIOD_B';
var PM_ILC_AM_SWIFT_MT798_HIDE = 'COMP_CHK_DONE,COMP_POSITIVE_MATCH,PT_ILC_FRAME';


var INI_GRNT_AM_SWIFT_MT798_SHOW  ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,TXN_REF_NO_LC,MSG_CR_DTTIME,METH_ISS_LG,SPL_AGREE,CUST_ID,CUST_ID_DESC,CUST_CONTACT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,PR_BANK_ID,LEAD_BANK_ID,FRM_MT798,EXTN_PERIOD_B';
var INI_GRNT_AM_SWIFT_MT798_DISABLE ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,TXN_REF_NO_LC,MSG_CR_DTTIME,METH_ISS_LG,SPL_AGREE,CUST_ID,CUST_ID_DESC,CUST_CONTACT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,PR_BANK_ID,LEAD_BANK_ID,PROCESS_TYPE,REQUEST_CATEGORY,REQUEST_TYPE,REQUESTED_BY,SOURCE_CHANNEL,EXTN_PERIOD_B';
var PPM_GRNT_AM_SWIFT_MT798_SHOW ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,TXN_REF_NO_LC,MSG_CR_DTTIME,METH_ISS_LG,SPL_AGREE,CUST_ID,CUST_ID_DESC,CUST_CONTACT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,PR_BANK_ID,LEAD_BANK_ID,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,PT_COMMON,PT_GRNT_FRAME,PT_CUST_EMAIL_ID,FRM_MT798,AVL_WITH,AVL_WITH_D,COND_FR_BANK,SUPPORTING_DOCS_REQ_PER_CREDIT_APPROVAL,EXTN_PERIOD_B';
var PPM_GRNT_AM_SWIFT_MT798_DISABLE ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,TXN_REF_NO_LC,MSG_CR_DTTIME,METH_ISS_LG,SPL_AGREE,CUST_ID,CUST_ID_DESC,CUST_CONTACT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,PR_BANK_ID,LEAD_BANK_ID,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,LC_DOC_COURIER,AVL_WITH,AVL_WITH_D,COND_FR_BANK,EXTN_PERIOD_B';

var PM_GRNT_AM_SWIFT_MT798_SHOW ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,TXN_REF_NO_LC,MSG_CR_DTTIME,METH_ISS_LG,SPL_AGREE,CUST_ID,CUST_ID_DESC,CUST_CONTACT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,PR_BANK_ID,LEAD_BANK_ID,ASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,PT_COMMON,PT_GRNT_FRAME,PT_CUST_EMAIL_ID,FRM_MT798,AVL_WITH,AVL_WITH_D,COND_FR_BANK,SUPPORTING_DOCS_REQ_PER_CREDIT_APPROVAL,EXTN_PERIOD_B';
var PM_GRNT_AM_SWIFT_MT798_DISABLE ='TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,CUST_BUS_REF,TXN_REF_NO_LC,MSG_CR_DTTIME,METH_ISS_LG,SPL_AGREE,CUST_ID,CUST_ID_DESC,CUST_CONTACT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,PR_BANK_ID,LEAD_BANK_ID,CASHMRG_ACCNO,IS_100PCT_CASHBACK,LL_CODE,LC_DOC_COURIER,AVL_WITH,AVL_WITH_D,COND_FR_BANK,EXTN_PERIOD_B';
var PM_GRNT_AM_SWIFT_MT798_HIDE = 'COMP_CHK_DONE,COMP_POSITIVE_MATCH';

var PM_SWIFT_MT798_LABEL_SHOW ='label526,label527,label528,label529,label530,label531,label532,label533,label534,label535,label536,label537,label538,label539,label540,label541,label542,label543,label544,label545,label546';


//ATP-490 SHIVANSHU 25-JULY-2024 END

//ATP-504 JAMSHED 09-08-2024 START

var INI_MISC_MSM_SWIFT_MT798_SHOW  ='FRM_MT798,TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,BANK_REF_NO,BANK_BUS_REF,MSG_CR_DTTIME,CUST_CONTACT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,EXTN_PERIOD_B,CUST_ID,PR_BANK_ID,LEAD_BANK_ID';
var INI_MISC_MSM_SWIFT_MT798_DISABLE ='PROCESS_TYPE,REQUEST_CATEGORY,REQUEST_TYPE,REQUESTED_BY,SOURCE_CHANNEL,TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,BANK_REF_NO,BANK_BUS_REF,MSG_CR_DTTIME,CUST_CONTACT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,EXTN_PERIOD_B,CUST_ID,PR_BANK_ID,LEAD_BANK_ID';

var PPM_MISC_MSM_SWIFT_MT798_SHOW ='FRM_MT798,TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,BANK_REF_NO,BANK_BUS_REF,MSG_CR_DTTIME,CUST_CONTACT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,EXTN_PERIOD_B,CUST_ID,PR_BANK_ID,LEAD_BANK_ID';
var PPM_MISC_MSM_SWIFT_MT798_DISABLE ='PROCESS_TYPE,REQUEST_CATEGORY,REQUEST_TYPE,REQUESTED_BY,SOURCE_CHANNEL,TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,BANK_REF_NO,BANK_BUS_REF,MSG_CR_DTTIME,CUST_CONTACT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,EXTN_PERIOD_B,CUST_ID,PR_BANK_ID,LEAD_BANK_ID';

var PM_MISC_MSM_SWIFT_MT798_SHOW ='FRM_MT798,TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,BANK_REF_NO,BANK_BUS_REF,MSG_CR_DTTIME,CUST_CONTACT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,EXTN_PERIOD_B,CUST_ID,PR_BANK_ID,LEAD_BANK_ID';
var PM_MISC_MSM_SWIFT_MT798_DISABLE ='PROCESS_TYPE,REQUEST_CATEGORY,REQUEST_TYPE,REQUESTED_BY,SOURCE_CHANNEL,TXN_REF_NO,SUB_MSG_TYPE,PROP_MSG,MSG_INDEX_TOTAL,CUST_REF_NO,BANK_REF_NO,BANK_BUS_REF,MSG_CR_DTTIME,CUST_CONTACT,SEN_REC_INFO,FILE_ID,FILE_ID_DESC,EXTN_PERIOD_B,CUST_ID,PR_BANK_ID,LEAD_BANK_ID';


//ATP-504 JAMSHED 09-08-2024 END 

//TrayTS_REFERENCEdstream |reyaz|09-10-2024|  start
var SKIP_TS_FLAG ='SKIP_TS_FLAG';
var TS_JUSTIFICATION ='TS_JUSTIFICATION';
var TS_REFERENCE ='TSTXNID';
var TS_STATUS ='TSSTATUS';
var TS_REQUIRED ='IS_TS_REQUIRED';
var TS_REQ_CAT=["IC","EC","ELCB","ILCB"];
var TS_REQ_TYPE=["IC_BL","EC_BL","ELCB_BL","ILCB_BL"];
var TS_HIDE='REF_FRAME,SEC_TSLM_REF_DET,FRM_DUPE,FRM_TR_DTLS,btnRetry,FRM_SWIFT,label11,EDAS_REFERENCE,ROUTE_TO_PPM,REF_ICG_RM,EDAS_APPROVAL,LEGALIZATION_CHARGES,CHKBX_SEND_MAIL';
var BUTTON_TSINQUIRY='btnInquiry';
var TS_DISABLE='SOURCE_CHANNEL,RELATIONSHIP_TYPE,BRANCH_CITY,ASSIGNED_CENTER,BRN_CODE,DELIVERY_BRANCH,btnSubmit';
var TS_SHOW='btnInquiry,TSSTATUS,TSTXNID';
var TS_REQ_FIELD_CAT=['ILC', 'ELC'];
var TS_REQ_FIELD_TYPE=['ILC_NI', 'ELC_LCA'];
//Traydstream |reyaz|09-10-2024|  end
                           
