package com.newgen.iforms.user.config;

public interface Constants {

	//CONTROL NAMES
	public static final String WI_NAME = "WI_NAME";
	public static final String CONTACT_CENTER_TEAM = "Contact Center Team";
	//PROCEDURE CALL
	public static final String PARAM_TEXT = "Text :";
	// LOGGER
//	public static final String FOLDER_CONFIG = "ProcessLoggerConfig";
	public static final String FOLDER_CONFIG = "NGConfig";
	public static final String FILE_LOG4J_PROPERTIES = "log4j.properties";
	// EVENT TYPE
	public static final String EVENT_TYPE_LOAD = "load";
	public static final String EVENT_TYPE_CLICK = "click";
	public static final String EVENT_TYPE_CHANGE = "change";
	public static final String EVENT_TYPE_LOSTFOCUS = "blur";
	public static final String EVENT_TYPE_GOTFOCUS = "focus";
	public static final String CONTROL_NAME_FORM = "form";
	public static final String TOTAL_RETRIEVED = "Total_Retrieved";
	public static final String ROW = "Row";
	public static final String DATA = "Data";
	public static final String SAVE_TAB_CLICK = "saveTabClick";
	//BOOLEAN
	public static final String TRUE = "true";
	public static final String FALSE = "false";
	public static final String ENABLE = "enable";
	public static final String DISABLE = "disable";
	public static final String VISIBLE = "visible";
	//ACTIVITY NAMES
	public static final String ACTIVITY_DDE_CUST_INFO = "DDE_Cust_Info";
	public static final String ACTIVITY_DDE_ACCOUNT_INFO = "DDE_Account_Info";
	public static final String ACTIVITY_DDE_ACCOUNT_INFO_CHECK = "DDE_Acc_Info_Chk";
	public static final String ACTIVITY_QDE_CUST_INFO = "QDE_Cust_Info";
	public static final String ACTIVITY_QDE_ACCOUNT_INFO = "QDE_Account_Info";
	public static final String ACTIVITY_QDE_ACCOUNT_INFO_CHECK ="QDE_Acc_Info_Chk";
	public static final String ACTIVITY_INTRODUCTION = "Introduction";
	public static final String ACTIVITY_ACCOUNT_RELATION = "Account_Relation";
	public static final String ACTIVITY_CONTACT_CENTER = "Contact Center Team";
	public static final String ACTIVITY_APP_ASSESSMENT = "Application_Assessment";
	public static final String ACTIVITY_CUST_SCREEN = "Customer_Screen";
	public static final String ACTIVITY_CUST_SCREEN_QDE = "Customer_Screen_QDE";
	public static final String ACTIVITY_CPD_MAKER = "CPD Maker";
	public static final String ACTIVITY_CPD_CHECKER = "CPD Checker";
	public static final String ACTIVITY_CONTACT_CENTER_CPD = "Contact_Center_CPD";
	public static final String ACTIVITY_LEVEL_11 = "Level1 Approved";
	public static final String ACTIVITY_LEVEL_12 = "Level2 Approved";
	public static final String ACTIVITY_LEVEL_13 = "Level3 Approved";
	public static final String ACTIVITY_LEVEL_14 = "Level4 Approved";
	public static final String ACTIVITY_CLOSE_REQUEST = "Close Request";
	public static final String ACTIVITY_RM = "RM";
	public static final String ACTIVITY_WORK_EXIT = "Work Exit1";
	public static final String ACTIVITY_QUERY = "Query1";
	public static final String ACTIVITY_MAIL_ROOM = "MailRoomOperation";
	public static final String ACTIVITY_BULK_EOD_CHECKER = "Bulk EOD Checker";
	public static final String ACTIVITY_DELIVERY_MAKER = "Delivery_Maker";
	public static final String ACTIVITY_DELIVERY_CHECKER = "Delivery_Checker";
	public static final String ACTIVITY_PHYSICAL_RECON = "Physical Reconciliation";
	public static final String ACTIVITY_COMP_APP = "Compliance Approver";
	public static final String ACTIVITY_PROD_APP = "Product Approver";
	public static final String ACTIVITY_PROD_APP_CPD = "Product_Approver_CPD";
	public static final String ACTIVITY_FB_MAKER = "FB_Maker";
	public static final String ACTIVITY_FB_CHECKER = "FB_Checker";
	public static final String ACTIVITY_PBG_VIGILANCE = "PBG Vigilance"; // Gurwinder PBG Vigilance Chnage 27062023
	//table name
	public static String sExtTable = "EXT_AO";
	public static String PROD_SEC_EXIST_CPD_LVW = "PROD_SEC_EXIST_CPD_LVW"; 
	public static String FAC_EXST_LVW_CPD = "FAC_EXST_LVW_CPD"; 
	public static String ELIG_LVW_CPD = "ELIG_LVW_CPD";
	public static String sAuditTable = "USR_0_AO_SEARCH_AUDIT";
	//Introduction
	public static String PREV_WS_NAME = "PREV_WS_NAME";
	public static String SUBMIT = "SUBMIT";
	public static String BTN_SAVE_NEXT = "BTN_SAVE_NEXT";
	public static String REQUEST_TYPE = "REQUEST_TYPE";
	public static String WMS_ID = "WMS_ID";
	public static String SOURCING_CHANNEL = "SOURCING_CHANNEL";
	public static String ACC_HOME_BRANCH = "ACC_HOME_BRANCH";
	public static String DATA_ENTRY_MODE = "DATA_ENTRY_MODE";
	public static String FORM_AUTO_GENERATE = "FORM_AUTO_GENERATE";
	public static String ACC_OWN_TYPE = "ACC_OWN_TYPE";
	public static String ACC_CLASS = "ACC_CLASS";
	public static String REASON = "REASON";
	public static String DATEFORMAT = "dd/MM/yyyy";
	public static String fCUBSSystem="FCUBS";
	public static String sDedupeTable = "USR_0_DUPLICATE_SEARCH_DATA";
	public static String cBGSystem="CBG";
	public static String lapsSystem="LAPS";
	public static String sCBGQuery="INSERT INTO "+sAuditTable+" (CUST_ID,cust_IC, cust_full_name, cust_pass_no, cust_nationality,cust_email, cust_mobile_no, cust_dob, eida_no, memo_severity , memo , system_type , wI_NAme ) select CUSTOMER_ID,'',CUSTOMER_FULL_NAME, passport_number, passport_nationality, customer_email, customer_mobile_no, passport_dob_date, eida_number,'','','FCUBS','00099' FROM EXT_CBG_CUST_ONBOARDING";
	public static String sFCUBQuery="";
	public static String sExternalTable = "EXT_AO";
	public static String sECBDefMasterTable = "USR_0_ECB_DEFAULT_MASTER";
	public static String chqbookValidationTable = "CHQBOOKVALIDATIONDATA";
	public static String ECBValidationGrid = "ECB_VALIDATION_GRID";
	public static String BTN_EIDA_INFO = "BTN_EIDA_INFO";
	public static String BTN_ADD_CUST_INFO = "BTN_ADD_CUST_INFO";
	public static String BTN_FETCH_EIDA_INFO = "BTN_FETCH_EIDA_INFO";//command8
	public static String BTN_SEARCH_CUSTOMER = "BTN_SEARCH_CUSTOMER"; //command9
	public static String SEARCH_DETAILS_LVW = "SEARCH_DETAILS_LVW"; //listvew_srch_fcr
	public static String SEARCH_CID = "SEARCH_CID"; //cid1
	public static String SEARCH_EIDA_CARD_NO = "SEARCH_EIDA_CARD_NO"; //eida_card_no
	public static String SEARCH_PASS_NO = "SEARCH_PASS_NO"; //combo4
	public static String SEARCH_MOB_NO = "SEARCH_MOB_NO";  //mobile1
	public static String SEARCH_DOB = "SEARCH_DOB"; //dob1
	public static String SEARCH_ADD_EIDA_INFO = "SEARCH_ADD_EIDA_INFO";
	public static String SEARCH_NATIONALITY ="SEARCH_NATIONALITY";  //srch_nation	
	public static String BTN_SEARCH_CLEAR = "BTN_SEARCH_CLEAR"; //command10
	public static String SEARCH_ADD_CUST_INFO = "SEARCH_ADD_CUST_INFO";  //command21
	public static String BTN_ADD_EIDA_INFO = "BTN_ADD_EIDA_INFO"; //command29
	public static String SEARCH_DETAILS_LISTVIEW = "SEARCH_DETAILS_LISTVIEW";
	public static String NEW_CUST_EIDA_DETAILS = "NEW_CUST_EIDA_DETAILS";
	public static String NEW_CUST_NAME = "NEW_CUST_NAME"; //text4
	public static String NEW_CUST_DOB = "NEW_CUST_DOB";  //mask1
	public static String NEW_CUST_NATIONALITY = "NEW_CUST_NATIONALITY"; //MAN_NATIONALITY
	public static String BTN_ADD_MANUALLY = "NEW_CUST_ADD_MANUALLY"; //command4 
	public static String ACC_RELATION = "acc_relation"; //acc_relation lvw
	public static String LISTVIEW_DECISION = "listview_decision";
	public static String TXT_DOB = "TXT_DOB";
	public static String TXT_CUSTOMERID = "TXT_CUSTOMERID";
	public static String HD_EMAIL = "HD_EMAIL"; 
	public static String HD_NAME = "HD_NAME";  //COMBO16
	public static String HD_CUST_IC = "HD_CUST_IC";
	public static String EIDA_DETAILS = "eida_details";
	public static String CHANNEL_TYPE = "CHANNEL_TYPE";
	public static String HD_DEBIT_NO = "HD_DEBIT_NO";
	public static String HD_CREDIT_NO = "HD_CREDIT_NO";
	public static String SCAN_MODE = "SCAN_MODE";
	public static String NEW_CUST_FETCH_EIDA = "NEW_CUST_FETCH_EIDA";
	public static String ONCLICKTAB1 = "onClickTab1";
	public static String TABCLICK = "TABCLICK";
	public static String OPERATING_INST = "OPERATING_INST";
	public static String TABLE33_BANK_RELATION = "table33_bank_relation";
	public static String TABLE33_ACC_RELATION = "table33_acc_relation";
	public static String ACCRELGRIDCOLNAMES = "SNO,NAME,CID,MOBILE,EIDANO,DOB,NATIONALITY,BANKREL,CUSTREL,ACCTREL,SEARCHTYPE,WI_NAME,EMAIL";
	public static String[] ARSETFIELDSBLANK = {HD_NAME,SEARCH_CID,HD_CUST_IC,SEARCH_PASS_NO,HD_EMAIL,SEARCH_MOB_NO,SEARCH_NATIONALITY,SEARCH_DOB,HD_DEBIT_NO,HD_CREDIT_NO,NEW_CUST_NAME,NEW_CUST_NATIONALITY,NEW_CUST_DOB};
	public static String[] SHOWCTRLSFCRSERCUSTDET = {HD_NAME,SEARCH_CID,HD_CUST_IC,SEARCH_PASS_NO,HD_EMAIL,SEARCH_MOB_NO,SEARCH_NATIONALITY,SEARCH_DOB,HD_DEBIT_NO,HD_CREDIT_NO};
	public static String[] ENBCTRLSFCRSERCUSTDET = {HD_NAME,SEARCH_CID,HD_CUST_IC,SEARCH_MOB_NO,SEARCH_PASS_NO,HD_EMAIL,SEARCH_DOB};
	public static String[] SHOWCTRLSFCRSERCCDC = {HD_NAME,SEARCH_CID,HD_CUST_IC,SEARCH_PASS_NO,HD_EMAIL,SEARCH_MOB_NO,SEARCH_NATIONALITY,SEARCH_DOB,HD_DEBIT_NO,HD_CREDIT_NO};
	public static String[] SHOWFCRSERFIELDS = {HD_NAME,SEARCH_CID,HD_CUST_IC,SEARCH_PASS_NO,HD_EMAIL,SEARCH_MOB_NO,SEARCH_NATIONALITY,SEARCH_DOB,HD_DEBIT_NO,HD_CREDIT_NO};
	public static String[] BTNSERBLANKFIELDS = {SEARCH_EIDA_CARD_NO,HD_NAME,HD_EMAIL,SEARCH_CID,SEARCH_MOB_NO,HD_CUST_IC,SEARCH_DOB,HD_DEBIT_NO,HD_CREDIT_NO,SEARCH_PASS_NO,NEW_CUST_NAME,NEW_CUST_DOB,SEARCH_NATIONALITY,NEW_CUST_NATIONALITY};
	public static String[] BTNADDCUSTINFOFIELDSDIS = {NEW_CUST_NAME,NEW_CUST_DOB,NEW_CUST_NATIONALITY};
	public static String[] BTNADDCUSTINFOBTNSHIDE = {BTN_ADD_EIDA_INFO,BTN_ADD_MANUALLY};
	public static String[] BTNADDEIDAINFOFIELDSDIS= {NEW_CUST_NAME,NEW_CUST_DOB,NEW_CUST_NATIONALITY};
	public static String[] BTNADDEIDAINFOBTNSHIDE = {BTN_ADD_EIDA_INFO,BTN_ADD_MANUALLY};
	//CCT fields
	public static String BTNPROFESSION = "BTNPROFESSION";
	public static String BTNEMLOYERNAME = "BTNEMLOYERNAME";
	public static String CRS_FIRSTNAME = "CRS_FirstName";
	public static String CRS_LASTNAME = "CRS_LastName";
	public static String CHK_PASSPORT_DET = "CHK_PASSPORT_DET";
	public static String CHK_EDD = "chk_edd";
	public static String RISK_ASSESS_LVW = "RISK_ASSESS_LVW";
	public static String ELIG_LVW_CRO = "ELIG_LVW_CRO";
	public static String PROD_CRO_LVW = "PROD_CRO_LVW";
	public static String PROD_CPD_LVW = "PROD_CPD_LVW";
	public static String PROD_OFRD_CRO_LVW = "PROD_OFRD_CRO_LVW";
	public static String PROD_OFRD_CPD_LVW = "PROD_OFRD_CPD_LVW";
	public static String FAC_OFRD_LVW_CRO = "FAC_OFRD_LVW_CRO";
	public static String DOC_REQ_QUEUE = "doc_req_queue";
	public static String BTN_DOC = "BTN_DOC";
	public static String FAC_OFRD_LVW_CPD = "FAC_OFRD_LVW_CPD";
	public static String PROD_SEC_OFRD_CPD_LVW = "PROD_SEC_OFRD_CPD_LVW";
	public static String SEC_RISK_ASSESS_LVW = "SEC_RISK_ASSESS_LVW";
	public static String FAC_LVW_CPD = "FAC_LVW_CPD";
	public static String CRO_FD = "FD";
	public static String PRE_APP_CREDIT_CARD = "PRE_APP_CREDIT_CARD";
	public static String OVERDRAFT = "OVERDRAFT";
	public static String ACC_INFO_EDC_LVW = "ACC_INFO_EDC_LVW";
	public static String SEC_RISK_ASSESS_CPD_LVW = "SEC_RISK_ASSESS_CPD_LVW";
	public static String BUTTON_SUBMIT  = "btnSubmit";
	public static String TXT_CURRWS = "TXT_CURRWS";
	public static String  PD_DOB = "PD_DOB";
	public static String HD_VISA_NO  = "HD_VISA_NO";
	public static String HD_PASSPORT_NO  = "HD_PASSPORT_NO ";
	public static String HD_EXP_DATE  = "HD_EXP_DATE";
	public static String HD_VISA_ISSUE_DATE = "HD_VISA_ISSUE_DATE";
	public static String PD_ANY_CHNG_CUST_INFO = "PD_ANY_CHNG_CUST_INFO"; 
	public static String PD_CUSTSEGMENT2 = "PD_CUSTSEGMENT2";
	public static String HD_FCR_SEARCH = "HD_FCR_SEARCH";
	public static String NOM_REQ = "NOM_REQ";
	public static String EXISTING_NOM_PRSN = "EXISTING_NOM_PRSN";
	public static String BRNCH_OF_INSTANT_ISSUE ="BRNCH_OF_INSTANT_ISSUE";
	public static String DEL_NAME = "DEL_NAME";
	public static String DEL_PO_BOX = "DEL_PO_BOX";
	public static String DEL_ADDRESS = "DEL_ADDRESS";
	public static String DEL_CITY = "DEL_CITY";
	public static String DEL_LANDMARK = "DEL_LANDMARK";
	public static String DEL_STATE = "DEL_STATE";
	public static String DEL_STATE_OTHER = "DEL_STATE_OTHER";
	public static String DEL_CNTRY = "DEL_CNTRY";
	public static String DEL_FAX = "DEL_FAX";
	public static String DEL_ZIP_CODE = "DEL_ZIP_CODE";
	public static String DEL_EMAIL = "DEL_EMAIL";
	public static String DEL_PREF_LANG = "DEL_PREF_LANG";
	public static String DEL_PH = "DEL_PH";
	public static String DEL_MOBILE = "DEL_MOBILE";
	public static String DEL_DELIVERY_MODE = "DEL_DELIVERY_MODE";
	public static String DELIVERY_MODE = "DELIVERY_MODE";
	public static String DEL_EXISTING_ADD = "DEL_EXISTING_ADD";
	public static String RD_INST_DEL = "RD_INST_DEL";
	public static String NEW_DEL_MODE = "new_del_mode";
	public static String CHANNEL_NAME = "channel_name";
	public static String DFC_STATIONERY_AVAIL = "DFC_STATIONERY_AVAIL";
	public static String FETCH_INFO = "FETCH_INFO";
	public static String skipUAEPass = "table114_Deceased";
	public static String Frame48 = "Frame48";
	public static String INSTANT_DEL_NO = "INSTANT_DEL_NO";
	public static String INSTANT_DEL_YES = "INSTANT_DEL_YES";
	public static String DATE_FORMAT = "";
	public static String [] DELIVERY_FIELD = {INSTANT_DEL_YES,INSTANT_DEL_NO};
	public static String [] FRAME_DELIVERY_FIELDS = {FETCH_INFO,DFC_STATIONERY_AVAIL,CHANNEL_NAME,NEW_DEL_MODE,DEL_EXISTING_ADD,DEL_DELIVERY_MODE,DEL_MOBILE,DEL_PH,DEL_PREF_LANG,DEL_EMAIL,DEL_ZIP_CODE,DEL_FAX,DEL_CNTRY,DEL_STATE_OTHER,DEL_STATE,DEL_LANDMARK,DEL_CITY,DEL_ADDRESS,DEL_PO_BOX,DEL_NAME,NOM_REQ ,EXISTING_NOM_PRSN,BRNCH_OF_INSTANT_ISSUE,BRNCH_OF_INSTANT_ISSUE};
	public static String [] DISABLE_FRAME_DELIVERY = {Frame48,FETCH_INFO,DFC_STATIONERY_AVAIL,CHANNEL_NAME,NEW_DEL_MODE,RD_INST_DEL,DEL_DELIVERY_MODE,DEL_MOBILE,DEL_PH,DEL_PREF_LANG,DEL_EMAIL,DEL_ZIP_CODE,DEL_FAX,DEL_CNTRY,DEL_STATE_OTHER,DEL_STATE,DEL_CITY,DEL_LANDMARK,DEL_ADDRESS,DEL_PO_BOX,DEL_NAME,BRNCH_OF_INSTANT_ISSUE,EXISTING_NOM_PRSN,INSTANT_DEL_NO,NOM_REQ,INSTANT_DEL_YES};
	public static String [] DISABLE_FRAME_DELIVERY2 ={NEW_DEL_MODE,CHANNEL_NAME,RD_INST_DEL,DEL_EXISTING_ADD,DEL_DELIVERY_MODE,DEL_MOBILE,DEL_PH,DEL_PREF_LANG,DEL_EMAIL,DEL_ZIP_CODE,DEL_FAX,DEL_CNTRY,DEL_STATE_OTHER,DEL_STATE,DEL_CITY,DEL_LANDMARK,DEL_ADDRESS,DEL_PO_BOX,DEL_NAME,BRNCH_OF_INSTANT_ISSUE,EXISTING_NOM_PRSN};
	
	public static String ACC_TITLE = "ACC_TITLE";
	public static String BUTTON_GENERATE_TEMPLATE = "BUTTON_GENERATE_TEMPLATE";
	public static String REF_BY_STAFF = "REF_BY_STAFF";
	public static String STAFF_REFER_BTN = "STAFF_REFER_BTN";
	public static String PRO_CODE = "pro_code";
	public static String EXCELLENCY_CNTR = "excellency_cntr";
	public static String RM_CODE = "rm_code";
	public static String RM_NAME = "rm_name";
	public static String OTHERS = "OTHERS";
	public static String BTNRMNAME = "BTNRMNAME";
	public static String BTNRMCODE = "BTNRMCODE";
	public static String BTN_RM_CODE = "BTN_RM_CODE";
	public static String BTN_RM_NAME = "BTN_RM_NAME";
	public static String CUST_NATIONALITY = "cust_nationality";
	public static String CUST_GENDER = "cust_gender";
	public static String DRP_RESEIDA = "drp_reseida";
	public static String CUST_PREFIX = "cust_prefix";
	public static String MARITAL_STATUS = "marital_status";
	public static String PROF_CODE  = "prof_code";
	public static String RELIGION = "religion";
	public static String HD_PASS_EXP_DATE  = "HD_PASS_EXP_DATE";
	public static String HD_PASS_ISS_DATE  = "HD_PASS_ISS_DATE";
	public static String HD_PASS_TYPE  = "HD_PASS_TYPE";
	public static String HD_VISA_STATUS  = "HD_VISA_STATUS";
	public static String HD_ONE = "HD_ONE";
	public static String HD_TWO = "HD_TWO";
	//APPLICATION ASSESSMENT CRO TAB
	public static String SEC_RISK_ASSESS_CRO = "SEC_RISK_ASSESS_CRO";
	public static String SEC_ELIG_ANALYSIS_CRO = "SEC_ELIG_ANALYSIS_CRO";
	public static String SEC_PRODUCTION_CRO = "SEC_PRODUCTION_CRO";
	public static String SEC_OPT_PROD_CRO = "SEC_OPT_PROD_CRO";
	public static String SEC_FACILITY_CRO = "SEC_FACILITY_CRO";
	public static String FAC_LVW_CRO = "FAC_LVW_CRO";
	public static String FAC_EXST_LVW_CRO = "FAC_EXST_LVW_CRO";
	public static String SEC_DOC_REQ_CRO = "SEC_DOC_REQ_CRO";
	public static String BTN_DOC_CPD = "BTN_DOC_CPD";
	//Application Assessment CPD Tab
	public static String SEC_RISK_ASSESS_CPD = "SEC_RISK_ASSESS_CPD";
	public static String SEC_ELIG_ANALYSIS_CPD ="SEC_ELIG_ANALYSIS_CPD";
	public static String SEC_PRODUCTION_CPD ="SEC_PRODUCTION_CPD";
	public static String SEC_OPT_PROD_CPD ="SEC_OPT_PROD_CPD";
	public static String SEC_FACILITY_CPD ="SEC_FACILITY_CPD";
	public static String SEC_DOC_REQ_CPD ="SEC_DOC_REQ_CPD";
	//Account Tab
	public static String SEC_ACC_INFO_PD = "SEC_ACC_INFO_PD";
	public static String SEC_ACC_INFO_ECD = "SEC_ACC_INFO_ECD";
	public static String ACC_INFO_PD_LVW = "ACC_INFO_PD_LVW";
	public static String SEC_ACC_INFO_AOR_MAKER = "SEC_ACC_INFO_AOR_MAKER";
	public static String BTN_ECD_VALIDATE = "BTN_ECD_VALIDATE";
	public static String ACC_INFO_UDF_FIELD = "ACC_INFO_UDF_FIELD";
	public static String ACC_INFO_UDF_VALUE = "ACC_INFO_UDF_VALUE";
	public static String SEC_ACC_INFO_DCL = "SEC_ACC_INFO_DCL";
	public static String FAMILY_REFFERED = "AO_FAMILY_REFFERED";
	public static String SOURCE_NAME = "SOURCE_NAME";
	public static String SOURCE_CODE = "SOURCE_CODE";
	public static String MAKER_NAME = "MAKER_NAME";
	public static String MAKER_CODE = "MAKER_CODE";
	public static String CHECKER_NAME = "CHECKER_NAME";
	public static String CHECKER_CODE = "CHECKER_CODE";
	public static String MAKER_DEPT = "MAKER_DEPT";
	public static String UDF_CODE = "UDF_CODE";
	public static String AI_DEPARTMENT = "AI_DEPARTMENT";
	public static String ACCINFO_UDF_LIST = "AccInfo_UdfList";
	public static String EXISTING_ETIHAD_CUST = "EXISTING_ETIHAD_CUST";
	
	public static String ETIHAD_NO = "ETIHAD_NO";
	public static String SRCH_NATION = "srch_nation";
	public static String DEBIT_CARD_CHK = "DEBIT_CARD_CHK";
	public static String GROUP_TYPE = "GROUP_TYPE";
	public static String NEW_LINK = "NEW_LINK";
	public static String EXISTING_CARD_NO = "EXISTING_CARD_NO";
	public static String CARD_TYPE = "CARD_TYPE";
	public static String EMBOSS_NAME = "EMBOSS_NAME";
	public static String DC_BTN_REMOVE = "DC_BTN_REMOVE";
	public static String QUEUE_DC = "queue_dc";
	public static String BTN_GEN_TEMPLATE = "btn_generate_template";
	public static String SEC_CONTACT_DETAILS = "SEC_CONTACT_DET_RA,SEC_CONTACT_DET_PA,SEC_CONTACT_DET_CP";//Frame20
	public static String INTERNAL_DETAIL_SECTION = "INTERNAL_DETAIL_SECTION";
	
	public static String DC_BTN_ADD= "DC_BTN_ADD";
	public static String ADD_PRODUCT = "add_product";
	public static String REMOVE_PRODUCT = "remove_product";
	
	public static String PRODUCT_QUEUE = "product_queue";
	public static String ACC_INFO_PG = "ACC_INFO_PG";
	public static String ACC_INFO_DC_LVW = "ACC_INFO_DC_LVW";
	public static String BTN_ACC_INFO_GEN_TEMP = "BTN_ACC_INFO_GEN_TEMP";
	//Optional Product Tab
	public static String SEC_OPT_OND = "SEC_OPT_OND";
	public static String SEC_OPT_MI = "SEC_OPT_MI";
	public static String SEC_OPT_OI = "SEC_OPT_OI";
	public static String SEC_OPT_PROD = "SEC_OPT_PROD";
	//Delivery Instruction
	public static String DI_CODE = "DI_CODE";
	public static String SEC_DEL_ADD = "SEC_DEL_ADD";
	public static String CT_BTN_EIDA_REFRESH = "CT_BTN_EIDA_REFRESH";
	//Family Banking Tab
	public static String CID_HOF = "CID_HOF";
	public static String CID_FAMILY_GROUP = "CID_FAMILY_GROUP";
	public static String RM_HOF = "RM_HOF";
	public static String RM_STRUCTURE = "RM_STRUCTURE";
	//Category Change
	public static String SEC_CAT_CHNG = "SEC_CAT_CHNG";
	public static String SEC_INTERNAL_DETL = "SEC_INTERNAL_DETL";
	public static String NEW_RM_CODE_CAT_CHANGE = "NEW_RM_CODE_CAT_CHANGE"; 
	public static String BTN_RM_CODE_CAT_CHANGE = "BTN_RM_CODE_CAT_CHANGE";
	public static String NEW_RM_NAME_CAT_CHANGE = "NEW_RM_NAME_CAT_CHANGE";
	public static String BTN_RM_NAME_CAT_CHANGE = "BTN_RM_NAME_CAT_CHANGE";
	public static String OLD_RM_CODE_CAT_CHANGE = "OLD_RM_CODE_CAT_CHANGE";
	public static String OLD_RM_NAME_CAT_CHANGE = "OLD_RM_NAME_CAT_CHANGE";
	public static String OLD_CUST_SEGMENT = "OLD_CUST_SEGMENT";
	public static String NEW_CUST_SEGMENT = "NEW_CUST_SEGMENT";
	public static String PROMO_CODE_CAT_CHANGE = "PROMO_CODE_CAT_CHANGE";
	public static String EXCELLENCY_CENTER_CC = "EXCELLENCY_CENTER_CC";
	public static String RD_MEMBRSHP_WITH = "RD_MEMBRSHP_WITH";
	public static String RD_PVLDGE_CLUB = "RD_PVLDGE_CLUB";
	public static String RD_BENEFITS = "RD_BENEFITS";
	public static String RD_OTHERS = "RD_OTHERS";
	public static String SOURCE_NAME_CAT_CHANGE = "SOURCE_NAME_CAT_CHANGE";
	public static String SOURCE_CODE_CAT_CHANGE = "SOURCE_CODE_CAT_CHANGE";
	public static String MAKER_NAME_CAT_CHANGE = "MAKER_NAME_CAT_CHANGE";
	public static String MAKER_CODE_CAT_CHANGE = "MAKER_CODE_CAT_CHANGE";
	public static String MAKER_DEPARMENT_CAT_CHANGE = "MAKER_DEPARMENT_CAT_CHANGE";
	public static String MAKER_UDF_CAT_CHANGE = "MAKER_UDF_CAT_CHANGE";
	public static String CHECKER_NAME_CAT_CHANGE = "CHECKER_NAME_CAT_CHANGE";
	public static String CHECKER_CODE_CAT_CHANGE = "CHECKER_CODE_CAT_CHANGE";
	public static String CHECKER_DEPARMENT_CAT_CHANGE = "CHECKER_DEPARMENT_CAT_CHANGE";
	public static String LAST_CAT_CAHNGE_DATE= "LAST_CAT_CAHNGE_DATE";
	public static String BTN_CC_GEN_TEMP = "BTN_CC_GEN_TEMP";
	public static String SEC_CC_AORM = "SEC_CC_AORM";
	public static String BTN_CC_CODE = "BTN_CC_CODE";
	public static String BTN_CC_SRC = "BTN_CC_SRC";
	public static String SEC_CC_AORC = "SEC_CC_AORC";
	public static String RMCode = "RMCode";
	public static String SEC_FB = "SEC_FB";
	public static String FB_FULL_CUST_NAME = "FB_FULL_CUST_NAME";
	public static String HOF_RELATIONSHIP = "HOF_RELATIONSHIP";
	public static String HOF_CUSTOMER_SEGMENT = "HOF_CUSTOMER_SEGMENT";
	public static String HOF_RM_CODE = "HOF_RM_CODE";
	//Standing Instructions
	public static String SEC_SI = "SEC_SI";
	public static String PROD_COMBO = "prod_combo";
	public static String SI_PRODUCT = "SI_PRODUCT";
	public static String SEC_SI_SIRFT = "SEC_SI_SIRFT";
	public static String SI_DEB_ACC_NO = "SI_DEB_ACC_NO";
	public static String SI_CURRENCY = "SI_CURRENCY";
	public static String SI_CRED_PROD = "SI_CRED_PROD";
	public static String SI_FRST_PAYMNT = "SI_FRST_PAYMNT";
	public static String SI_LST_PAYMNT = "SI_LST_PAYMNT";
	public static String SI_PERIOD = "SI_PERIOD";
	public static String SI_TRNS_AMT = "SI_TRNS_AMT";
	public static String BTN_SI_ADD = "BTN_SI_ADD";
	public static String BTN_SI_MOD = "BTN_SI_MOD";
	public static String BTN_SI_DEL = "BTN_SI_DEL";
	public static String STND_INST_LVW = "STND_INST_LVW";
	public static String SEC_SI_SWP = "SEC_SI_SWP";
	public static String SWP_OUT_TRNS = "SWP_OUT_TRNS";
	public static String SWP_OUT_DEB_ACC_NO = "SWP_OUT_DEB_ACC_NO";
	public static String SWP_OUT_CRED_ACC_NO = "SWP_OUT_CRED_ACC_NO";
	public static String SWP_OUT_CURRENCY = "SWP_OUT_CURRENCY";
	public static String SWP_OUT_AMT_ABV = "SWP_OUT_AMT_ABV";
	public static String SWP_OUT_ABV_AMT = "SWP_OUT_ABV_AMT";
	public static String SWP_IN_TRNS = "SWP_IN_TRNS";
	public static String SWP_IN_DEB_ACC_NO = "SWP_IN_DEB_ACC_NO";
	public static String SWP_IN_CRED_ACC_NO = "SWP_IN_CRED_ACC_NO";
	public static String SWP_IN_CURRENCY = "SWP_IN_CURRENCY";
	public static String SWP_IN_AMT_ABV = "SWP_IN_AMT_ABV";
	//Compliance
	public static String NEG_INFO = "NEG_INFO";
	public static String NEG_AXPLAIN = "NEG_AXPLAIN";
	public static String FATF = "FATF";
	public static String FATF_EXPLAIN = "FATF_EXPLAIN";
	public static String KYC = "KYC";
	public static String KYC_AXPLAIN = "KYC_AXPLAIN";
	//ECB Validation
	public static String BTN_ECB_REFRSH = "BTN_ECB_REFRSH";
	public static String ECB_VALIDATION_LVW = "ECB_VALIDATION_LVW";
	public static String SEC_DECISION_SD = "SEC_DECISION_SD";
	public static String SEC_DECISION_LAST = "SEC_DECISION_LAST";
	public static String BTN_LAST_DEC = "BTN_LAST_DEC";
	public static String CHQ_ELIGIBILITY = "CHQ_ELIGIBILITY";
	public static String DECISION_LVW = "DECISION_LVW";
	//Customer Tab
	public static String LVW_DEDUPE_RESULT = "LVW_DEDUPE_RESULT";
	public static String BTN_DEDUPE_SEARCH = "BTN_DEDUPE_SEARCH";
	public static String BTN_SELECT_CUST = "BTN_SELECT_CUST";
	//Decision
	public static String SEC_DEC = "SEC_DEC";
	public static String IS_COMPLIANCE_NAME_SCR = "IS_COMPLIANCE_NAME_SCR";
	public static String IS_COMPLIANCE_RISK_ASSESS = "IS_COMPLIANCE_RISK_ASSESS";
	public static String IS_PROD_APP_REQ = "IS_PROD_APP_REQ";
	public static String IS_CALL_BACK_REQ = "IS_CALL_BACK_REQ";
	public static String L1_APP_REQ = "L1_APP_REQ";
	public static String L2_APP_REQ = "L2_APP_REQ";
	public static String L3_APP_REQ = "L3_APP_REQ";
	public static String L4_APP_REQ = "L4_APP_REQ";
	public static String DOC_APPROVAL_OBTAINED = "DOC_APPROVAL_OBTAINED";
	public static String COURT_ORD_TRADE_LIC = "COURT_ORD_TRADE_LIC";
	public static String CRO_DEC = "CRO_DEC";
	public static String CRO_REJ_REASON = "CRO_REJ_REASON";
	public static String CRO_REMARKS = "CRO_REMARKS";
	public static String STAFF_ID = "STAFF_ID";
	public static String DELIVERY_DATE = "DELIVERY_DATE";
	public static String BTN_DEC_STAFF = "BTN_DEC_STAFF";
	public static String CHUBB = "CHUBB";
	public static String RACK = "RACK";
	public static String BTN_GENERATETEMP = "BTN_GENERATETEMP";
	public static String BUTTON_REFRESH = "BUTTON_REFRESH";
	public static String BUTTON_RETRY = "BUTTON_RETRY";
	public static String BTN_DOCUMENT_LINK = "document_link_button";
	//FCR
	public static String ESTATEMENT_FLAG = "ESTATEMENT_FLAG";
	public static String FCR_RISK = "FCR_RISK"; 
	public static String CHECKFCR = "CHECKBOX_COUNTRY_RES_FCR"; 
	public static String CHECKEIDA = "CHECKBOX_COUNTRY_RES_EIDA"; 
	public static String CHECKMANUAL = "CHECKBOX_COUNTRY_RES_MANUAL"; 
	public static String FCR_SHORTNAME = "ShortName_FCR";
	public static String FCR_PREFIX  ="prefix_fcr";
	public static String FCR_FIRSTNAME ="firstname_fcr";
	public static String FCR_LASTNAME  ="lastname_fcr";
	public static String FCR_NAME= "name_fcr";
	public static String FCR_MOTHERSNAME= "mothersname_fcr";
	public static String FCR_EIDANO= "eidano_fcr";
	public static String FCR_ADDRESS="address_fcr";
	public static String FCR_CNTRY = "cntry_fcr";
	public static String FCR_STATE = "state_fcr";
	public static String FCR_CITY = "city_fcr";
	public static String CHECKBOX_SELECTALL_FCR = "CHECKBOX_SELECTALL_FCR";
	public static String CHECKBOX_PREFIX_FCR = "CHECKBOX_PREFIX_FCR";
	public static String CHECKBOX_FIRSTNAME_FCR= "CHECKBOX_FIRSTNAME_FCR";
	public static String CHECKBOX_LASTNAME_FCR = "CHECKBOX_LASTNAME_FCR";
	public static String CHECKBOX_FULLNAME_FCR = "CHECKBOX_FULLNAME_FCR";
	public static String CHECKBOX_SHORTNAME_FCR = "CHECKBOX_SHORTNAME_FCR";
	public static String CHECKBOX_MOTHERSNAME_FCR = "CHECKBOX_MOTHERSNAME_FCR";
	public static String CHECKBOX_EIDANO_FCR = "CHECKBOX_EIDANO_FCR";
	public static String CHECKBOX_CORR_POB_FCR = "CHECKBOX_CORR_POB_FCR";
	public static String CHECKBOX_CNTRY_OF_CORR_FCR	= "CHECKBOX_CNTRY_OF_CORR_FCR";
	public static String CHECKBOX_STATE_FCR	= "CHECKBOX_STATE_FCR";	
	public static String CHECKBOX_CITY_FCR = "CHECKBOX_CITY_FCR";
	public static String FCR_RESIDENT="Resident_FCR";
	public static String FCR_PER_CNTRY="per_cntry_fcr";
	public static String FCR_PH="ph_fcr";
	public static String FCR_MOBILE="mobile_fcr";
	public static String FCR_EMAIL="email_fcr";
	public static String FCR_DOB="dob_fcr";
	public static String FCR_PASSPORTNO="passportno_fcr";
	public static String FCR_PASSPORTISSDATE="passportissdate_fcr";
	public static String FCR_PASSPORTEXPDATE="passportexpdate_fcr";
	public static String FCR_PASSTYPE="passtype_fcr";
	public static String FCR_NATIONALITY="nationality_fcr";
	public static String FCR_COUNTRYBIRTH="countryBirth_fcr";
	public static String FCR_VISANO="visano_fcr";
	public static String FCR_VISASTATUS="visaStatus_fcr";
	public static String FCR_VISAISSDATE="visaissdate_fcr";
	public static String FCR_VISAEXPDATE="visaexpdate_fcr";
	public static String FCR_PROFESSION="profession_fcr";
	public static String FCR_GENDER="gender_fcr";
	public static String FCR_EMPLYR_NAME="emplyr_name_fcr";
	public static String CHECKBOX_PASSPORT_TYPE_FCR = "CHECKBOX_PASSPORT_TYPE_FCR";
	public static String CHECKBOX_NATIONALITY_FCR = "CHECKBOX_NATIONALITY_FCR";
	public static String CHECKBOX_COB_FCR = "CHECKBOX_COB_FCR";
	public static String CHECKBOX_COUNTRY_RES_FCR = "CHECKBOX_COUNTRY_RES_FCR";
	public static String CHECKBOX_COUNTRY_PER_RES_FCR = "CHECKBOX_COUNTRY_PER_RES_FCR";
	public static String CHECKBOX_TELE_RES_FCR = "CHECKBOX_TELE_RES_FCR";
	public static String CHECKBOX_TELE_MOB_FCR = "CHECKBOX_TELE_MOB_FCR";
	public static String CHECKBOX_EMAIL_FCR = "CHECKBOX_EMAIL_FCR";
	public static String CHECKBOX_VISA_NO_FCR = "CHECKBOX_VISA_NO_FCR";
	public static String CHECKBOX_VISA_STATUS_FCR = "CHECKBOX_VISA_STATUS_FCR";
	public static String CHECKBOX_VISA_ISSUE_DATE_FCR = "CHECKBOX_VISA_ISSUE_DATE_FCR";
	public static String CHECKBOX_VISA_EXPIRY_DATE_FCR = "CHECKBOX_VISA_EXPIRY_DATE_FCR";
	public static String CHECKBOX_PROFESSION_FCR = "CHECKBOX_PROFESSION_FCR";
	public static String CHECKBOX_GENDER_FCR = "CHECKBOX_GENDER_FCR";
	public static String CHECKBOX_EMP_NAME_FCR = "CHECKBOX_EMP_NAME_FCR";
	public static String CHECKBOX_DOB_FCR = "CHECKBOX_DOB_FCR";
	public static String CHECKBOX_PASSPORT_NO_FCR = "CHECKBOX_PASSPORT_NO_FCR";
	public static String CHECKBOX_PASS_ISS_DT_FCR = "CHECKBOX_PASS_ISS_DT_FCR";
	public static String CHECKBOX_PASS_EXP_DT_FCR = "CHECKBOX_PASS_EXP_DT_FCR";
	//MANUAL
	
	public static String MANUAL_PASSTYPE = "passtype_manual";
	public static String MANUAL_VISASTATUS = "visaStatus_manual";
	public static String MANUAL_SHORTNAME = "ShortName_Manual";
	public static String MANUAL_VISANO = "visano_manual";
	public static String MANUAL_PREFIX= "prefix_manual";
	public static String MANUAL_FIRSTNAME= "firstname_manual";
	public static String MANUAL_LASTNAME= "lastname_manual";
	public static String MANUAL_NAME= "name_manual";
	public static String MANUAL_MOTHERNAME= "mothername_manual";
	public static String MANUAL_EIDANO= "eidano_manual";
	public static String MANUAL_PROFESSION = "profession_manual";
	public static String CHECKBOX_SELECTALL_MANUAL= "CHECKBOX_SELECTALL_MANUAL";    
	public static String CHECKBOX_PREFIX_MANUAL= "CHECKBOX_PREFIX_MANUAL";
	public static String CHECKBOX_FIRSTNAME_MANUAL= "CHECKBOX_FIRSTNAME_MANUAL";
	public static String CHECKBOX_LASTNAME_MANUAL= "CHECKBOX_LASTNAME_MANUAL"; 
	public static String CHECKBOX_FULLNAME_MANUAL= "CHECKBOX_FULLNAME_MANUAL";
	public static String CHECKBOX_SHORTNAME_MANUAL= "CHECKBOX_SHORTNAME_MANUAL";  
	public static String CHECKBOX_MOTHERSNAME_MANUAL= "CHECKBOX_MOTHERSNAME_MANUAL";
	public static String CHECKBOX_EIDANO_MANUAL= "CHECKBOX_EIDANO_MANUAL";
	public static String MANUAL_RESIDENT="Resident_Manual";
	public static String MANUAL_PER_CNTRY="per_cntry_manual";
	public static String MANUAL_PH="ph_manual";
	public static String MANUAL_MOBILE="mobile_manual";
	public static String MANUAL_EMAIL="email_manual";
	public static String MANUAL_DOB="dob_manual";
	public static String MANUAL_PASSPORTNO="passportno_manual";
	public static String MANUAL_PASSPORTISSDATE="passportissdate_manual";
	public static String MANUAL_ADDRESS="address_manual";	
	public static String MANUAL_CNTRY="cntry_manual";	
	public static String MANUAL_STATE="state_manual";	
	public static String MANUAL_CITY="city_manual";
	public static String CHECKBOX_CORR_POB_MANUAL = "CHECKBOX_CORR_POB_MANUAL";
	public static String CHECKBOX_CNTRY_OF_CORR_MANUAL	= "CHECKBOX_CNTRY_OF_CORR_MANUAL";
	public static String CHECKBOX_STATE_MANUAL	= "CHECKBOX_STATE_MANUAL";	
	public static String CHECKBOX_CITY_MANUAL = "CHECKBOX_CITY_MANUAL";
	public static String MANUAL_PASSPORTEXPDATE="passportexpdate_manual";
	public static String MANUAL_NATIONALITY="nationality_manual";
	public static String MANUAL_COUNTRYBIRTH="countryBirth_manual";
	public static String CRO_BANK_DECISION = "CRO_BANK_DECISION";
	public static String MANUAL_VISAISSDATE="visaissdate_manual";
	public static String MANUAL_VISAEXPDATE="visaexpdate_manual";
	public static String MANUAL_GENDER="gender_manual";
	public static String MANUAL_EMPLYR_NAME="emplyr_name_manual";
	public static String CHECKBOX_PASSPORT_TYPE_MANUAL = "CHECKBOX_PASSPORT_TYPE_MANUAL";
	public static String CHECKBOX_NATIONALITY_MANUAL = "CHECKBOX_NATIONALITY_MANUAL";
	public static String CHECKBOX_COB_MANUAL = "CHECKBOX_COB_MANUAL";
	public static String CHECKBOX_COUNTRY_RES_MANUAL = "CHECKBOX_COUNTRY_RES_MANUAL";
	public static String CHECKBOX_COUNTRY_PER_RES_MANUAL = "CHECKBOX_COUNTRY_PER_RES_MANUAL";
	public static String CHECKBOX_TELE_RES_MANUAL = "CHECKBOX_TELE_RES_MANUAL";
	public static String CHECKBOX_TELE_MOB_MANUAL = "CHECKBOX_TELE_MOB_MANUAL";
	public static String CHECKBOX_EMAIL_MANUAL = "CHECKBOX_EMAIL_MANUAL";
	public static String CHECKBOX_VISA_NO_MANUAL = "CHECKBOX_VISA_NO_MANUAL";
	public static String CHECKBOX_VISA_STATUS_MANUAL = "CHECKBOX_VISA_STATUS_MANUAL";
	public static String CHECKBOX_VISA_ISSUE_DATE_MANUAL = "CHECKBOX_VISA_ISSUE_DATE_MANUAL";
	public static String CHECKBOX_VISA_EXPIRY_DATE_MANUAL = "CHECKBOX_VISA_EXPIRY_DATE_MANUAL";
	public static String CHECKBOX_PROFESSION_MANUAL = "CHECKBOX_PROFESSION_MANUAL";
	public static String CHECKBOX_GENDER_MANUAL = "CHECKBOX_GENDER_MANUAL";
	public static String CHECKBOX_EMP_NAME_MANUAL = "CHECKBOX_EMP_NAME_MANUAL";
	public static String CHECKBOX_DOB_MANUAL = "CHECKBOX_DOB_MANUAL";
	public static String CHECKBOX_PASSPORT_NO_MANUAL = "CHECKBOX_PASSPORT_NO_MANUAL";
	public static String CHECKBOX_PASS_ISS_DT_MANUAL = "CHECKBOX_PASS_ISS_DT_MANUAL";
	public static String CHECKBOX_PASS_EXP_DT_MANUAL = "CHECKBOX_PASS_EXP_DT_MANUAL";

	//EIDA
	public static String PASSPORTEXPPLACE_FCR = "passportexpplace_fcr";
	public static String PASSPORTEXPPLACE_MANUAL = "passportexpplace_MANUAL";
	public static String EIDA_SHORTNAME = "shortname_eida";
	public static String EIDA_PREFIX = "prefix_eida";
	public static String EIDA_FIRSTNAME = "firstname_eida";
	public static String EIDA_LASTNAME = "lastname_eida";
	public static String EIDA_NAME = "name_eida";
	public static String EIDA_MOTHERNAME= "mothername_eida";
	public static String EIDA_EIDANO= "eidano_eida";
	public static String EIDA_EXPIRY_DATE = "EIDA_EXPIRY_DATE";  //Added by Shivanshu ATP-377 for Eida Expiry Date
	public static String CHECKBOX_SELECTALL_EIDA = "CHECKBOX_SELECTALL_EIDA";
	public static String CHECKBOX_PREFIX_EIDA   = "CHECKBOX_PREFIX_EIDA";
	public static String CHECKBOX_FIRSTNAME_EIDA = "CHECKBOX_FIRSTNAME_EIDA";
	public static String CHECKBOX_LASTNAME_EIDA = "CHECKBOX_LASTNAME_EIDA";
	public static String CHECKBOX_FULLNAME_EIDA  = "CHECKBOX_FULLNAME_EIDA";
	public static String CHECKBOX_SHORTNAME_EIDA = "CHECKBOX_SHORTNAME_EIDA";
	public static String CHECKBOX_MOTHERSNAME_EIDA= "CHECKBOX_MOTHERSNAME_EIDA";
	public static String CHECKBOX_EIDANO_EIDA= "CHECKBOX_EIDANO_EIDA";
	public static String EIDA_RESIDENT="Resident_EIDA";
	public static String EIDA_PER_CNTRY="per_cntry_eida";
	public static String EIDA_PH="ph_eida";
	public static String EIDA_MOBILE="mobile_eida";
	public static String EIDA_EMAIL="email_eida";
	public static String EIDA_DOB="dob_eida";
	public static String EIDA_PASSPORTNO="passportno_eida";
	public static String EIDA_PASSPORTISSDATE="passportissdate_eida";
	public static String EIDA_ADDRESS="address_eida";	
	public static String EIDA_CNTRY="cntry_eida";	
	public static String EIDA_STATE="state_eida";	
	public static String EIDA_CITY="city_eida";	
	public static String CHECKBOX_CORR_POB_EIDA = "CHECKBOX_CORR_POB_EIDA";
	public static String CHECKBOX_CNTRY_OF_CORR_EIDA	= "CHECKBOX_CNTRY_OF_CORR_EIDA";
	public static String CHECKBOX_STATE_EIDA	= "CHECKBOX_STATE_EIDA";	
	public static String CHECKBOX_CITY_EIDA = "CHECKBOX_CITY_EIDA";
	public static String EIDA_PASSPORTEXPDATE="passportexpdate_eida";
	public static String EIDA_PSSTYPE="psstype_eida";
	public static String EIDA_NATIONALITY="nationality_eida";
	public static String EIDA_COUNTRYBIRTH="countryBirth_eida";
	public static String EIDA_VISANO="visano_eida";
	public static String EIDA_VISASTATUS="visaStatus_eida";
	public static String EIDA_VISAISSDATE="visaissdate_eida";
	public static String EIDA_VISAEXPDATE="visaexpdate_eida";
	public static String EIDA_PROFESSION="profession_eida";
	public static String EIDA_GENDER="gender_eida";
	public static String EIDA_EMPLYR_NAME="emplyr_name_eida";
	public static String CHECKBOX_PASSPORT_TYPE_EIDA = "CHECKBOX_PASSPORT_TYPE_EIDA";
	public static String CHECKBOX_NATIONALITY_EIDA = "CHECKBOX_NATIONALITY_EIDA";
	public static String CHECKBOX_COB_EIDA = "CHECKBOX_COB_EIDA";
	public static String CHECKBOX_COUNTRY_RES_EIDA = "CHECKBOX_COUNTRY_RES_EIDA";
	public static String CHECKBOX_COUNTRY_PER_RES_EIDA = "CHECKBOX_COUNTRY_PER_RES_EIDA";
	public static String CHECKBOX_TELE_RES_EIDA = "CHECKBOX_TELE_RES_EIDA";
	public static String CHECKBOX_TELE_MOB_EIDA = "CHECKBOX_TELE_MOB_EIDA";
	public static String CHECKBOX_EMAIL_EIDA = "CHECKBOX_EMAIL_EIDA";
	public static String CHECKBOX_VISA_NO_EIDA = "CHECKBOX_VISA_NO_EIDA";
	public static String CHECKBOX_VISA_STATUS_EIDA = "CHECKBOX_VISA_STATUS_EIDA";
	public static String CHECKBOX_VISA_ISSUE_DATE_EIDA = "CHECKBOX_VISA_ISSUE_DATE_EIDA";
	public static String CHECKBOX_VISA_EXPIRY_DATE_EIDA = "CHECKBOX_VISA_EXPIRY_DATE_EIDA";
	public static String CHECKBOX_PROFESSION_EIDA = "CHECKBOX_PROFESSION_EIDA";
	public static String CHECKBOX_GENDER_EIDA = "CHECKBOX_GENDER_EIDA";
	public static String CHECKBOX_EMP_NAME_EIDA = "CHECKBOX_EMP_NAME_EIDA";
	public static String CHECKBOX_DOB_EIDA = "CHECKBOX_DOB_EIDA";
	public static String CHECKBOX_PASSPORT_NO_EIDA = "CHECKBOX_PASSPORT_NO_EIDA";
	public static String CHECKBOX_PASS_ISS_DT_EIDA = "CHECKBOX_PASS_ISS_DT_EIDA";
	public static String CHECKBOX_PASS_EXP_DT_EIDA = "CHECKBOX_PASS_EXP_DT_EIDA";
	
	//Personal Details Tab
	public static String SECRET_QUES = "secret_question";
	public static String CONGCIERGE = "concierge";
	public static String CK_PER_DET = "ck_per_det";
	public static String CHK_CONTACT_DET = "chk_contact_det";
	public static String CHK_INTERNAL_SEC = "chk_internal_sec";
	public static String CHK_BANKING_RELATION = "chk_banking_relation";
	public static String SEC_PERSONAL_DET = "SEC_PERSONAL_DET";
	public static String PD_OTHERS = "PD_OTHERS";
	public static String PD_FULLNAME = "PD_FULLNAME";
	public static String PD_SHORTNAME = "PD_SHORTNAME";
	public static String PD_MOTHERMAIDENNAME = "pd_mothermaidenname";
	public static String PD_EIDANO = "PD_EIDANO";
	public static String PD_CUSTSEGMENT = "PD_CUSTSEGMENT";
	public static String PD_CUSTRELTYPE = "PD_CUSTRELTYPE";
	public static String PD_NEWRELTYPE = "PD_NEWRELTYPE";
	public static String PD_DATEOFATTAININGMAT = "PD_DATEOFATTAININGMAT";
	public static String PD_MARITALSTATUSOTHER = "PD_MARITALSTATUSOTHER";
	public static String SEC_CONTACT_DET_CP = "SEC_CONTACT_DET_CP";
	public static String PERM_CNTRY = "perm_cntry";
	public static String CP_OTHERS = "CP_OTHERS";
	public static String CP_FLOOR = "CP_FLOOR";
	public static String CP_STREET = "CP_STREET";
	public static String CP_CITY = "cp_city";
	public static String CP_TELEOFFICE = "CP_TELEOFFICE";
	public static String SEC_CONTACT_DET_PA = "SEC_CONTACT_DET_PA";
	public static String CP_POBOXNO = "CP_POBOXNO"; 
	public static String CORR_STATE = "corr_state"; 
	public static String CORR_CNTRY = "corr_cntry";
	public static String CP_PHONENO = "CP_PHONENO";
	public static String CP_MOBILE = "CP_MOBILE";
	public static String CP_EMAIL = "CP_EMAIL";
	public static String COR_MAKANI = "cor_makani";
	public static String PERM_MAKANI = "perm_makani";
	public static String PA_SAMEAS = "PA_SAMEAS";
	public static String CP_SAMEAS = "CP_SAMEAS";
	public static String PA_PERM_CNTRY = "PA_PERM_CNTRY";
	public static String PA_PERM_STATE = "PA_PERM_STATE";
	public static String PERM_STATE = "perm_state";
	public static String PA_OTHERS = "PA_OTHERS";
	public static String PA_BUILDINGNAME = "PA_BUILDINGNAME";
	public static String PA_VILLAFLATNO = "PA_VILLAFLATNO";
	public static String PA_STREET = "PA_STREET";
	public static String PA_CITY = "PA_CITY";
	public static String OTHER_RESIDENTIAL_CITY = "other_res_city";
	public static String OTHER_PERM_CITY = "other_perm_city";
	public static String SEC_CONTACT_DET_RA = "SEC_CONTACT_DET_RA";
	public static String RA_SAMEAS = "RA_SAMEAS";
	public static String RES_CNTRY = "res_cntry";
	public static String RES_STATE = "res_state";
	public static String RA_BUILDINGNAME = "RA_BUILDINGNAME";
	public static String RA_VILLAFLATNO = "RA_VILLAFLATNO";
	public static String RA_STREET = "RA_STREET";
	public static String RA_CITY = "RA_CITY";
	public static String OTHER_RES_CITY = "other_res_city";
	public static String IDS_CB_SAL_TRANSFER = "IDS_CB_SAL_TRANSFER";
	public static String IDS_CB_MORTGAGES = "IDS_CB_MORTGAGES";
	public static String IDS_CB_INSURANCE = "IDS_CB_INSURANCE";
	public static String IDS_CB_TRB = "IDS_CB_TRB";
	public static String IDS_CB_OTHERS = "IDS_CB_OTHERS";
	public static String IDS_CB_VVIP = "IDS_CB_VVIP";
	public static String IDS_PC_CB_TP = "IDS_PC_CB_TP";
	public static String IDS_BNFT_CB_TP = "IDS_BNFT_CB_TP";
	public static String IDS_PC_CB_ENTERTAINMENT = "IDS_PC_CB_ENTERTAINMENT";
	public static String IDS_PC_CB_SHOPPING = "IDS_PC_CB_SHOPPING";
	public static String IDS_PC_CB_SPORT = "IDS_PC_CB_SPORT";
	public static String IDS_PC_CB_TRAVEL = "IDS_PC_CB_TRAVEL";
	public static String IDS_OTH_CB_OTHERS = "IDS_OTH_CB_OTHERS";
	public static String IDS_PROF_CENTER_CODE = "IDS_PROF_CENTER_CODE";
	public static String IDS_REF_BY_CUST = "IDS_REF_BY_CUST";
	public static String IDS_PC_BN_TP = "public static String";
	public static String BTN_FCR_SRCH = "BTN_FCR_SRCH";
	public static String BTN_PRD_SEARCH = "product_search";

	//KYC
	public static String CHK_GEN_INFO = "chk_gen_info";
	public static String CHK_EMP_DETAIL = "chk_emp_detail";
	public static String CHK_FUNDING_INFO = "chk_funding_info";
	public static String CHK_RISK_ASS = "chk_risk_ass";
	public static String IS_SIGN_UPDATE = "Is_Sign_Update";  
	public static String NIG_CPDMAKER = "NIG_CPDMAKER";
	public static String NIG_CPDCHECKER = "NIG_CPDCHECKER";
	public static String SEC_GEN_INFO = "SEC_GEN_INFO";  //Frame28
	public static String GI_EXST_SINCE = "GI_EXST_SINCE"; //Mask12
	public static String GI_DATE_KYC_PREP = "GI_DATE_KYC_PREP"; //Mask13
	public static String GI_IS_CUST_VIP = "GI_IS_CUST_VIP"; //combo51
	public static String GI_PURPOSE_ACC_REL = "GI_PURPOSE_ACC_REL"; //combo59
	public static String GI_YEARS_IN_UAE = "GI_YEARS_IN_UAE"; //text9
	public static String GI_ACC_NO_COVERED = "GI_ACC_NO_COVERED"; //text81
	public static String PROFESION = "profession";
	public static String SEC_EMPLYMNT_DETAILS = "SEC_EMPLYMNT_DETAILS"; //frame27
	public static String ED_OTHER = "ED_OTHER"; //text82
	public static String ED_EMPNAME = "ED_EMPNAME"; //text83
	public static String ED_EMPLYID = "ED_EMPLYID"; //text84
	public static String ED_EMP_TYPE = "ED_EMP_TYPE"; //combo56
	public static String ED_SET_FLG = "ED_SET_FLG"; //combo57
	public static String ED_CB_TML = "ED_CB_TML"; //check104
	public static String ED_CB_NON_TML = "ED_CB_NON_TML"; //check105
	public static String ED_DATE_OF_JOING = "ED_DATE_OF_JOING"; //mask14
	public static String ED_POSITN_DESGNT = "ED_POSITN_DESGNT"; //text78
	public static String ED_NATURE_OF_BUSNS = "ED_NATURE_OF_BUSNS";  //text160
	public static String ED_LEN_OF_SERVCE = "ED_LEN_OF_SERVCE"; //text159
	public static String ED_PHNE_NO = "ED_PHNE_NO"; //text74
	public static String ED_PERC_OF_OWNRSHP = "ED_PERC_OF_OWNRSHP"; //text10
	public static String ED_COMP_WEBSITE = "ED_COMP_WEBSITE"; //text11
	public static String ED_MONTHLY_INCM = "ED_MONTHLY_INCM"; //text79
	
	public static String ED_CB_SAL_AED = "ED_CB_SAL_AED"; //checck106
	public static String ED_SAL_AED = "ED_SAL_AED"; //text72
	public static String ED_CB_INVSTMNT_RETN_AED = "ED_CB_INVSTMNT_RETN_AED"; //check107
	public static String ED_INVSTMNT_RETN_AED = "ED_INVSTMNT_RETN_AED"; //text73
	public static String ED_CB_INHT_AED = "ED_CB_INHT_AED"; //check108
	public static String ED_ANNUAL_INC = "ED_ANNUAL_INC"; //text80
	public static String ED_CB_REAL_INC_AED = "ED_CB_REAL_INC_AED"; //Check111
	public static String ED_REAL_INC_AED = "ED_REAL_INC_AED"; //text86
	public static String ED_INHT_AED = "ED_INHT_AED"; //text76
	public static String ED_CB_SALE_OF_ASST = "ED_CB_SALE_OF_ASST"; //Check110
	public static String ED_SALE_OF_ASST = "ED_SALE_OF_ASST"; //Text85
	public static String ED_CB_OTHERS = "ED_CB_OTHERS"; //Check109
	public static String ED_OTHERS = "ED_OTHERS"; //Text77
	public static String ED_CUST_CRS_BRDR_PAYMENT = "ED_CUST_CRS_BRDR_PAYMENT"; //Combo9
	public static String ED_PURPSE_CRS_BRDR_PAYMENT = "ED_PURPSE_CRS_BRDR_PAYMENT"; //Text13
	public static String ED_ANTCPATD_MNTHVAL_BRDER_PYMT = "ED_ANTCPATD_MNTHVAL_BRDER_PYMT"; //text15
	public static String ED_ANTCPATD_CRS_BRDER_PYMT = "ED_ANTCPATD_CRS_BRDER_PYMT"; //text14
	public static String ED_CNTRY_PYMT_RECVD = "ED_CNTRY_PYMT_RECVD"; //text16
	public static String ED_NO_UAE_OVRS_BRNCH = "ED_NO_UAE_OVRS_BRNCH"; //text152
	public static String SEC_FUND_EXP_RELTNSHP = "SEC_FUND_EXP_RELTNSHP"; //Frame30
	public static String FERS_GEO_CNTRY_FINANCL = "FERS_GEO_CNTRY_FINANCL"; //text70
	public static String FERS_EMD_CASH_ATM = "FERS_EMD_CASH_ATM"; //text66
	public static String FERS_NATRE_ACTVTY_FT = "FERS_NATRE_ACTVTY_FT"; //text71
	public static String FERS_EMW_CASH_ATM = "FERS_EMW_CASH_ATM"; //text67
	public static String FERS_EMD_CHQ_DRFT = "FERS_EMD_CHQ_DRFT"; //text65
	public static String FERS_EMW_CHQ_DRFT = "FERS_EMW_CHQ_DRFT"; //text68
	public static String FERS_EMD_TRNSFR_ONLN = "FERS_EMD_TRNSFR_ONLN"; //text62
	public static String FERS_EMW_TRNSFR_ONLN = "FERS_EMW_TRNSFR_ONLN"; //text69
	public static String SEC_ASSESS_OTH_INFO = "SEC_ASSESS_OTH_INFO"; //frame25
	public static String RA_IS_UAE_RESIDENT = "RA_IS_UAE_RESIDENT"; //combo43
	public static String RA_RSN_BNKNG_UAE = "RA_RSN_BNKNG_UAE"; //text6
	public static String RA_IS_CUST_WRKNG_UAE = "RA_IS_CUST_WRKNG_UAE"; //combo5
	public static String RA_IS_CUST_WRKNG_NON_UAE = "RA_IS_CUST_WRKNG_NON_UAE"; //combo6
	public static String RA_CB_GEN_TRDNG_CMPNY = "RA_CB_GEN_TRDNG_CMPNY"; //check73
	public static String RA_CB_PRECIOUS_STONE_DEALER = "RA_CB_PRECIOUS_STONE_DEALER";//check74
	public static String RA_CB_BULLN_COMMDTY_BROKR = "RA_CB_BULLN_COMMDTY_BROKR"; //check75
	public static String RA_CB_REAL_STATE_BROKR = "RA_CB_REAL_STATE_BROKR"; //check76
	public static String RA_CB_USD_AUTO_DEALER = "RA_CB_USD_AUTO_DEALER"; //check77
	public static String RA_CB_OTHERS = "RA_CB_OTHERS"; //check96
	public static String RA_CB_OTHERS_FLD = "RA_CB_OTHERS_FLD"; //textbox953
	public static String RA_IS_CUST_DEALNG_HAWALA = "RA_IS_CUST_DEALNG_HAWALA"; //combo39
	public static String RA_PRPSE_TAX_EVSN = "RA_PRPSE_TAX_EVSN"; //combo38
	public static String RA_IS_CUST_DEALNG_ARMAMNT = "RA_IS_CUST_DEALNG_ARMAMNT"; //combo37
	public static String RA_CARRYNG_EID_CARD = "RA_CARRYNG_EID_CARD"; //combo42
	public static String RA_IS_CUST_PEP = "RA_IS_CUST_PEP"; //combo36
	public static String RA_LIST_OF_CUST_PEP = "RA_LIST_OF_CUST_PEP"; //text7
	public static String RA_CUST_SRC_WEALTH = "RA_CUST_SRC_WEALTH"; //text8
	public static String RA_ADDTNL_CMNT = "RA_ADDTNL_CMNT"; //text59
	public static String SEC_BNK_REL_UAE_OVRS = "SEC_BNK_REL_UAE_OVRS"; //Frame32
	public static String BR_BANK_NAME_1 = "BR_BANK_NAME_1"; //text60
	public static String BR_CITY_CNTRY_1 = "BR_CITY_CNTRY_1"; //text61 
	public static String BR_BANK_NAME_2 = "BR_BANK_NAME_2"; //text90
	public static String BR_CITY_CNTRY_2 = "BR_CITY_CNTRY_2"; //text89
	public static String BR_BANK_NAME_3 = "BR_BANK_NAME_3"; //text93
	public static String BR_CITY_CNTRY_3 = "BR_CITY_CNTRY_3"; //text92
	public static String SEC_SIGN_OFF = "SEC_SIGN_OFF"; //Frame33
	public static String BR_STAFF_WHO_NAME_STMP = "BR_STAFF_WHO_NAME_STMP"; //text99
	public static String BR_LINE_MAN_NAME_STMP = "BR_LINE_MAN_NAME_STMP"; //text87
	public static String BR_BUSN_GRP_HEAD = "BR_BUSN_GRP_HEAD"; //text88
	public static String BR_BUSN_UNIT_HEAD = "BR_BUSN_UNIT_HEAD"; //text91
	//CRS
	public static String CRS_CHECKBOX = "CRS_CB"; 
	public static String SEC_CRS_DETAILS = "SEC_CRS_DETAILS"; //Frmae47
	public static String CRS_RES_PERM_ADRS_US = "CRS_RES_PERM_ADRS_US"; //combo45
	//public static String LVW_CRS_TAX_COUNTRY = "CRS_TaxCountryDetails";
	public static String DOC_REQ_QUEUE_CPD_LVW = "doc_req_queue_cpd";//DOC_REQ_QUEUE_CPD_LVW
	public static String CRS_CERTI_NO = "CRS_Certi_no";
	public static String CRS_CERTI_YES = "CRS_Certi_yes";
	public static String CRS_TAX_COUNTRY = "CRS_tax_country";
	public static String CRS_TAXPAYERIDENTIFICATIONNUMBER = "CRS_TaxPayerIdentificationNumber";
	public static String CRS_REASONNOTPROVIDINGTIN = "CRS_ReasonNotProvidingTin";
	public static String CRS_CITYOFBIRTH = "CRS_CITYOFBIRTH";
	public static String CRS_TAXCOUNTRYDETAILS = "CRS_TaxCountryDetails";
	public static String CRS_CLASSIFICATION = "CRS_Classification";
	public static String CRS_DATECLASSIFICATION = "CRS_DateClassification";
	public static String CRS_DATECERTIFICATION = "CRS_DateCertification";
	public static String CRS_ADD = "CRS_ADD";
	public static String CRS_REMOVE = "CRS_remove";
	public static String REASON_DESC = "reason_desc";
	//FATCA
	public static String FAT_US_PERSON = "FAT_US_PERSON"; //Combo50
	public static String FAT_LIABLE_TO_PAY_TAX = "FAT_LIABLE_TO_PAY_TAX"; //combo48
	public static String FAT_SSN = "FAT_SSN";//combo47
	public static String FAT_CUST_CLASSIFICATION = "FAT_CUST_CLASSIFICATION"; //combo44
	public static String sCustTxnTable = "usr_0_cust_txn";
	public static String CHECKBOX_FATCA = "CHECKBOX_FATCA";
	//Optionanl Product Tab
	public static String DEBIT_ACNO_NEW ="DEBIT_ACNO_NEW";
	public static String NEW_DEPOSIT_CID ="NEW_DEPOSIT_CID";
	public static String NEW_DEPOSIT_AMOUNT ="NEW_DEPOSIT_AMOUNT";
	public static String NEW_DEPOSIT_AMT_WORDS ="NEW_DEPOSIT_AMT_WORDS";
	public static String TENURE_DAYS ="TENURE_DAYS";
	public static String TENURE_MNTHS ="TENURE_MNTHS";
	public static String TENURE_YRS ="TENURE_YRS";
	public static String INTEREST ="INTEREST";
	public static String MAT_DEBIT_ACNO ="MAT_DEBIT_ACNO";
	public static String MAT_DEPOSITNO ="MAT_DEPOSITNO";
	public static String MAT_CREDIT_PRNCPL ="MAT_CREDIT_PRNCPL";
	public static String NEW_TENURE ="NEW_TENURE";
	public static String SAME_TENURE ="SAME_TENURE";
	public static String ROLL_OVER_PRNCPL ="ROLL_OVER_PRNCPL";
	public static String SPECIFY_TENURE ="SPECIFY_TENURE";
	public static String FULL_REDEMPTION ="FULL_REDEMPTION";
	public static String FULL_REDEMPTION_ACNO ="FULL_REDEMPTION_ACNO";
	public static String PARTIAL_REDEMPTION ="PARTIAL_REDEMPTION";
	public static String PARTIAL_REDEMPTION_ACNO ="PARTIAL_REDEMPTION_ACNO";
	
	/*yamini*/
	//-------------------------------------------------------DDE WORKSTEP
	//Customer Information Tab
	public static String COLUMNS_LVW_DEDUPE_RESULT = "CID,Name,CustomerIC,PassportNo,Email,Mobile,DebitCardNo,"
			+ "CreditCardNo,DOB,EIDANo,Nationality,System";
	public static String COLUMNS_LVW_DEL_PREF = "del_name,del_po_box,del_address,del_landmark,"
			+ "del_city,del_state,del_state_others,del_country,del_fax,del_zip_code,"
			+ "del_email,del_pref_lang,del_phone,wi_name,cid,nom_id,del_mob_no";
	public static String  DELIVERY_PREFERENCE = "DELIVERY_PREFRENCES_GRID";
	public static String OTHER_CORR_CITY = "other_corr_city";
	//Personal Details Tab
	public static String CONTACT_DETAILS_EMIRATES = "perm_state"; //res_state
//	public static String CONTACT_DETAILS_OTHERS = ""; //Text95
	public static String CONTACT_DETAILS_MAKANI_NO = "per_makani"; //per_makani
	public static String CONTACT_DETAILS_CITY_OTHERS = "other_resi_city"; //other_resi_city
	public static String[] SET_PERMANENT_DETAILS_CONTROLS_LIST = {CONTACT_DETAILS_EMIRATES,CONTACT_DETAILS_MAKANI_NO,
		RA_BUILDINGNAME,RA_VILLAFLATNO,RA_STREET,RA_CITY,CONTACT_DETAILS_CITY_OTHERS};//CONTACT_DETAILS_OTHERS
	//QDE KYC
	//public static String RA_CUSTOMER_SEGMENT = "RA_CUSTOMER_SEGMENT";
	public static String RA_IS_CUST_VVIP = "RA_IS_CUST_VVIP";
	public static String RA_SIGN_TYPE = "RA_SIGN_TYPE";
	public static String RA_TAX_EVASION = "RA_TAX_EVASION";
	public static String RA_VISA_STATUS = "RA_VISA_STATUS";
	public static String RA_CUST_DEALING_HAWALA = "RA_CUST_DEALING_HAWALA";
	public static String RA_CUST_DEALING_ARMAMENT = "RA_CUST_DEALING_ARMAMENT";
	public static String RA_PASSPORT_TYPE = "RA_PASSPORT_TYPE";
	public static String RA_RESIDENCY_STATUS = "RA_RESIDENCY_STATUS";
	public static String RA_EMP_TYPE = "RA_EMP_TYPE";
	public static String QDE_KYC = "QDE_KYC";
	public static String QDE_KYC_CLIENT = "QDE_KYC_CLIENT";
	//CRS DETAILSQDE_KYC_CLIENT
	public static String CRS_CERTIFICATION_OBTAINED = "CRS_CERTIFICATION_OBTAINED";
	public static String CRS_RESN_DECRPTN = "CRS_RESN_DECRPTN";
	//ACCOUNT RELATION TAB
	public static String NO_OF_CUST_SEARCHED = "NO_OF_CUST_SEARCHED";
	public static String LODGEMENT_NO = "LODGEMENT_NO";
	//HIDDEN FIELDS 
	public static String HIDDEN_SEC_ACC_REL = "HIDDEN_SEC_ACC_REL";//section
	public static String SEC_ACC_REL = "SEC_ACC_REL";//section
	public static String CURR_WS_DETAIL = "CURR_WS_DETAIL";
	public static String SELECTED_ROW_INDEX = "SELECTED_ROW_INDEX";
	public static String BTN_CUSTOMER_SEARCH = "BTN_CUSTOMER_SEARCH";
	public static String  SANC_SCRN_MATCH_FOUND = "SANC_SCRN_MATCH_FOUND";
	public static String CUST_PROCESSED = "CUST_PROCESSED";
	public static String FRAME_CLIENTQUESTIONS = "Frame_ClientQuestions";
	public static String SECRET_QUESTION = "secret_question";
	public static String SECRET_ANS = "secret_ans";
	public static String CONCIERGE = "concierge";
	public static String HD_THREE = "HD_THREE";
	public static String HD_BTN = "HD_BTN"; //Command46
	public static String SMS_FLAG = "SMS_FLAG";
	public static String IVR_FLAG = "IVR_FLAG";
	public static String RESIDENCY_STATUS = "RA_IS_UAE_RESIDENT";
	public static String TAX_EVASION = "RA_TAX_EVASION";
	public static String ARE_U_PEP = "RA_IS_CUST_PEP";
	public static String HAWALA = "RA_CUST_DEALING_HAWALA";
	public static String DEALS_IN_ARMAMENT = "RA_CUST_DEALING_ARMAMENT";
	public static String SIGNATUREPRESENTFLAG = "SIGNATUREPRESENTFLAG";
	public static String ESTATEMENT_REGISTERED = "ESTATEMENT_REGISTERED";
	public static String CUSTOMER_OPEN_DATE = "CUSTOMER_OPEN_DATE";
	public static String MIB_FLAG = "MIB_FLAG";
	public static String INDICIACOMBO = "indiciacombo";
	public static String CNTRY_OF_BIRTH = "cntry_of_birth";
	public static String PERM_COUNTRY = "perm_cntry";
	public static String DEL_MODE_YES = "DEL_MODE_YES";
	public static String DEL_MODE_NO = "DEL_MODE_NO";
	public static String CUST_SEGMENT1 = "RA_CUSTOMER_SEGMENT";
	public static String CUST_VVIP = "RA_IS_CUST_VVIP";
	public static String SIGN_STYLE1 = "RA_SIGN_TYPE";
	public static String SPECIAL_CAT = "special_cat";
	public static String IB_FLAG = "IB_FLAG";
	public static String STAFF_FLAG_EXISTING = "STAFF_FLAG_EXISTING";
	public static String CHEQUEBOOK_BLOCK = "CHEQUEBOOK_BLOCK";
	public static String PHOTOPRESENTFLAG = "PHOTOPRESENTFLAG";
	public static String TOUCHPOINTS = "TOUCHPOINTS";
	public static String TXT_CUSTOMERNAME = "TXT_CUSTOMERNAME";
	public static String EMPNAME = "EmpName";
	public static String CHK_PASSPORT_DE = "chk_passport_de";
	public static String CHK_ADD = "chk_add";
	public static String STANDING_INSTR = "STANDING_INSTR";
	public static String RA_OTHERS = "RA_OTHERS";
	public static String EMP_PH_CODE = "EMP_PH_CODE";
	public static String EMP_STATUS = "emp_status";
	public static String AO_INCOME_SRC = "ao_income_src";
	public static String US_INDICIA_MDM = "US_INDICIA_MDM";
	public static String FATCAMINI = "fatcamini";
	public static String NIG_MAKER = "NIG_MAKER";
	public static String CHANGE_IN_FATCA_3WAY_INPUTS = "change_in_fatca_3way_inputs";
	public static String FATCAMAIN = "fatcamain";
	public static String FATCAOPTION = "FATCAOPTION";
	public static String NIG_CHECKER = "NIG_CHECKER";
	public static String POACOMBO = "POAcombo";
	public static String COMBODOC = "Combodoc";
	public static String DATEPICKERCUST = "DatePickercust";
	public static String CRS_CB = "CRS_CB";
	public static String DATEPICKERW8 = "DatePickerW8";
	public static String IDS_BNFT_CB_OTHERS = "IDS_BNFT_CB_OTHERS";
	public static String RES_MAKANI = "res_makani";
	public static String IDS_RM_CODE = "ids_rm_code";
	public static String IDS_RM_NAME = "ids_rm_name";
	public static String IDS_PRO_CODE = "ids_pro_code";
	public static String ISD_BNFT_CB_TP = "ISD_BNFT_CB_TP";
	public static String FRAMEFATCA = "FrameFATCA";
	public static String BTN_VALIDATE = "validate";
	public static String BTN_VALIDATEFATCA = "validateFATCA";
	public static String SERVICE_PACKAGE = "SERVICE_PACKAGE";
	public static String HD_FOUR  = "HD_FOUR"; //checkbox 116
	public static String HD_FIVE = "HD_FIVE"; //checkbox 120 
	public static String HD_SIX = "HD_SIX";  //checkbox123 
	public static String BN_OTHERS = "BN_OTHERS";
	public static String LABEL_APPASSESS = "Label_Assess";
	public static String DOC_REQ_QUEUE_CPD = "doc_req_queue_cpd";
	//Frame77
	 
	//ngfuser properties
	public static String  EIDA_FULL_NAME = "eida_full_name";
	public static String  EIDA_EIDA_NO = "eida_eida_no";
	public static String  EIDA_PASS_NO = "eida_pass_no";
	public static String  EIDA_PASS_ISSUE_DATE = "eida_pass_issue_date";
	public static String  EIDA_PASS_EXP_DATE = "eida_pass_exp_date";
	public static String  PASSPORTEXPPLACE_EIDA = "passportexpplace_eida";
	public static String  EIDA_PASS_ISSUE_PLACE = "eida_pass_issue_place";
	public static String  MOTHER_NAME_EIDA = "mother_name_eida";
	public static String  EIDA_PHONE_NO = "eida_phone_no";
	public static String  EIDA_MOBILE_NO = "eida_mobile_no";
//	public static String  EIDA_PROFESSION = "eida_profession";
	public static String  EMPLYR_TYPE1 = "emplyr_type1";
	public static String  EIDA_OCC_TYPE = "eida_occ_type";
	public static String  PASSPORT_TYPE = "passport_type";
	public static String  EIDA_PASSPORT_TYPE = "eida_passport_type";
	public static String VIEW = "BTN_VIEW";
	public static String CITYBIRTH_MANUAL ="CRS_CITYOFBIRTH";
	public static String CITYBIRTH_FCR ="cityBirth_fcr";
	public static String CITYBIRTH_EIDA ="cityBirth_eida";
	public static String CUST_PREV_RISK = "CUST_PREV_RISK";
	public static String CUST_ID = "CUST_ID";
	public static String CUST_NAME = "CUST_NAME";
	public static String CUST_FCR_RISK = "CUST_FCR_RISK";
	public static String CUST_COM_APP = "CUST_COM_APP";
	public static String CUST_CUR_RISK = "CUST_CUR_RISK";
	public static String CUST_CUR_RISK_BANK = "CUST_CUR_RISK_BANK";
	public static String CUST_ASSESSMENT_DATE = "cust_assessment_date";
	public static String RISK_CLASSIFICATION = "risk_classification";
	public static String CPD_CUR_RISK_BANK = "CPD_CUR_RISK_BANK";
	public static String COMP_DEC = "COMP_DEC";
	public static String CPD_PREV_RISK = "CPD_PREV_RISK";
	public static String MOBILE_CHANGE_FLAG = "MOBILE_CHANGE_FLAG";
	public static String CHECKBOX_CNTRY_OF_CORR_EID = "CHECKBOX_CNTRY_OF_CORR_EIDA";
	public static String EMPLYR_NAME_FCR = "emplyr_name_fcr";
	public static String VISA_STATUS = "VISA_STATUS";
 	public static String NO_OF_CUST_PROCESSED = "NO_OF_CUST_PROCESSED";
 	public static String SRC_NAME_BTN = "SRC_NAME_BTN";
	public static String CT_BTN_RESETALL = "CT_BTN_RESETALL";
	//NGF Validation
	public static String USR_0_NOM_MAST = "usr_0_nom_mast";
	public static String DEL_PREF_RADIO = "DEL_PREF_RADIO";
	//populateComparisonFields 
	public static String[] LIST_OF_COLUMNS = {CHECKBOX_PREFIX_FCR, CHECKBOX_FULLNAME_FCR, CHECKBOX_SHORTNAME_FCR, 
		CHECKBOX_DOB_FCR, CHECKBOX_PASSPORT_NO_FCR, CHECKBOX_PASS_ISS_DT_FCR, CHECKBOX_PASS_EXP_DT_FCR, "CHECK17", 
		CHECKBOX_VISA_NO_FCR, CHECKBOX_VISA_ISSUE_DATE_FCR, CHECKBOX_VISA_EXPIRY_DATE_FCR, CHECKBOX_NATIONALITY_FCR, 
		CHECKBOX_MOTHERSNAME_FCR, CHECKBOX_EIDANO_FCR, CHECKBOX_CORR_POB_FCR, CHECKBOX_CITY_FCR, CHECKBOX_STATE_FCR, 
		CHECKBOX_CNTRY_OF_CORR_FCR, CHECKBOX_COUNTRY_PER_RES_FCR, CHECKBOX_TELE_RES_FCR, CHECKBOX_TELE_MOB_FCR, 
		CHECKBOX_EMAIL_FCR, CHECKBOX_PROFESSION_FCR, CHECKBOX_GENDER_FCR, CHECKBOX_EMP_NAME_FCR, 
		CHECKBOX_PREFIX_EIDA, CHECKBOX_FULLNAME_EIDA, CHECKBOX_SHORTNAME_EIDA, CHECKBOX_DOB_EIDA, 
		CHECKBOX_PASSPORT_NO_EIDA, CHECKBOX_PASS_ISS_DT_EIDA, CHECKBOX_PASS_EXP_DT_EIDA, "CHECK62", 
		CHECKBOX_VISA_NO_EIDA, CHECKBOX_VISA_ISSUE_DATE_EIDA, CHECKBOX_VISA_EXPIRY_DATE_EIDA, 
		CHECKBOX_NATIONALITY_EIDA, CHECKBOX_MOTHERSNAME_EIDA, CHECKBOX_EIDANO_EIDA, CHECKBOX_CORR_POB_EIDA, 
		CHECKBOX_CITY_EIDA, CHECKBOX_STATE_EIDA, CHECKBOX_CNTRY_OF_CORR_EIDA, CHECKBOX_COUNTRY_PER_RES_EIDA, 
		CHECKBOX_TELE_RES_EIDA, CHECKBOX_TELE_MOB_EIDA, CHECKBOX_EMAIL_EIDA, CHECKBOX_PROFESSION_EIDA, 
		CHECKBOX_GENDER_EIDA, CHECKBOX_EMP_NAME_EIDA, CHECKBOX_PREFIX_MANUAL, CHECKBOX_FULLNAME_MANUAL, 
		CHECKBOX_SHORTNAME_MANUAL, CHECKBOX_DOB_MANUAL, CHECKBOX_PASSPORT_NO_MANUAL, CHECKBOX_PASS_ISS_DT_MANUAL, 
		CHECKBOX_PASS_EXP_DT_MANUAL, "CHECK39", CHECKBOX_VISA_NO_MANUAL, CHECKBOX_VISA_ISSUE_DATE_MANUAL, 
		CHECKBOX_VISA_EXPIRY_DATE_MANUAL, CHECKBOX_NATIONALITY_MANUAL, CHECKBOX_MOTHERSNAME_MANUAL,
		CHECKBOX_EIDANO_MANUAL, CHECKBOX_CORR_POB_MANUAL,CHECKBOX_CITY_MANUAL, CHECKBOX_STATE_MANUAL, 
		CHECKBOX_CNTRY_OF_CORR_MANUAL, CHECKBOX_COUNTRY_PER_RES_MANUAL,CHECKBOX_TELE_RES_MANUAL,
		CHECKBOX_TELE_MOB_MANUAL,CHECKBOX_EMAIL_MANUAL, CHECKBOX_PROFESSION_MANUAL, CHECKBOX_GENDER_MANUAL,
		CHECKBOX_EMP_NAME_MANUAL, CHECKBOX_SELECTALL_FCR, CHECKBOX_SELECTALL_EIDA, CHECKBOX_SELECTALL_MANUAL, 
		CHECKBOX_COUNTRY_RES_FCR, CHECKBOX_COUNTRY_RES_EIDA, CHECKBOX_COUNTRY_RES_MANUAL, MANUAL_RESIDENT, 
		CHECKBOX_PASSPORT_TYPE_FCR, CHECKBOX_PASSPORT_TYPE_EIDA, CHECKBOX_PASSPORT_TYPE_MANUAL, 
		CHECKBOX_FIRSTNAME_FCR, CHECKBOX_LASTNAME_FCR, CHECKBOX_COB_FCR, HD_FOUR, CHECKBOX_FIRSTNAME_EIDA,
		CHECKBOX_LASTNAME_EIDA, CHECKBOX_COB_EIDA, HD_FIVE, CHECKBOX_FIRSTNAME_MANUAL, CHECKBOX_LASTNAME_MANUAL, 
		CHECKBOX_COB_MANUAL, HD_SIX, MANUAL_PASSTYPE, FCR_NATIONALITY, FCR_STATE, FCR_COUNTRYBIRTH, EIDA_COUNTRYBIRTH, FCR_GENDER, EIDA_GENDER, FCR_PREFIX, FCR_NAME, FCR_SHORTNAME, FCR_PASSPORTNO, 
		PASSPORTEXPPLACE_FCR,  FCR_VISANO, FCR_NATIONALITY,  FCR_MOTHERSNAME,  FCR_EIDANO,  FCR_ADDRESS, FCR_CITY, FCR_STATE, FCR_CNTRY, FCR_PER_CNTRY, FCR_PH, 
		FCR_MOBILE, FCR_EMAIL, FCR_PROFESSION, FCR_GENDER, EMPLYR_NAME_FCR, EIDA_PREFIX, EIDA_NAME, EIDA_SHORTNAME, EIDA_PASSPORTNO, PASSPORTEXPPLACE_EIDA, 
		EIDA_VISANO, EIDA_NATIONALITY, EIDA_MOTHERNAME, EIDA_EIDANO, EIDA_ADDRESS, EIDA_CITY, EIDA_STATE, EIDA_CNTRY, EIDA_PER_CNTRY, EIDA_PH, EIDA_MOBILE, EIDA_EMAIL, 
		EIDA_PROFESSION, EIDA_GENDER, EIDA_EMPLYR_NAME, MANUAL_NAME, MANUAL_SHORTNAME, MANUAL_PASSPORTNO, PASSPORTEXPPLACE_MANUAL, MANUAL_VISANO, MANUAL_MOTHERNAME,
		 MANUAL_EIDANO, MANUAL_ADDRESS, MANUAL_CITY, MANUAL_PH, MANUAL_MOBILE, MANUAL_EMAIL, MANUAL_PROFESSION, MANUAL_EMPLYR_NAME, FCR_DOB, FCR_PASSPORTEXPDATE, 
		 FCR_PASSPORTISSDATE, FCR_VISAEXPDATE, FCR_VISAISSDATE, EIDA_DOB, EIDA_PASS_EXP_DATE, EIDA_PASS_ISSUE_DATE, EIDA_VISAEXPDATE, EIDA_VISAISSDATE, MANUAL_PREFIX, 
		 MANUAL_NATIONALITY, MANUAL_STATE, MANUAL_CNTRY, MANUAL_PER_CNTRY, MANUAL_GENDER, SERVICE_PACKAGE, ESTATEMENT_FLAG, FCR_RISK, FCR_RESIDENT, EIDA_RESIDENT,
		 FCR_PASSTYPE, EIDA_PASSPORT_TYPE, MANUAL_FIRSTNAME, MANUAL_LASTNAME, CITYBIRTH_MANUAL, EIDA_FIRSTNAME, EIDA_LASTNAME, EIDA_COUNTRYBIRTH, CITYBIRTH_EIDA, 
		 FCR_FIRSTNAME, FCR_LASTNAME, FCR_COUNTRYBIRTH, CITYBIRTH_FCR, CHECKBOX_FIRSTNAME_FCR, CHECKBOX_LASTNAME_FCR, CHECKBOX_COB_FCR, HD_FOUR, 
		 CHECKBOX_FIRSTNAME_EIDA, CHECKBOX_LASTNAME_EIDA, CHECKBOX_COB_EIDA, HD_FIVE, CHECKBOX_FIRSTNAME_MANUAL, CHECKBOX_LASTNAME_MANUAL, CHECKBOX_COB_MANUAL, HD_SIX,
		 MANUAL_COUNTRYBIRTH, FCR_VISASTATUS, EIDA_VISASTATUS, MANUAL_VISASTATUS, CHECKBOX_VISA_STATUS_FCR, CHECKBOX_VISA_STATUS_EIDA, CHECKBOX_VISA_STATUS_MANUAL, 
		 MANUAL_DOB, MANUAL_PASSPORTISSDATE, MANUAL_PASSPORTEXPDATE, MANUAL_VISAEXPDATE, MANUAL_VISAISSDATE};
	public static String EIDA_COMBOS = EIDA_PREFIX+","+EIDA_NATIONALITY+","+EIDA_CITY+","+EIDA_STATE+","
		 +EIDA_PASSPORT_TYPE+","+EIDA_CNTRY+","+EIDA_RESIDENT+","+EIDA_PER_CNTRY;
	public static String CAT_BENEFIT_OTHER = "CAT_BENEFIT_OTHER";
	public static String IS_SALARY_TRANSFER_CAT_CHANGE = "IS_SALARY_TRANSFER_CAT_CHANGE";
	public static String IS_MORTAGAGE_CAT_CHANGE = "IS_MORTAGAGE_CAT_CHANGE";
	public static String IS_INSURANCE_CAT_CHANGE = "IS_INSURANCE_CAT_CHANGE";
	public static String IS_TRB_CAT_CHANGE = "IS_TRB_CAT_CHANGE";
	public static String IS_VVIP = "IS_VVIP";
	public static String IS_OTHERS_CAT_CHANGE = "IS_OTHERS_CAT_CHANGE";
	public static String IS_ENTERTAINMENT_CAT_CHANGE = "IS_ENTERTAINMENT_CAT_CHANGE";
	public static String IS_PREVILEGE_TP_CAT_CHANGE = "IS_PREVILEGE_TP_CAT_CHANGE";
	public static String IS_SHOPPING_CAT_CHANGE = "IS_SHOPPING_CAT_CHANGE";
	public static String IS_SPORT_CAT_CHANGE = "IS_SPORT_CAT_CHANGE";
	public static String IS_TRAVEL_CAT_CHANGE = "IS_TRAVEL_CAT_CHANGE";
	public static String IS_EXCELLENCY_TP_CAT_CHANGE = "IS_EXCELLENCY_TP_CAT_CHANGE";
	public static String IS_CAT_BENEFIT_OTHER = "IS_CAT_BENEFIT_OTHER";		
	public static String CURRENCY = "currency";
	
	public static String DBCOLUMNS="NATIONALITY_EIDA#EIDA_NATIONALITY$NAME_EIDA#EIDA_FULL_NAME$EIDANO_EIDA#EIDA_EIDA_NO$DOB_EIDA#EIDA_DOB$PASSPORTNO_EIDA#EIDA_PASS_NO$PASSPORTISSDATE_EIDA#EIDA_PASS_ISSUE_DATE$PASSPORTEXPDATE_EIDA#EIDA_PASS_EXP_DATE$PASSPORTEXPPLACE_EIDA#EIDA_PASS_ISSUE_PLACE$MOTHERNAME_EIDA#MOTHER_NAME_EIDA$ADDRESS_EIDA#EIDA_ADDRESS$CITY_EIDA#EIDA_CITY$STATE_EIDA#EIDA_STATE$PH_EIDA#EIDA_PHONE_NO$MOBILE_EIDA#EIDA_MOBILE_NO$EMAIL_EIDA#EIDA_EMAIL$PREFESSION_EIDA#EIDA_PROFESSION$PREFIX_EIDA#EIDA_PREFIX$EMPLYR_NAME_EIDA#EIDA_EMPLYR_NAME$GENDER_EIDA#EIDA_GENDER$EMPLYR_TYPE1#EIDA_OCC_TYPE$PASSPORT_TYPE#EIDA_PASSPORT_TYPE$VISANO_EIDA#EIDA_VISANO$VISAEXPDATE_EIDA#EIDA_VISAEXPDATE";
//sharan missing constants creating 29 apr 21
	public static String EDIT = "Edit";
	public static String INSTANT_DEL = "INSTANT_DEL";
	public static String DEL_MODE = "DEL_MODE";
	public static String DEL_EXCELLENCY_CNTR = "DEL_EXCELLENCY_CNTR";
	public static String DEL_BRNCH_COURIER = "DEL_BRNCH_COURIER";
	public static String DEL_BRNCH_NAME = "DEL_BRNCH_NAME";
	public static String CT_BTN_REFRESH = "CT_BTN_REFRESH";
	public static String NATION_CRO = "nation_cro";
	public static String MATCH_FOUND = "match_found";
	public static String MATCH = "match";
	public static String INTRNL_BLCKLICT_CMNTS = "INTRNL_BLCKLICT_CMNTS";
	public static String TRNSFR_FROM_ACC_NO = "trnsfr_from_acc_no";
	public static String AMT_TRNSFERED = "amt_trnsfered";
	public static String CHEQUE_BOOK_NO = "cheque_book_no";
	public static String UDF_Field = "UDF_Field";
	public static String UDF_Value = "UDF_Value";
	public static String udf_addRow = "udf_addRow";
	public static String udf_delRow = "udf_delRow";
	public static String ACC_COVERED_IN_FORM= "ACC_COVERED_IN_FORM";
	public static String SEARCH = "SEARCH";
	public static String IS_ETIHAD = "IS_ETIHAD";
	public static String  ADD = "ADD";
	public static String MODIFY = "MODIFY";
	public static String BTN_AI_CLOSE = "BTN_AI_CLOSE";
	public static String CPD_FCR_RISK = "CPD_FCR_RISK";
	public static String CPDRISK_CLASSIFICATION = "cpdrisk_classification";
	public static String CPD_CUR_RISK = "CPD_CUR_RISK";
	public static String CALCULATE = "Calculate";
	public static String TRSD_CHECK = "TRSD_CHECK";
	public static String TRSD_APPROVEDRESULT = "trsd_approvedResult";
	public static String BUSINESS_NATURE_SECTION_FRM = "BUSINESS_NATURE_SECTION";
	public static String CURR_WS_NAME = "CURR_WS_NAME";
	public static String EXCELLENCY_CENTER = "EXCELLENCY_CENTER";
	
	//CONTROL SETS
	public static String CONTROL_SET_DISABLE_PERSONAL_DETAILS = "CONTROL_SET_DISABLE_PERSONAL_DETAILS";
	public static String CONTROL_SET_FCR = "CONTROL_SET_FCR";
	public static String CONTROL_SET_EIDA = "CONTROL_SET_EIDA";
	public static String CONTROL_SET_MANUAL = "CONTROL_SET_MANUAL";
	
	// SANCTION SCREENING
	// DDE 
	public static String CHK_MATCH_FOUND= "CHK_MATCH_FOUND";
	public static String CHK_REMARKS= "CHK_REMARKS";
	public static String BTN_VIEWDETAILS_SANCT= "BTN_VIEWDETAILS_SANCT";
	public static String SANC_SCRN_MATCH= "SANC_SCRN_MATCH";
	public static String SANC_WRLD_CHK_REMARKS= "SANC_WRLD_CHK_REMARKS";
	public static String BTN_RECHECK_SANC= "BTN_RECHECK_SANC";
	public static String SEC_SS_TRSD = "SEC_SS_TRSD";
	public static String SEC_DEL_INST = "SEC_DEL_INST";
	public static String TRSD_CHANNEL_REF_NO = "TRSD_CHANNEL_REF_NO";
	public static String TRSD_CASE_ID = "TRSD_CASE_ID";
	public static String TRSD_NAME= "TRSD_NAME";
	public static String TRSD_SYS_CALC_RES= "TRSD_SYS_CALC_RES";
	public static String TRSD_FINAL_DECISION= "TRSD_FINAL_DECISION";
	public static String TRSD_APPROVAL_REQUIRED= "TRSD_APPROVAL_REQUIRED";
	public static String TRSD_ASSESSMENT_DATE= "TRSD_ASSESSMENT_DATE";
	public static String TRSD_SCREENING_DATE= "TRSD_SCREENING_DATE";
	public static String TRSD_ASSESSMENT_NEW= "TRSD_ASSESSMENT_NEW";
	public static String TRSD_REMARKS= "TRSD_REMARKS";
	public static String SANC_TRSD_HISTORY_LVW= "TRSD_HISTORY_LVW";
	public static String TRSD_HISTORY_LVW= "TRSD_ASSESS_HISTORY_LVW";
	public static String SANC_FINAL_ELIGIBILITY= "SANC_FINAL_ELIGIBILITY";
	public static String BTN_SANC_CALCULATE= "BTN_SANC_CALCULATE";
	public static String SEC_SS_RISK_ASSESS= "SEC_SS_RISK_ASSESS";
	public static String SANCT_RISK_CID= "SANCT_RISK_CID";
	public static String SANCT_RISK_NAME= "SANCT_RISK_NAME";
	public static String SANCT_RISK_CURRENT_RSK_SYSTEM= "SANCT_RISK_CURRENT_RSK_SYSTEM";
	public static String SANCT_RISK_CURRENT_RSK_BANK= "SANCT_RISK_CURRENT_RSK_BANK";
	public static String SANCT_RISK_PREVIOUS_RSK= "SANCT_RISK_PREVIOUS_RSK";
	public static String SANCT_RISK_FCR_RSK= "SANCT_RISK_FCR_RSK";
	public static String SANCT_RISK_COMPL_APP_REQ= "SANCT_RISK_COMPL_APP_REQ";
	public static String SANCT_RISK_INITIAL_ASSESS_DATE= "SANCT_RISK_INITIAL_ASSESS_DATE";
	public static String SANCT_RISK_RSK_CLSF= "SANCT_RISK_RSK_CLSF";
	public static String SANCT_CHKBOX_COMPL_AP= "SANCT_CHKBOX_COMPL_AP";
	public static String SANCT_RISK_ASSESS_LVW= "SANCT_RISK_ASSESS_LVW";
	public static String SANCT_RISK_ASSESS_MARKS= "SANCT_RISK_ASSESS_MARKS";
	public static String SANC_SCRN_HD2_LVW= "SANC_SCRN_HD2_LVW";
	public static String BTN_NEXT_CUST_SANCT= "BTN_NEXT_CUST_SANCT";
	public static String CRO_SYS_DEC = "CRO_SYS_DEC";
	 public static String SANC_SCRN_NAME = "SANC_SCRN_NAME";
	 public static String SANC_SCRN_NATIONALITY = "SANC_SCRN_NATIONALITY";
	 public static String SANC_SCRN_DOB = "SANC_SCRN_DOB";
	 public static String SANC_SCRN_PASS_NO = "SANC_SCRN_PASS_NO" ; 
	 public static String SANC_SCRN_PERIOD_EXP = "SANC_SCRN_PERIOD_EXP" ; 
	 public static String SANC_SCRN_DEPT = "SANC_SCRN_DEPT";
	 public static String SANC_SCRN_REMARKS = "SANC_SCRN_REMARKS";
	// DDE
	 public static String SANC_SYS_DEC = "SANC_SYS_DEC";
	 public static String CPD_BANK_DECISION = "CPD_BANK_DECISION";
	public static String BTN_VIEW = "BTN_VIEW";
	public static String USR_0_TRSD_DETAILS = "usr_0_trsd_details";	
	public static String TRSD_SYSTEM_CALCULATED_RESULT = "TRSD_SYSTEM_CALCULATED_RESULT";
	public static String TRSD_ASSESS_HISTORY_LVW = "TRSD_ASSESS_HISTORY_LVW";
	public static String RISK_CID = "RISK_CID";
	public static String RISK_NAME = "RISK_NAME";
	public static String RISK_CURRENT_RSK_SYSTEM = "RISK_CURRENT_RSK_SYSTEM";
	public static String RISK_CURRENT_RSK_BANK = "RISK_CURRENT_RSK_BANK";
	public static String RISK_PREVIOUS_RSK = "RISK_PREVIOUS_RSK";
	public static String RISK_FCR_RSK = "RISK_FCR_RSK";
	public static String RISK_COMPLIANCE_APP_REQ = "RISK_COMPLIANCE_APP_REQ";
	public static String RISK_INITIAL_ASSESS_DATE = "RISK_INITIAL_ASSESS_DATE";
	public static String RISK_RSK_CLASSIFICATION = "RISK_RSK_CLASSIFICATION";
	public static String RISK_ASSES_LVW = "RISK_ASSES_LVW";
	public static String CHECKBOX_COMPLIANCE_APPROVAL = "CHECKBOX_COMPLIANCE_APPROVAL";
	public static String BTN_TRSD_CHECK = "BTN_TRSD_CHECK";
	public static String RISK_ASSESS_MARKS = "RISK_ASSESS_MARKS";
	public static String FINAL_ELIGIBILITY = "FINAL_ELIGIBILITY"; //combo8
	public static String BTN_RE_CHECK = "BTN_RE_CHECK";
	public static String SEC_SS_CHECK_TYPE = "SEC_SS_CHECK_TYPE";
	public static String CHCK_INT_BLK_LVW = "CHCK_INT_BLK_LVW";
	public static String CHCK_MATCH_FOUND = "CHCK_MATCH_FOUND";
	public static String CHCK_REMARKS = "CHCK_REMARKS";
	public static String BTN_VIEW_DETAILS = "BTN_VIEW_DETAILS";
	public static String SEC_CRO_HIDDEN1 = "SEC_CRO_HIDDEN1";
	public static String CRO_NAME = "CRO_NAME";
	public static String CRO_NATIONALITY = "CRO_NATIONALITY";
	public static String CRO_DOB = "CRO_DOB";
	public static String CRO_PASS_NO = "CRO_PASS_NO";
	public static String CRO_PERIOD_EXP = "CRO_PERIOD_EXP";
	public static String CRO_DEPT = "CRO_DEPT";
	public static String CRO_CNTRL_BNK_BAD_LVW = "CRO_CNTRL_BNK_BAD_LVW";
	public static String BTN_CNTRL_BANK_URL = "BTN_CNTRL_BANK_URL";
	public static String CRO_MATCH_FOUND = "CRO_MATCH_FOUND";
	public static String CRO_REMARK = "CRO_REMARK";
	public static String BTN_CRO_VIEW_DETAILS = "BTN_CRO_VIEW_DETAILS";
	public static String BTN_CRO_ADD = "BTN_CRO_ADD";
	public static String BTN_CRO_DELETE = "BTN_CRO_DELETE";
	public static String BTN_CRO_MODIFY = "BTN_CRO_MODIFY";
	public static String SEC_CRO_HIDDEN2 = "SEC_CRO_HIDDEN2";
	public static String DOW_JONES_LVW = "DOW_JONES_LVW";
	public static String MTCH_FOUND = "MTCH_FOUND";
	public static String WRLD_CHCK_REMARKS = "WRLD_CHCK_REMARKS";
	public static String BTN_VIEWDETAILS = "BTN_VIEWDETAILS";
	public static String SEC_SS_CPD_TRSD = "SEC_SS_CPD_TRSD";
	public static String CPD_TRSD_CHANNEL_REF_NO = "CPD_TRSD_CHANNEL_REF_NO";
	public static String CPD_TRSD_CASE_ID = "CPD_TRSD_CASE_ID";
	public static String CPD_TRSD_NAME = "CPD_TRSD_NAME";
	public static String CPD_TRSD_SYS_CALC_RES = "CPD_TRSD_SYS_CALC_RES";
	public static String CPD_TRSD_FINAL_DECISION = "CPD_TRSD_FINAL_DECISION";
	public static String CPD_TRSD_APPROVAL_REQUIRED = "CPD_TRSD_APPROVAL_REQUIRED";
	public static String CPD_TRSD_ASSESSMENT_DATE = "CPD_TRSD_ASSESSMENT_DATE";
	public static String CPD_TRSD_SCREENING_DATE = "CPD_TRSD_SCREENING_DATE";
	public static String CPD_TRSD_ASSESSMENT_NEW = "CPD_TRSD_ASSESSMENT_NEW";
	public static String CPD_TRSD_HISTORY_LVW = "CPD_TRSD_HISTORY_LVW";
	public static String SEC_SS_CPD_CHECK_TYPE = "SEC_SS_CPD_CHECK_TYPE";
	public static String CPD_CHK_INT_BLK_LVW = "CPD_CHK_INT_BLK_LVW";
	public static String CPD_CHK_MATCH_FOUND = "CPD_CHK_MATCH_FOUND";
	public static String CPD_CHK_REMARKS = "CPD_CHK_REMARKS";
	public static String BTN_CHK_VIEW_DETAILS = "BTN_CHK_VIEW_DETAILS";
	public static String SEC_CPD_HIDDEN1 = "SEC_CPD_HIDDEN1";
	public static String CPD_NAME = "CPD_NAME";
	public static String CPD_NATIONALITY = "CPD_NATIONALITY";
	public static String CPD_DOB = "CPD_DOB";
	public static String CPD_PASS_NO = "CPD_PASS_NO";
	public static String CPD_PERIOD_EXP = "CPD_PERIOD_EXP";
	public static String CPD_DEPT = "CPD_DEPT";
	public static String CPD_CNTRL_BNK_BAD_LVW = "CPD_CNTRL_BNK_BAD_LVW";
	public static String BTN_CPD_CNTRL_URL = "BTN_CPD_CNTRL_URL";
	public static String CPD_MATCH_FOUND = "CPD_MATCH_FOUND";
	public static String CPD_REMARKS = "CPD_REMARKS";
	public static String BTN_CPD_VIEW_DETAILS = "BTN_CPD_VIEW_DETAILS";
	public static String BTN_CPD_ADD = "BTN_CPD_ADD";
	public static String BTN_CPD_DELETE = "BTN_CPD_DELETE";
	public static String BTN_CPD_MODIFY = "BTN_CPD_MODIFY";
	public static String SEC_CPD_HIDDEN2 = "SEC_CPD_HIDDEN2";
	public static String CPD_HD2_LVW = "CPD_HD2_LVW";
	public static String BTN_CPD_VIEWDETAILS = "BTN_CPD_VIEWDETAILS";
	public static String CPD_MTCH_FOUND = "CPD_MTCH_FOUND";
	public static String CPD_WRLD_CHK_REMARKS = "CPD_WRLD_CHK_REMARKS";
	public static String BTN_CPD_TRSD_CHK = "BTN_CPD_TRSD_CHK";
	public static String BTN_CPD_RE_CHK = "BTN_CPD_RE_CHK";
	public static String CPD_FINAL_ELIGIBILITY = "CPD_FINAL_ELIGIBILITY";
	public static String BTN_CALCULATE = "BTN_CALCULATE";
	public static String CPD_RISK_ASSESS_MARKS = "CPD_RISK_ASSESS_MARKS";
	public static String BTN_NEXT_CUST = "BTN_NEXT_CUST";
	public static String SEC_SS_CPD_RISK_ASSESS = "SEC_SS_CPD_RISK_ASSESS";
	public static String CPD_RISK_CID = "CPD_RISK_CID";
	public static String CPD_RISK_NAME = "CPD_RISK_NAME";
	public static String CPD__RISK_CURRENT_RSK_SYSTEM = "CPD__RISK_CURRENT_RSK_SYSTEM";
	public static String CPD_RISK_CURRENT_RSK_BANK = "CPD_RISK_CURRENT_RSK_BANK";
	public static String CPD_RISK_PREVIOUS_RSK = "CPD_RISK_PREVIOUS_RSK";
	public static String CPD_RISK_FCR_RSK = "CPD_RISK_FCR_RSK";
	public static String CPD_RISK_COMPL_APP_REQ = "CPD_RISK_COMPL_APP_REQ";
	public static String CPD_RISK_INITIAL_ASSESS_DATE = "CPD_RISK_INITIAL_ASSESS_DATE";
	public static String CPD_CHKBOX_COMPL_AP = "CPD_CHKBOX_COMPL_AP";
	public static String CPD_RISK_RSK_CLSF = "CPD_RISK_RSK_CLSF";
	public static String CPD_RISK_ASSESS_LVW = "CPD_RISK_ASSESS_LVW";
	public static String BTN_SUBMIT = "BTN_SUBMIT";
	public static String TEMP_GEN_QUEUE_LVW = "temp_gen_queue";
	public static String ED_CNTRY_PYMT_RECV = "ED_CNTRY_PYMT_RECV";
	public static String BTN_CHECK_VIEW_DETAILS = "BTN_CHECK_VIEW_DETAILS";
	public static String CHECK_TYPE_LVW = "CHECK_TYPE_LVW";
	public static String BTN_RECHECK = "BTN_RECHECK";
	public static String BTN_ADD_SANC_SCRN = "BTN_ADD_SANC_SCRN";
	public static String SANC_CNTRL_BNK_BAD_LVW = "SANC_CNTRL_BNK_BAD_LVW";
	public static String DEC_STORAGE_DETAILS = "DEC_STORAGE_DETAILS";
	public static String SEC_CI = "SEC_CI";
	public static String SEC_INT_DETAIL = "SEC_INT_DETAIL";
	public static String ACCREL_ACCRELATION = "ACCREL_ACCRELATION";
	public static String ACCREL_CUSTRELATION = "ACCREL_CUSTRELATION";
	public static String PRODQUE_CHQBOOK = "PRODQUE_CHQBOOK";
	public static String BTN_DOC_GEN_REFRESH = "BTN_DOC_GEN_REFRESH";
	
	public static String PER_INC_TAX_CON_1 = "PER_INC_TAX_CON_1";
	public static String PER_INC_TAX_CON_2 = "PER_INC_TAX_CON_2";
	public static String PER_INC_TAX_CON_3 = "PER_INC_TAX_CON_3";
	
	public static String SEC_ADD_NEW_CUSTOMER = "SEC_ADD_NEW_CUSTOMER";
	public static String SEC_SRCH_EXIST_CUST = "SEC_SRCH_EXIST_CUST";
	public static String Frame_ClientQuestions = "Frame_ClientQuestions";
	public static String FrameFATCA = "FrameFATCA";
	public static String SEC_ELIG_ANALYSIS = "SEC_ELIG_ANALYSIS";
	public static String P_ECB_CHQ_VALIDATION ="P_ECB_CHQ_VALIDATION";
	public static String P_ECB_REASON = "P_ECB_REASON";
	public static String PIC1 = "Pic1";
	public static String FINAL_RISK_VAL = "FINAL_RISK_VAL";
	public static String FINAL_RISK_VAL_CPD = "FINAL_RISK_VAL_CPD";
	public static String FINAL_CUSTOMER_RISK = "FINAL_CUSTOMER_RISK";
	public static String FETCH_BALANCE = "fetch_balance";
	public static String PHY_CONC_DISABLE[]={BTN_VIEWDETAILS_SANCT,SEC_CI,SEC_OPT_PROD,SEC_OPT_MI,SEC_OPT_OI,SEC_PERSONAL_DET,SEC_CRS_DETAILS,
		FRAME_CLIENTQUESTIONS,SEC_CONTACT_DET_RA,SEC_CONTACT_DET_PA,SEC_CONTACT_DET_CP,CK_PER_DET,CHK_CONTACT_DET,CHK_INTERNAL_SEC,
		CHECKBOX_FATCA,CRS_CB,SEC_INT_DETAIL,SEC_ACC_INFO_PD,SEC_ACC_INFO_AOR_MAKER,SEC_ACC_INFO_ECD,SEC_ACC_INFO_DCL,SEC_SI,SEC_DEL_INST,SEC_INTERNAL_DETL,
		SEC_OPT_PROD_CRO,SEC_DOC_REQ_CRO,SEC_CC_AORM,SEC_CC_AORC,L1_APP_REQ,L2_APP_REQ,L3_APP_REQ,L4_APP_REQ,SEC_GEN_INFO,SEC_EMPLYMNT_DETAILS,
		SEC_FUND_EXP_RELTNSHP,SEC_ASSESS_OTH_INFO,SEC_BNK_REL_UAE_OVRS,SEC_SIGN_OFF,FRAMEFATCA,BTN_CPD_TRSD_CHK,SEC_SS_CPD_TRSD,
		SEC_SS_CPD_RISK_ASSESS,CPD_FINAL_ELIGIBILITY,BTN_CALCULATE,CPD_RISK_ASSESS_MARKS,BTN_NEXT_CUST,BTN_TRSD_CHECK,SEC_SS_TRSD,
		FINAL_ELIGIBILITY,SEC_SS_RISK_ASSESS,RISK_ASSESS_MARKS,PD_ANY_CHNG_CUST_INFO,CHK_GEN_INFO,CHK_EMP_DETAIL,
		CHK_FUNDING_INFO,CHK_RISK_ASS,CHK_BANKING_RELATION,CHECKBOX_FATCA,SEC_RISK_ASSESS_CPD,
		SEC_ELIG_ANALYSIS_CPD,SEC_PRODUCTION_CPD,SEC_OPT_PROD_CPD,SEC_FACILITY_CPD,SEC_DOC_REQ_CPD,SEC_SI_SIRFT,SEC_SI_SWP};
	
	public static String SALARY_TRANSFER = "SALARY_TRANSFER";
	public static String DEALS_IN_WMD = "DEALS_IN_WMD";
	public static String FINANCIAL_BROKERS = "FINANCIAL_BROKERS";
	public static String NOTARY_PUBLIC = "NOTARY_PUBLIC";
	public static String SOCIAL_MEDIA_INFLUNCER = "SOCIAL_MEDIA_INFLUNCER";
	public static String TAX_SCHEME_OBTAINED = "TAX_SCHEME_OBTAINED";
	public static String RESI_UNDER_JUD = "RESI_UNDER_JUD";
	public static String SUB_PERSONAL_TAX = "SUB_PERSONAL_TAX";
	
	
	public static String EMP_COUNTRY = "EMP_COUNTRY";
	public static String EMP_STREET = "EMP_STREET";
	public static String EMP_CITY = "EMP_CITY";
	public static String EMP_PO_BOX = "EMP_PO_BOX";
	public static String EMP_STATE = "EMP_STATE";
	public static String EMP_STATE_OTHERS = "EMP_STATE_OTHERS";
	public static String EMP_CITY_OTHERS = "EMP_CITY_OTHERS";
	public static String[] OPTIONAL_PRODUCT = {SEC_OPT_PROD,SEC_OPT_MI,SEC_OPT_OI};
	public static String BTN_APP_LEVEL_RISK = "BTN_APP_LEVEL_RISK";
	public static String OVERDRAFT_CPD = "OVERDRAFT_CPD";
	public static String FD = "FD";
	public static String FD_CPD = "FD_CPD";
	public static String BULK_EOD_DEC = "BULK_EOD_DEC";
	public static String BULK_EOD_USER = "BULK_EOD_USER";
	public static String BULK_EOD_DATE = "BULK_EOD_DATE";
	public static String PHYSICAL_RECON_DECISION = "PHYSICAL_RECON_DECISION";
	public static String PHYSICAL_RECON_DATE = "PHYSICAL_RECON_DATE";
	public static String PHYSICAL_RECON_USER = "PHYSICAL_RECON_USER";
	public static String[]  BUSINESS_NATURE_SECTION ={RA_CB_GEN_TRDNG_CMPNY,RA_CB_PRECIOUS_STONE_DEALER,
		RA_CB_BULLN_COMMDTY_BROKR,RA_CB_REAL_STATE_BROKR,RA_IS_CUST_WRKNG_NON_UAE,RA_CB_OTHERS,BN_OTHERS,FINANCIAL_BROKERS,NOTARY_PUBLIC,SOCIAL_MEDIA_INFLUNCER,RA_CB_USD_AUTO_DEALER};
	public static String EIDANO_MANUAL = "eidano_manual";
	public static String READ_EIDA ="READ_EIDA";
	public static String EDIT1 ="Edit_1";
	public static String EDIT3 ="Edit_3";
	public static String BTN_FG_VALIDATE = "BTN_FG_VALIDATE";
	public static String BTN_FETCH_FAMILY = "BTN_FETCH_FAMILY";
	public static String LVW_FAMILY_MEMBERS = "LVW_FAMILY_MEMBERS";
	public static String OTHER_PERK_ALLOWANCES_AED ="OTHER_PERK_ALLOWANCES_AED";
	public static String ADDITIONAL_SOURCES_INCOME_AED ="ADDITIONAL_SOURCES_INCOME_AED";
	public static String EST_TOTAL_INCOME_PER_ANNUM ="EST_TOTAL_INCOME_PER_ANNUM";
	public static String IS_FAMILY_EXIST ="IS_FAMILY_EXIST";
	public static String PRIMARY_SRC_CTRY  ="Primary_src_ctry";

	//shahbaz
	public static String  KYC_CUST_BLACKLIST = "KYC_CUST_BLACKLIST";
	public static String  KYC_CUST_HAWALADRA_SERV = "KYC_CUST_HAWALADRA_SERV";
	public static String  KYC_CUST_NORTH_KORES_RESD = "KYC_CUST_NORTH_KORES_RESD";
	public static String  KYC_ENTITY_RESIDENT_JURISD = "KYC_ENTITY_RESIDENT_JURISD";
	
	public static String  CHANNEL_RISK_AO = "CHANNEL_RISK_AO";
	public static String  DUAL_NATIONALITY = "DUAL_NATIONALITY";
	public static String  ACC_IN_ANTHR_BNK_UAE = "ACC_IN_ANTHR_BNK_UAE";
	//Jamshed
	public static String  PRIVATE_CLIENT = "PRIVATE_CLIENT";
	
	//Reyaz
	public static String  KYC_CUST_BLACKLIST1 = "KYC_CUST_BLACKLIST1";
	public static String  KYC_BARRIER = "KYC_BARRIER";
	public static String  KYC_CUST_HAWALADRA = "KYC_CUST_HAWALADRA";
	public static String  KYC_PATNER_UBO = "kYC_PATNER_UBO";
	public static String  KYC_CUST_NORTH_KORES = "KYC_CUST_NORTH_KORES";
	public static String  KYC_MANUFACTURING = "KYC_MANUFACTURING";
	public static String  KYC_ENTITY_SHELL = "KYC_ENTITY_SHELL";
	public static String  KYC_LEGAL_GAMING = "KYC_LEGAL_GAMING";
	public static String  KYC_OFFICE_VELLI = "KYC_OFFICE_VELLI";
	public static String  KYC_VIRTUAL_CURRENCY = "KYC_VIRTUAL_CURRENCY";
	public static String  KYC_ENTITY_RE = "KYC_ENTITY_RE";
	public static String  KYC_NOMINEE = "KYC_NOMINEE";
	public static String  KYC_EXCEPTIONAL = "KYC_EXCEPTIONAL";
	public static String  POA_NATIONALITY = "POA_Nationality";  //Jamshed
	public static String  PRIMARY_SRC_CNTRY = "Primary_src_ctry";
	public static String  POA_RESIDENCY = "POA_RESIDENCY";  //SHivanshu ATP-455
	
	// FULFILLMENT CONSTANT
	public static String  PRE_FULFILLMENT = "PRE";
	public static String  POST_FULFILLMENT = "POST";
	public static String  NOT_APPLICABLE_FULFILLMENT = "NA";
	public static String  FULFILLMENT = "FULFILLMENT";
	public static String  GRID_FULFILLMENT ="fulfillmentTable";
	public static final String PM_FF_DATE_FORMAT="yyyy-MM-dd'T'HH:mm:ss:00";
	public static final String BLANK = "";
	
}
